# Code generated by `ubx sdk gen` from aws_ivs_playback_key_pairs. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PlaybackKeyPairs_KeyPairs:
    arn: Any = None
    name: Any = None
    tags: Any = None

@dataclasses.dataclass
class PlaybackKeyPairsConfig:
    max_results: Any = None
    next_token: Any = None

@dataclasses.dataclass
class PlaybackKeyPairsAttrs:
    key_pairs: Any = None
    max_results: Any = None
    next_token: Any = None

PlaybackKeyPairs = ubx.DataSourceBinding(
    wire_type="aws_ivs_playback_key_pairs",
    fields={
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
    },
)
