// Code generated by `ubx sdk gen` from aws_workmail_mobile_device_access_overrides. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface MobileDeviceAccessOverrides_Overrides {
  dateCreated?: string | Computed<string>;
  dateModified?: string | Computed<string>;
  description?: string | Computed<string>;
  deviceId?: string | Computed<string>;
  effect?: string | Computed<string>;
  userId?: string | Computed<string>;
}

export interface MobileDeviceAccessOverridesConfig {
  deviceId?: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  organizationId: string | Computed<string>;
  userId?: string | Computed<string>;
}

export interface MobileDeviceAccessOverridesAttrs {
  deviceId: string;
  maxResults: number;
  nextToken: string;
  organizationId: string;
  overrides: MobileDeviceAccessOverrides_Overrides[];
  userId: string;
}

export const MobileDeviceAccessOverrides: DataSourceBinding<MobileDeviceAccessOverridesConfig, MobileDeviceAccessOverridesAttrs> = {
  wireType: "aws_workmail_mobile_device_access_overrides",
  fields: {
    deviceId: "device_id",
    maxResults: "max_results",
    nextToken: "next_token",
    organizationId: "organization_id",
    userId: "user_id",
  },
};
