# Code generated by `ubx sdk gen` from aws_greengrassv2_components. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Components_Components_LatestVersion_Platforms:
    attributes: Any = None
    name: Any = None

@dataclasses.dataclass
class Components_Components_LatestVersion:
    arn: Any = None
    component_version: Any = None
    creation_timestamp: Any = None
    description: Any = None
    platforms: Any = None
    publisher: Any = None

@dataclasses.dataclass
class Components_Components:
    arn: Any = None
    component_name: Any = None
    latest_version: Any = None

@dataclasses.dataclass
class ComponentsConfig:
    max_results: Any = None
    next_token: Any = None
    scope: Any = None

@dataclasses.dataclass
class ComponentsAttrs:
    components: Any = None
    max_results: Any = None
    next_token: Any = None
    scope: Any = None

Components = ubx.DataSourceBinding(
    wire_type="aws_greengrassv2_components",
    fields={
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
        "scope": ubx.FieldSpec(wire_name="scope"),
    },
)
