// Code generated by `ubx sdk gen` from aws_bedrock_resource_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ResourcePolicyConfig {
  /** The IAM policy document defining access permissions for the guardrail and guardrail profile resources */
  policyDocument: unknown | Computed<unknown>;
  /** The ARN of the Bedrock Guardrail or Guardrail Profile resource */
  resourceArn: string | Computed<string>;
}

export interface ResourcePolicyAttrs {
  /** The IAM policy document defining access permissions for the guardrail and guardrail profile resources */
  policyDocument: unknown;
  /** The ARN of the Bedrock Guardrail or Guardrail Profile resource */
  resourceArn: string;
}

export const ResourcePolicy: ResourceBinding<ResourcePolicyConfig, ResourcePolicyAttrs> = {
  wireType: "aws_bedrock_resource_policy",
  fields: {
    policyDocument: "policy_document",
    resourceArn: "resource_arn",
  },
};
