// Code generated by `ubx sdk gen` from aws_data_pipeline_pipeline. DO NOT EDIT.
package data

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PipelinePipeline_ParameterObjects_Attributes struct {
	// The name of the attribute within a parameter object in an AWS Data Pipeline pipeline definition, used to specify parameter metadata such as 'description' or 'type'. (AI-inferred)
	Key any
	// The string value of an attribute within a parameter object, used to define a parameter's value in the pipeline definition. (AI-inferred)
	StringValue any
}

type PipelinePipeline_ParameterObjects struct {
	// Defines the list of key-value attribute pairs (ParameterAttribute) that specify the configuration of a parameter object, such as its default value and description, in the AWS Data Pipeline pipeline definition. (AI-inferred)
	Attributes any
	// The unique identifier for this parameter object within the pipeline's parameter definitions, used to reference it from pipeline expressions and resources. (AI-inferred)
	Id any
}

type PipelinePipeline_ParameterValues struct {
	// The identifier of a parameter defined in the pipeline's ParameterObjects list, used to map this value to that parameter. (AI-inferred)
	Id any
	// The string value assigned to a keyed parameter in the pipeline's parameter values, providing a runtime value to substitute into the pipeline definition at creation or update. (AI-inferred)
	StringValue any
}

type PipelinePipeline_PipelineObjects_Fields struct {
	// The key is the name of the field in a Data Pipeline object definition, such as 'name', 'type', or 'schedule'. (AI-inferred)
	Key any
	// The reference to another pipeline object's ID, used to link objects within the pipeline definition. (AI-inferred)
	RefValue any
	// Sets the literal string value for a field in a Data Pipeline object definition, used when the field holds a direct string rather than a reference to another pipeline object. (AI-inferred)
	StringValue any
}

type PipelinePipeline_PipelineObjects struct {
	// Defines the properties of each pipeline object via a list of key-value pairs (Field objects), which specify attributes such as name, type, schedule, and dependencies, either as literal values or references to other pipeline objects. (AI-inferred)
	Fields any
	// The unique identifier for this pipeline object within the pipeline definition, used to reference it from other objects. (AI-inferred)
	Id any
	// The user-defined name of a pipeline object within the AWS Data Pipeline definition. (AI-inferred)
	Name any
}

type PipelinePipeline_PipelineTags struct {
	// The key of a tag applied to the Data Pipeline, used to categorize and manage the pipeline within AWS. (AI-inferred)
	Key any
	// The value component of a key-value tag attached to the Data Pipeline, used for metadata and resource organization. (AI-inferred)
	Value any
}

var PipelinePipeline_ParameterObjects_AttributesFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"StringValue": ubx.FieldSpec{WireName: "string_value"},
	}

var PipelinePipeline_ParameterObjectsFields = ubx.FieldMap{
		"Attributes": ubx.FieldSpec{
			WireName: "attributes",
			Kind: "list",
			Fields: PipelinePipeline_ParameterObjects_AttributesFields,
		},
		"Id": ubx.FieldSpec{WireName: "id"},
	}

var PipelinePipeline_ParameterValuesFields = ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"StringValue": ubx.FieldSpec{WireName: "string_value"},
	}

var PipelinePipeline_PipelineObjects_FieldsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"RefValue": ubx.FieldSpec{WireName: "ref_value"},
		"StringValue": ubx.FieldSpec{WireName: "string_value"},
	}

var PipelinePipeline_PipelineObjectsFields = ubx.FieldMap{
		"Fields": ubx.FieldSpec{
			WireName: "fields",
			Kind: "list",
			Fields: PipelinePipeline_PipelineObjects_FieldsFields,
		},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
	}

var PipelinePipeline_PipelineTagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type PipelinePipelineConfig struct {
	// Indicates whether to validate and start the pipeline or stop an active pipeline. By default, the value is set to true.
	Activate any
	// A description of the pipeline.
	Description any
	// The name of the pipeline.
	Name any
	// The parameter objects used with the pipeline.
	ParameterObjects any
	// The parameter values used with the pipeline.
	ParameterValues any
	// The objects that define the pipeline. These objects overwrite the existing pipeline definition. Not all objects, fields, and values can be updated. For information about restrictions, see Editing Your Pipeline in the AWS Data Pipeline Developer Guide.
	PipelineObjects any
	// A list of arbitrary tags (key-value pairs) to associate with the pipeline, which you can use to control permissions. For more information, see Controlling Access to Pipelines and Resources in the AWS Data Pipeline Developer Guide.
	PipelineTags any
}

type PipelinePipelineAttrs struct {
	// Indicates whether to validate and start the pipeline or stop an active pipeline. By default, the value is set to true.
	Activate any
	// A description of the pipeline.
	Description any
	// The name of the pipeline.
	Name any
	// The parameter objects used with the pipeline.
	ParameterObjects any
	// The parameter values used with the pipeline.
	ParameterValues any
	// The unique identifier assigned by AWS to the pipeline. (AI-inferred)
	PipelineId any
	// The objects that define the pipeline. These objects overwrite the existing pipeline definition. Not all objects, fields, and values can be updated. For information about restrictions, see Editing Your Pipeline in the AWS Data Pipeline Developer Guide.
	PipelineObjects any
	// A list of arbitrary tags (key-value pairs) to associate with the pipeline, which you can use to control permissions. For more information, see Controlling Access to Pipelines and Resources in the AWS Data Pipeline Developer Guide.
	PipelineTags any
}

var PipelinePipeline = ubx.ResourceBinding{
	WireType: "aws_data_pipeline_pipeline",
	Fields: ubx.FieldMap{
		"Activate": ubx.FieldSpec{WireName: "activate"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ParameterObjects": ubx.FieldSpec{
			WireName: "parameter_objects",
			Kind: "list",
			Fields: PipelinePipeline_ParameterObjectsFields,
		},
		"ParameterValues": ubx.FieldSpec{
			WireName: "parameter_values",
			Kind: "list",
			Fields: PipelinePipeline_ParameterValuesFields,
		},
		"PipelineObjects": ubx.FieldSpec{
			WireName: "pipeline_objects",
			Kind: "list",
			Fields: PipelinePipeline_PipelineObjectsFields,
		},
		"PipelineTags": ubx.FieldSpec{
			WireName: "pipeline_tags",
			Kind: "list",
			Fields: PipelinePipeline_PipelineTagsFields,
		},
	},
}
