// Code generated by `ubx sdk gen` from aws_control_tower_enabled_baseline. DO NOT EDIT.
package controltower

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type EnabledBaseline_Parameters struct {
	// The key (name) of a baseline parameter, used to identify a specific configuration parameter defined for the selected baseline in AWS Control Tower. (AI-inferred)
	Key any
	// The value of a key-value pair supplied as a configuration parameter to the AWS Control Tower baseline being enabled on an account. (AI-inferred)
	Value any
}

type EnabledBaseline_Tags struct {
	// The key of a tag assigned to the AWS Control Tower enabled baseline, used to categorize and identify the resource. (AI-inferred)
	Key any
	Value any
}

var EnabledBaseline_ParametersFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

var EnabledBaseline_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type EnabledBaselineConfig struct {
	// The ARN of the AWS Control Tower baseline to enable for the specified account. (AI-inferred)
	BaselineIdentifier any
	// The version of the baseline to enable, used to specify a particular released version of the baseline identified by BaselineIdentifier. (AI-inferred)
	BaselineVersion any
	// A list of parameter key-value pairs that customize the configuration of the enabled baseline when it is applied to an account. (AI-inferred)
	Parameters any
	// Specifies a list of key-value tags to associate with the AWS Control Tower enabled baseline resource, enabling metadata, cost allocation, and access control. (AI-inferred)
	Tags any
	// Specifies the ARN of the target AWS account or organizational unit to which the baseline is applied, such as an account ARN or OU ARN. (AI-inferred)
	TargetIdentifier any
}

type EnabledBaselineAttrs struct {
	// The ARN of the AWS Control Tower baseline to enable for the specified account. (AI-inferred)
	BaselineIdentifier any
	// The version of the baseline to enable, used to specify a particular released version of the baseline identified by BaselineIdentifier. (AI-inferred)
	BaselineVersion any
	// The unique identifier (Amazon Resource Name) of the enabled baseline, assigned by AWS Control Tower when the baseline is enabled on the target account or organizational unit. (AI-inferred)
	EnabledBaselineIdentifier any
	// A list of parameter key-value pairs that customize the configuration of the enabled baseline when it is applied to an account. (AI-inferred)
	Parameters any
	// Specifies a list of key-value tags to associate with the AWS Control Tower enabled baseline resource, enabling metadata, cost allocation, and access control. (AI-inferred)
	Tags any
	// Specifies the ARN of the target AWS account or organizational unit to which the baseline is applied, such as an account ARN or OU ARN. (AI-inferred)
	TargetIdentifier any
}

var EnabledBaseline = ubx.ResourceBinding{
	WireType: "aws_control_tower_enabled_baseline",
	Fields: ubx.FieldMap{
		"BaselineIdentifier": ubx.FieldSpec{WireName: "baseline_identifier"},
		"BaselineVersion": ubx.FieldSpec{WireName: "baseline_version"},
		"Parameters": ubx.FieldSpec{
			WireName: "parameters",
			Kind: "list",
			Fields: EnabledBaseline_ParametersFields,
		},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: EnabledBaseline_TagsFields,
		},
		"TargetIdentifier": ubx.FieldSpec{WireName: "target_identifier"},
	},
}
