// Code generated by `ubx sdk gen` from aws_autoscaling_notification. DO NOT EDIT.
package autoscaling

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type NotificationConfig struct {
	GroupNames any
	Id any
	Notifications any
	Region any
	TopicArn any
}

var Notification = ubx.ResourceBinding{
	WireType: "aws_autoscaling_notification",
	Fields: ubx.FieldMap{
		"GroupNames": ubx.FieldSpec{WireName: "group_names"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Notifications": ubx.FieldSpec{WireName: "notifications"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"TopicArn": ubx.FieldSpec{WireName: "topic_arn"},
	},
}
