// Code generated by `ubx sdk gen` from aws_iam_group_policy. DO NOT EDIT.
package iam

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GroupPolicyConfig struct {
	GroupName any
	PolicyName any
}

type GroupPolicyAttrs struct {
	GroupName any
	PolicyDocument any
	PolicyName any
}

var GroupPolicy = ubx.DataSourceBinding{
	WireType: "aws_iam_group_policy",
	Fields: ubx.FieldMap{
		"GroupName": ubx.FieldSpec{WireName: "group_name"},
		"PolicyName": ubx.FieldSpec{WireName: "policy_name"},
	},
}
