// Code generated by `ubx sdk gen` from aws_iam_role_tags. DO NOT EDIT.
package iam

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RoleTags_Tags struct {
	Key any
	Value any
}

type RoleTagsConfig struct {
	Marker any
	MaxItems any
	RoleName any
}

type RoleTagsAttrs struct {
	IsTruncated any
	Marker any
	MaxItems any
	RoleName any
	Tags any
}

var RoleTags = ubx.DataSourceBinding{
	WireType: "aws_iam_role_tags",
	Fields: ubx.FieldMap{
		"Marker": ubx.FieldSpec{WireName: "marker"},
		"MaxItems": ubx.FieldSpec{WireName: "max_items"},
		"RoleName": ubx.FieldSpec{WireName: "role_name"},
	},
}
