// Code generated by `ubx sdk gen` from aws_iot_index. DO NOT EDIT.
package iot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IndexConfig struct {
	IndexName any
}

type IndexAttrs struct {
	IndexName any
	IndexStatus any
	Schema any
}

var Index = ubx.DataSourceBinding{
	WireType: "aws_iot_index",
	Fields: ubx.FieldMap{
		"IndexName": ubx.FieldSpec{WireName: "index_name"},
	},
}
