// Code generated by `ubx sdk gen` from aws_fraud_detector_outcome. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Outcome_Tags {
  /** The key of a tag assigned to the AWS Fraud Detector outcome, used to organize and identify the outcome resource. (AI-inferred) */
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const Outcome_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface OutcomeConfig {
  /** The outcome description. */
  description?: string | Computed<string>;
  /** The name of the outcome. */
  name: string | Computed<string>;
  /** Tags associated with this outcome. */
  tags?: Outcome_Tags[] | Computed<Outcome_Tags[]>;
}

export interface OutcomeAttrs {
  /** The outcome ARN. */
  arn: string;
  /** The timestamp when the outcome was created. */
  createdTime: string;
  /** The outcome description. */
  description: string;
  /** The timestamp when the outcome was last updated. */
  lastUpdatedTime: string;
  /** The name of the outcome. */
  name: string;
  /** Tags associated with this outcome. */
  tags: Outcome_Tags[];
}

export const Outcome: ResourceBinding<OutcomeConfig, OutcomeAttrs> = {
  wireType: "aws_fraud_detector_outcome",
  fields: {
    description: "description",
    name: "name",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: Outcome_TagsFields,
    },
  },
};
