// Code generated by `ubx sdk gen` from aws_account_alternate_contact. DO NOT EDIT.
package account

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AlternateContact_Timeouts struct {
	Create any
	Delete any
	Update any
}

var AlternateContact_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type AlternateContactConfig struct {
	AccountId any
	AlternateContactType any
	EmailAddress any
	Id any
	Name any
	PhoneNumber any
	Title any
	Timeouts any
}

var AlternateContact = ubx.ResourceBinding{
	WireType: "aws_account_alternate_contact",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"AlternateContactType": ubx.FieldSpec{WireName: "alternate_contact_type"},
		"EmailAddress": ubx.FieldSpec{WireName: "email_address"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"PhoneNumber": ubx.FieldSpec{WireName: "phone_number"},
		"Title": ubx.FieldSpec{WireName: "title"},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AlternateContact_TimeoutsFields,
		},
	},
}
