// Code generated by `ubx sdk gen` from aws_autoscaling_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_Dimensions {
  name: string;
  value: string;
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric {
  metricName: string;
  namespace: string;
  dimensions: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_Dimensions[];
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat {
  stat: string;
  unit: string;
  metric: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric[];
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries {
  expression: string;
  id: string;
  label: string;
  returnData: boolean;
  metricStat: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat[];
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification {
  metricDataQueries: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries[];
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecification {
  predefinedMetricType: string;
  resourceLabel: string;
}

export interface Policy_PredictiveScalingConfiguration_MetricSpecification {
  targetValue: number;
  customizedCapacityMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification[];
  customizedLoadMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification[];
  customizedScalingMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification[];
  predefinedLoadMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecification[];
  predefinedMetricPairSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecification[];
  predefinedScalingMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecification[];
}

export interface Policy_PredictiveScalingConfiguration {
  maxCapacityBreachBehavior: string;
  maxCapacityBuffer: string;
  mode: string;
  schedulingBufferTime: string;
  metricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification[];
}

export interface Policy_StepAdjustment {
  metricIntervalLowerBound: string;
  metricIntervalUpperBound: string;
  scalingAdjustment: number;
}

export interface Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics_MetricStat {
  period: number;
  stat: string;
  unit: string;
  metric: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric[];
}

export interface Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics {
  expression: string;
  id: string;
  label: string;
  returnData: boolean;
  metricStat: Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics_MetricStat[];
}

export interface Policy_TargetTrackingConfiguration_CustomizedMetricSpecification {
  metricName: string;
  namespace: string;
  period: number;
  statistic: string;
  unit: string;
  metricDimension: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_Dimensions[];
  metrics: Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics[];
}

export interface Policy_TargetTrackingConfiguration {
  disableScaleIn: boolean;
  targetValue: number;
  customizedMetricSpecification: Policy_TargetTrackingConfiguration_CustomizedMetricSpecification[];
  predefinedMetricSpecification: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecification[];
}

const Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_DimensionsFields: FieldMap = {
  name: "name",
  value: "value",
};

const Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_MetricFields: FieldMap = {
  metricName: "metric_name",
  namespace: "namespace",
  dimensions: {
    wireName: "dimensions",
    kind: "set",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_DimensionsFields,
  },
};

const Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStatFields: FieldMap = {
  stat: "stat",
  unit: "unit",
  metric: {
    wireName: "metric",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_MetricFields,
  },
};

const Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueriesFields: FieldMap = {
  expression: "expression",
  id: "id",
  label: "label",
  returnData: "return_data",
  metricStat: {
    wireName: "metric_stat",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStatFields,
  },
};

const Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecificationFields: FieldMap = {
  metricDataQueries: {
    wireName: "metric_data_queries",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueriesFields,
  },
};

const Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecificationFields: FieldMap = {
  predefinedMetricType: "predefined_metric_type",
  resourceLabel: "resource_label",
};

const Policy_PredictiveScalingConfiguration_MetricSpecificationFields: FieldMap = {
  targetValue: "target_value",
  customizedCapacityMetricSpecification: {
    wireName: "customized_capacity_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecificationFields,
  },
  customizedLoadMetricSpecification: {
    wireName: "customized_load_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecificationFields,
  },
  customizedScalingMetricSpecification: {
    wireName: "customized_scaling_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecificationFields,
  },
  predefinedLoadMetricSpecification: {
    wireName: "predefined_load_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecificationFields,
  },
  predefinedMetricPairSpecification: {
    wireName: "predefined_metric_pair_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecificationFields,
  },
  predefinedScalingMetricSpecification: {
    wireName: "predefined_scaling_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecificationFields,
  },
};

const Policy_PredictiveScalingConfigurationFields: FieldMap = {
  maxCapacityBreachBehavior: "max_capacity_breach_behavior",
  maxCapacityBuffer: "max_capacity_buffer",
  mode: "mode",
  schedulingBufferTime: "scheduling_buffer_time",
  metricSpecification: {
    wireName: "metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecificationFields,
  },
};

const Policy_StepAdjustmentFields: FieldMap = {
  metricIntervalLowerBound: "metric_interval_lower_bound",
  metricIntervalUpperBound: "metric_interval_upper_bound",
  scalingAdjustment: "scaling_adjustment",
};

const Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics_MetricStatFields: FieldMap = {
  period: "period",
  stat: "stat",
  unit: "unit",
  metric: {
    wireName: "metric",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_MetricFields,
  },
};

const Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_MetricsFields: FieldMap = {
  expression: "expression",
  id: "id",
  label: "label",
  returnData: "return_data",
  metricStat: {
    wireName: "metric_stat",
    kind: "list",
    fields: Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_Metrics_MetricStatFields,
  },
};

const Policy_TargetTrackingConfiguration_CustomizedMetricSpecificationFields: FieldMap = {
  metricName: "metric_name",
  namespace: "namespace",
  period: "period",
  statistic: "statistic",
  unit: "unit",
  metricDimension: {
    wireName: "metric_dimension",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_CustomizedCapacityMetricSpecification_MetricDataQueries_MetricStat_Metric_DimensionsFields,
  },
  metrics: {
    wireName: "metrics",
    kind: "set",
    fields: Policy_TargetTrackingConfiguration_CustomizedMetricSpecification_MetricsFields,
  },
};

const Policy_TargetTrackingConfigurationFields: FieldMap = {
  disableScaleIn: "disable_scale_in",
  targetValue: "target_value",
  customizedMetricSpecification: {
    wireName: "customized_metric_specification",
    kind: "list",
    fields: Policy_TargetTrackingConfiguration_CustomizedMetricSpecificationFields,
  },
  predefinedMetricSpecification: {
    wireName: "predefined_metric_specification",
    kind: "list",
    fields: Policy_PredictiveScalingConfiguration_MetricSpecification_PredefinedLoadMetricSpecificationFields,
  },
};

export interface PolicyConfig {
  adjustmentType?: string | Computed<string>;
  autoscalingGroupName: string | Computed<string>;
  cooldown?: number | Computed<number>;
  enabled?: boolean | Computed<boolean>;
  estimatedInstanceWarmup?: number | Computed<number>;
  id?: string | Computed<string>;
  metricAggregationType?: string | Computed<string>;
  minAdjustmentMagnitude?: number | Computed<number>;
  name: string | Computed<string>;
  policyType?: string | Computed<string>;
  region?: string | Computed<string>;
  scalingAdjustment?: number | Computed<number>;
  predictiveScalingConfiguration?: Policy_PredictiveScalingConfiguration[] | Computed<Policy_PredictiveScalingConfiguration[]>;
  stepAdjustment?: Policy_StepAdjustment[] | Computed<Policy_StepAdjustment[]>;
  targetTrackingConfiguration?: Policy_TargetTrackingConfiguration[] | Computed<Policy_TargetTrackingConfiguration[]>;
}

export interface PolicyAttrs {
  adjustmentType: string;
  arn: string;
  autoscalingGroupName: string;
  cooldown: number;
  enabled: boolean;
  estimatedInstanceWarmup: number;
  id: string;
  metricAggregationType: string;
  minAdjustmentMagnitude: number;
  name: string;
  policyType: string;
  region: string;
  scalingAdjustment: number;
  predictiveScalingConfiguration: Policy_PredictiveScalingConfiguration[];
  stepAdjustment: Policy_StepAdjustment[];
  targetTrackingConfiguration: Policy_TargetTrackingConfiguration[];
}

export const Policy: ResourceBinding<PolicyConfig, PolicyAttrs> = {
  wireType: "aws_autoscaling_policy",
  fields: {
    adjustmentType: "adjustment_type",
    autoscalingGroupName: "autoscaling_group_name",
    cooldown: "cooldown",
    enabled: "enabled",
    estimatedInstanceWarmup: "estimated_instance_warmup",
    id: "id",
    metricAggregationType: "metric_aggregation_type",
    minAdjustmentMagnitude: "min_adjustment_magnitude",
    name: "name",
    policyType: "policy_type",
    region: "region",
    scalingAdjustment: "scaling_adjustment",
    predictiveScalingConfiguration: {
      wireName: "predictive_scaling_configuration",
      kind: "list",
      fields: Policy_PredictiveScalingConfigurationFields,
    },
    stepAdjustment: {
      wireName: "step_adjustment",
      kind: "set",
      fields: Policy_StepAdjustmentFields,
    },
    targetTrackingConfiguration: {
      wireName: "target_tracking_configuration",
      kind: "list",
      fields: Policy_TargetTrackingConfigurationFields,
    },
  },
};
