# Code generated by `ubx sdk gen` from aws_cloud_front_continuous_deployment_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleHeaderPolicyConfig:
    header: Any = None
    value: Any = None

@dataclasses.dataclass
class FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfig_SessionStickinessConfig:
    # The amount of time after which you want sessions to cease if no requests are received. Allowed values are 300–3600 seconds (5–60 minutes).
    idle_ttl: Any = None
    # The maximum amount of time to consider requests from the viewer as being part of the same session. Allowed values are 300–3600 seconds (5–60 minutes).
    maximum_ttl: Any = None

@dataclasses.dataclass
class FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfig:
    # Session stickiness provides the ability to define multiple requests from a single viewer as a single session. This prevents the potentially inconsistent experience of sending some of a given user's requests to your staging distribution, while others are sent to your primary distribution. Define the session duration using TTL values.
    session_stickiness_config: Any = None
    weight: Any = None

@dataclasses.dataclass
class FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_TrafficConfig:
    # Determines which HTTP requests are sent to the staging distribution.
    single_header_config: Any = None
    # This configuration determines the percentage of HTTP requests that are sent to the staging distribution.
    single_weight_config: Any = None
    # The type of traffic configuration.
    type: Any = None

@dataclasses.dataclass
class FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig:
    # A Boolean that indicates whether this continuous deployment policy is enabled (in effect). When this value is ``true``, this policy is enabled and in effect. When this value is ``false``, this policy is not enabled and has no effect.
    enabled: Any = None
    # This configuration determines which HTTP requests are sent to the staging distribution. If the HTTP request contains a header and value that matches what you specify here, the request is sent to the staging distribution. Otherwise the request is sent to the primary distribution.
    single_header_policy_config: Any = None
    # This configuration determines the percentage of HTTP requests that are sent to the staging distribution.
    single_weight_policy_config: Any = None
    # The CloudFront domain name of the staging distribution. For example: ``d111111abcdef8.cloudfront.net``.
    staging_distribution_dns_names: Any = None
    # The traffic configuration of your continuous deployment.
    traffic_config: Any = None
    # The type of traffic configuration.
    type: Any = None

_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleHeaderPolicyConfigFields = {
    "header": ubx.FieldSpec(wire_name="header"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfig_SessionStickinessConfigFields = {
    "idle_ttl": ubx.FieldSpec(wire_name="idle_ttl"),
    "maximum_ttl": ubx.FieldSpec(wire_name="maximum_ttl"),
}

_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfigFields = {
    "session_stickiness_config": ubx.FieldSpec(
        wire_name="session_stickiness_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfig_SessionStickinessConfigFields,
    ),
    "weight": ubx.FieldSpec(wire_name="weight"),
}

_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_TrafficConfigFields = {
    "single_header_config": ubx.FieldSpec(
        wire_name="single_header_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleHeaderPolicyConfigFields,
    ),
    "single_weight_config": ubx.FieldSpec(
        wire_name="single_weight_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfigFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
}

_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfigFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "single_header_policy_config": ubx.FieldSpec(
        wire_name="single_header_policy_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleHeaderPolicyConfigFields,
    ),
    "single_weight_policy_config": ubx.FieldSpec(
        wire_name="single_weight_policy_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_SingleWeightPolicyConfigFields,
    ),
    "staging_distribution_dns_names": ubx.FieldSpec(wire_name="staging_distribution_dns_names"),
    "traffic_config": ubx.FieldSpec(
        wire_name="traffic_config",
        kind="object",
        fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfig_TrafficConfigFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class FrontContinuousDeploymentPolicyConfig:
    # Contains the configuration for a continuous deployment policy.
    continuous_deployment_policy_config: Any = None

@dataclasses.dataclass
class FrontContinuousDeploymentPolicyAttrs:
    # Contains the configuration for a continuous deployment policy.
    continuous_deployment_policy_config: Any = None
    id: Any = None
    last_modified_time: Any = None

FrontContinuousDeploymentPolicy = ubx.ResourceBinding(
    wire_type="aws_cloud_front_continuous_deployment_policy",
    fields={
        "continuous_deployment_policy_config": ubx.FieldSpec(
            wire_name="continuous_deployment_policy_config",
            kind="object",
            fields=_FrontContinuousDeploymentPolicy_ContinuousDeploymentPolicyConfigFields,
        ),
    },
)
