# Code generated by `ubx sdk gen` from aws_cloud_trail_dashboard. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TrailDashboard_RefreshSchedule_Frequency:
    # The frequency unit. Supported values are HOURS and DAYS.
    unit: Any = None
    # The frequency value.
    value: Any = None

@dataclasses.dataclass
class TrailDashboard_RefreshSchedule:
    frequency: Any = None
    # The status of the schedule. Supported values are ENABLED and DISABLED.
    status: Any = None
    # StartTime of the automatic schedule refresh.
    time_of_day: Any = None

@dataclasses.dataclass
class TrailDashboard_Tags:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class TrailDashboard_Widgets:
    query_parameters: Any = None
    query_statement: Any = None
    view_properties: Any = None

_TrailDashboard_RefreshSchedule_FrequencyFields = {
    "unit": ubx.FieldSpec(wire_name="unit"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_TrailDashboard_RefreshScheduleFields = {
    "frequency": ubx.FieldSpec(
        wire_name="frequency",
        kind="object",
        fields=_TrailDashboard_RefreshSchedule_FrequencyFields,
    ),
    "status": ubx.FieldSpec(wire_name="status"),
    "time_of_day": ubx.FieldSpec(wire_name="time_of_day"),
}

_TrailDashboard_TagsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_TrailDashboard_WidgetsFields = {
    "query_parameters": ubx.FieldSpec(wire_name="query_parameters"),
    "query_statement": ubx.FieldSpec(wire_name="query_statement"),
    "view_properties": ubx.FieldSpec(wire_name="view_properties"),
}

@dataclasses.dataclass
class TrailDashboardConfig:
    # The name of the dashboard.
    name: Any = None
    # Configures the automatic refresh schedule for the dashboard. Includes the frequency unit (DAYS or HOURS) and value, as well as the status (ENABLED or DISABLED) of the refresh schedule.
    refresh_schedule: Any = None
    tags: Any = None
    # Indicates whether the dashboard is protected from termination.
    termination_protection_enabled: Any = None
    # List of widgets on the dashboard
    widgets: Any = None

@dataclasses.dataclass
class TrailDashboardAttrs:
    created_timestamp: Any = None
    # The ARN of the dashboard.
    dashboard_arn: Any = None
    # The name of the dashboard.
    name: Any = None
    # Configures the automatic refresh schedule for the dashboard. Includes the frequency unit (DAYS or HOURS) and value, as well as the status (ENABLED or DISABLED) of the refresh schedule.
    refresh_schedule: Any = None
    # The status of the dashboard. Values are CREATING, CREATED, UPDATING, UPDATED and DELETING.
    status: Any = None
    tags: Any = None
    # Indicates whether the dashboard is protected from termination.
    termination_protection_enabled: Any = None
    # The type of the dashboard. Values are CUSTOM and MANAGED.
    type: Any = None
    updated_timestamp: Any = None
    # List of widgets on the dashboard
    widgets: Any = None

TrailDashboard = ubx.ResourceBinding(
    wire_type="aws_cloud_trail_dashboard",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "refresh_schedule": ubx.FieldSpec(
            wire_name="refresh_schedule",
            kind="object",
            fields=_TrailDashboard_RefreshScheduleFields,
        ),
        "tags": ubx.FieldSpec(
            wire_name="tags",
            kind="list",
            fields=_TrailDashboard_TagsFields,
        ),
        "termination_protection_enabled": ubx.FieldSpec(wire_name="termination_protection_enabled"),
        "widgets": ubx.FieldSpec(
            wire_name="widgets",
            kind="list",
            fields=_TrailDashboard_WidgetsFields,
        ),
    },
)
