// Code generated by `ubx sdk gen` from aws_ram_permission. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Permission_Timeouts {
  delete: string;
}

const Permission_TimeoutsFields: FieldMap = {
  delete: "delete",
};

export interface PermissionConfig {
  name: string | Computed<string>;
  policyTemplate: string | Computed<string>;
  region?: string | Computed<string>;
  resourceType: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: Permission_Timeouts | Computed<Permission_Timeouts>;
}

export interface PermissionAttrs {
  arn: string;
  defaultVersion: boolean;
  name: string;
  policyTemplate: string;
  region: string;
  resourceType: string;
  status: string;
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  version: string;
  timeouts: Permission_Timeouts;
}

export const Permission: ResourceBinding<PermissionConfig, PermissionAttrs> = {
  wireType: "aws_ram_permission",
  fields: {
    name: "name",
    policyTemplate: "policy_template",
    region: "region",
    resourceType: "resource_type",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Permission_TimeoutsFields,
    },
  },
};
