# Code generated by `ubx sdk gen` from aws_evs_account_settings. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AccountSettings_Settings:
    name: Any = None
    value: Any = None

@dataclasses.dataclass
class AccountSettingsConfig:
    pass

@dataclasses.dataclass
class AccountSettingsAttrs:
    # <p>A list of regional account-level EVS settings.</p>
    settings: Any = None

AccountSettings = ubx.DataSourceBinding(
    wire_type="aws_evs_account_settings",
    fields={
    },
)
