# Code generated by `ubx sdk gen` from aws_sagemaker_project. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Project_ServiceCatalogProvisioningDetails_ProvisioningParameter:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class Project_ServiceCatalogProvisioningDetails:
    path_id: Any = None
    product_id: Any = None
    provisioning_artifact_id: Any = None
    provisioning_parameter: Any = None

_Project_ServiceCatalogProvisioningDetails_ProvisioningParameterFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_Project_ServiceCatalogProvisioningDetailsFields = {
    "path_id": ubx.FieldSpec(wire_name="path_id"),
    "product_id": ubx.FieldSpec(wire_name="product_id"),
    "provisioning_artifact_id": ubx.FieldSpec(wire_name="provisioning_artifact_id"),
    "provisioning_parameter": ubx.FieldSpec(
        wire_name="provisioning_parameter",
        kind="list",
        fields=_Project_ServiceCatalogProvisioningDetails_ProvisioningParameterFields,
    ),
}

@dataclasses.dataclass
class ProjectConfig:
    id: Any = None
    project_description: Any = None
    project_name: Any = None
    region: Any = None
    tags: Any = None
    tags_all: Any = None
    service_catalog_provisioning_details: Any = None

Project = ubx.ResourceBinding(
    wire_type="aws_sagemaker_project",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "project_description": ubx.FieldSpec(wire_name="project_description"),
        "project_name": ubx.FieldSpec(wire_name="project_name"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "service_catalog_provisioning_details": ubx.FieldSpec(
            wire_name="service_catalog_provisioning_details",
            kind="list",
            fields=_Project_ServiceCatalogProvisioningDetailsFields,
        ),
    },
)
