// Code generated by `ubx sdk gen` from aws_codecommit_merge_commit. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface MergeCommitConfig {
  conflictDetailLevel?: string | Computed<string>;
  conflictResolutionStrategy?: string | Computed<string>;
  destinationCommitSpecifier: string | Computed<string>;
  repositoryName: string | Computed<string>;
  sourceCommitSpecifier: string | Computed<string>;
}

export interface MergeCommitAttrs {
  baseCommitId: string;
  conflictDetailLevel: string;
  conflictResolutionStrategy: string;
  destinationCommitId: string;
  destinationCommitSpecifier: string;
  mergedCommitId: string;
  repositoryName: string;
  sourceCommitId: string;
  sourceCommitSpecifier: string;
}

export const MergeCommit: DataSourceBinding<MergeCommitConfig, MergeCommitAttrs> = {
  wireType: "aws_codecommit_merge_commit",
  fields: {
    conflictDetailLevel: "conflict_detail_level",
    conflictResolutionStrategy: "conflict_resolution_strategy",
    destinationCommitSpecifier: "destination_commit_specifier",
    repositoryName: "repository_name",
    sourceCommitSpecifier: "source_commit_specifier",
  },
};
