// Code generated by `ubx sdk gen` from aws_connect_agent_status. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AgentStatus_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const AgentStatus_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface AgentStatusConfig {
  /** The description of the status. */
  description?: string | Computed<string>;
  /** The display order of the status. */
  displayOrder?: number | Computed<number>;
  /** The identifier of the Amazon Connect instance. */
  instanceArn: string | Computed<string>;
  /** The name of the status. */
  name: string | Computed<string>;
  /** A number indicating the reset order of the agent status. */
  resetOrderNumber?: boolean | Computed<boolean>;
  /** The state of the status. */
  state: string | Computed<string>;
  /** An array of key-value pairs to apply to this resource. */
  tags?: AgentStatus_Tags[] | Computed<AgentStatus_Tags[]>;
  /** The type of agent status. */
  type?: string | Computed<string>;
}

export interface AgentStatusAttrs {
  /** The Amazon Resource Name (ARN) of the agent status. */
  agentStatusArn: string;
  /** The description of the status. */
  description: string;
  /** The display order of the status. */
  displayOrder: number;
  /** The identifier of the Amazon Connect instance. */
  instanceArn: string;
  /** Last modified region. */
  lastModifiedRegion: string;
  /** Last modified time. */
  lastModifiedTime: number;
  /** The name of the status. */
  name: string;
  /** A number indicating the reset order of the agent status. */
  resetOrderNumber: boolean;
  /** The state of the status. */
  state: string;
  /** An array of key-value pairs to apply to this resource. */
  tags: AgentStatus_Tags[];
  /** The type of agent status. */
  type: string;
}

export const AgentStatus: ResourceBinding<AgentStatusConfig, AgentStatusAttrs> = {
  wireType: "aws_connect_agent_status",
  fields: {
    description: "description",
    displayOrder: "display_order",
    instanceArn: "instance_arn",
    name: "name",
    resetOrderNumber: "reset_order_number",
    state: "state",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: AgentStatus_TagsFields,
    },
    type: "type",
  },
};
