// Code generated by `ubx sdk gen` from aws_connect_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Instance_Attributes {
  /** Boolean flag which enables AUTO_RESOLVE_BEST_VOICES on an instance. */
  autoResolveBestVoices?: boolean | Computed<boolean>;
  /** Boolean flag which enables CONTACT_LENS on an instance. */
  contactLens?: boolean | Computed<boolean>;
  /** Boolean flag which enables CONTACTFLOW_LOGS on an instance. */
  contactflowLogs?: boolean | Computed<boolean>;
  /** Boolean flag which enables EARLY_MEDIA on an instance. */
  earlyMedia?: boolean | Computed<boolean>;
  /** Boolean flag which enables ENHANCED_CHAT_MONITORING on an instance. */
  enhancedChatMonitoring?: boolean | Computed<boolean>;
  /** Boolean flag which enables ENHANCED_CONTACT_MONITORING on an instance. */
  enhancedContactMonitoring?: boolean | Computed<boolean>;
  /** Boolean flag which enables HIGH_VOLUME_OUTBOUND on an instance. */
  highVolumeOutBound?: boolean | Computed<boolean>;
  /** Mandatory element which enables inbound calls on new instance. */
  inboundCalls: boolean | Computed<boolean>;
  /** Boolean flag which enables MESSAGE_STREAMING on an instance. */
  messageStreaming?: boolean | Computed<boolean>;
  /** Boolean flag which enables MULTI_PARTY_CHAT_CONFERENCE on an instance. */
  multiPartyChatConference?: boolean | Computed<boolean>;
  /** Boolean flag which enables MULTI_PARTY_CONFERENCE on an instance. */
  multiPartyConference?: boolean | Computed<boolean>;
  /** Mandatory element which enables outbound calls on new instance. */
  outboundCalls: boolean | Computed<boolean>;
  /** Boolean flag which enables USE_CUSTOM_TTS_VOICES on an instance. */
  useCustomTtsvoices?: boolean | Computed<boolean>;
}

export interface Instance_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const Instance_AttributesFields: FieldMap = {
  autoResolveBestVoices: "auto_resolve_best_voices",
  contactLens: "contact_lens",
  contactflowLogs: "contactflow_logs",
  earlyMedia: "early_media",
  enhancedChatMonitoring: "enhanced_chat_monitoring",
  enhancedContactMonitoring: "enhanced_contact_monitoring",
  highVolumeOutBound: "high_volume_out_bound",
  inboundCalls: "inbound_calls",
  messageStreaming: "message_streaming",
  multiPartyChatConference: "multi_party_chat_conference",
  multiPartyConference: "multi_party_conference",
  outboundCalls: "outbound_calls",
  useCustomTtsvoices: "use_custom_ttsvoices",
};

const Instance_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface InstanceConfig {
  attributes: Instance_Attributes | Computed<Instance_Attributes>;
  /** Existing directoryId user wants to map to the new Connect instance. */
  directoryId?: string | Computed<string>;
  /** Specifies the type of directory integration for new instance. */
  identityManagementType: string | Computed<string>;
  /** Alias of the new directory created as part of new instance creation. */
  instanceAlias?: string | Computed<string>;
  /** An array of key-value pairs to apply to this resource. */
  tags?: Instance_Tags[] | Computed<Instance_Tags[]>;
}

export interface InstanceAttrs {
  /** An instanceArn is automatically generated on creation based on instanceId. */
  arn: string;
  attributes: Instance_Attributes;
  /** Timestamp of instance creation logged as part of instance creation. */
  createdTime: string;
  /** Existing directoryId user wants to map to the new Connect instance. */
  directoryId: string;
  /** An instanceId is automatically generated on creation and assigned as the unique identifier. */
  id: string;
  /** Specifies the type of directory integration for new instance. */
  identityManagementType: string;
  /** Alias of the new directory created as part of new instance creation. */
  instanceAlias: string;
  /** Specifies the creation status of new instance. */
  instanceStatus: string;
  /** Service linked role created as part of instance creation. */
  serviceRole: string;
  /** An array of key-value pairs to apply to this resource. */
  tags: Instance_Tags[];
}

export const Instance: ResourceBinding<InstanceConfig, InstanceAttrs> = {
  wireType: "aws_connect_instance",
  fields: {
    attributes: {
      wireName: "attributes",
      kind: "object",
      fields: Instance_AttributesFields,
    },
    directoryId: "directory_id",
    identityManagementType: "identity_management_type",
    instanceAlias: "instance_alias",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: Instance_TagsFields,
    },
  },
};
