// Code generated by `ubx sdk gen` from aws_codebuild_resource_policy. DO NOT EDIT.
package codebuild

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ResourcePolicyConfig struct {
	Id any
	Policy any
	Region any
	ResourceArn any
}

var ResourcePolicy = ubx.ResourceBinding{
	WireType: "aws_codebuild_resource_policy",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Policy": ubx.FieldSpec{WireName: "policy"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"ResourceArn": ubx.FieldSpec{WireName: "resource_arn"},
	},
}
