// Code generated by `ubx sdk gen` from aws_macie2_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccountConfig {
  findingPublishingFrequency?: string | Computed<string>;
  id?: string | Computed<string>;
  region?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface AccountAttrs {
  createdAt: string;
  findingPublishingFrequency: string;
  id: string;
  region: string;
  serviceRole: string;
  status: string;
  updatedAt: string;
}

export const Account: ResourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "aws_macie2_account",
  fields: {
    findingPublishingFrequency: "finding_publishing_frequency",
    id: "id",
    region: "region",
    status: "status",
  },
};
