// Code generated by `ubx sdk gen` from aws_cassandra_type. DO NOT EDIT.
package cassandra

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Type_Fields struct {
	FieldName any
	FieldType any
}

var Type_FieldsFields = ubx.FieldMap{
		"FieldName": ubx.FieldSpec{WireName: "field_name"},
		"FieldType": ubx.FieldSpec{WireName: "field_type"},
	}

type TypeConfig struct {
	// Field definitions of the User-Defined Type
	Fields any
	// Name of the Keyspace which contains the User-Defined Type.
	KeyspaceName any
	// Name of the User-Defined Type.
	TypeName any
}

type TypeAttrs struct {
	// List of parent User-Defined Types that directly reference the User-Defined Type in their fields.
	DirectParentTypes any
	// List of Tables that directly reference the User-Defined Type in their columns.
	DirectReferringTables any
	// Field definitions of the User-Defined Type
	Fields any
	// ARN of the Keyspace which contains the User-Defined Type.
	KeyspaceArn any
	// Name of the Keyspace which contains the User-Defined Type.
	KeyspaceName any
	// Timestamp of the last time the User-Defined Type's meta data was modified.
	LastModifiedTimestamp any
	// Maximum nesting depth of the User-Defined Type across the field types.
	MaxNestingDepth any
	// Name of the User-Defined Type.
	TypeName any
}

var Type = ubx.ResourceBinding{
	WireType: "aws_cassandra_type",
	Fields: ubx.FieldMap{
		"Fields": ubx.FieldSpec{
			WireName: "fields",
			Kind: "list",
			Fields: Type_FieldsFields,
		},
		"KeyspaceName": ubx.FieldSpec{WireName: "keyspace_name"},
		"TypeName": ubx.FieldSpec{WireName: "type_name"},
	},
}
