// Code generated by `ubx sdk gen` from aws_redshift_reserved_node_exchange_status. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ReservedNodeExchangeStatus_ReservedNodeExchangeStatusDetails {
  requestTime?: string | Computed<string>;
  reservedNodeExchangeRequestId?: string | Computed<string>;
  sourceReservedNodeCount?: number | Computed<number>;
  sourceReservedNodeId?: string | Computed<string>;
  sourceReservedNodeType?: string | Computed<string>;
  status?: string | Computed<string>;
  targetReservedNodeCount?: number | Computed<number>;
  targetReservedNodeOfferingId?: string | Computed<string>;
  targetReservedNodeType?: string | Computed<string>;
}

export interface ReservedNodeExchangeStatusConfig {
  marker?: string | Computed<string>;
  maxRecords?: number | Computed<number>;
  reservedNodeExchangeRequestId?: string | Computed<string>;
  reservedNodeId?: string | Computed<string>;
}

export interface ReservedNodeExchangeStatusAttrs {
  marker: string;
  maxRecords: number;
  reservedNodeExchangeRequestId: string;
  reservedNodeExchangeStatusDetails: ReservedNodeExchangeStatus_ReservedNodeExchangeStatusDetails[];
  reservedNodeId: string;
}

export const ReservedNodeExchangeStatus: DataSourceBinding<ReservedNodeExchangeStatusConfig, ReservedNodeExchangeStatusAttrs> = {
  wireType: "aws_redshift_reserved_node_exchange_status",
  fields: {
    marker: "marker",
    maxRecords: "max_records",
    reservedNodeExchangeRequestId: "reserved_node_exchange_request_id",
    reservedNodeId: "reserved_node_id",
  },
};
