// Code generated by `ubx sdk gen` from aws_code_commit_repository. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CommitRepository_Code_S3 {
  bucket: string | Computed<string>;
  key: string | Computed<string>;
  objectVersion?: string | Computed<string>;
}

export interface CommitRepository_Code {
  branchName?: string | Computed<string>;
  s3: CommitRepository_Code_S3 | Computed<CommitRepository_Code_S3>;
}

export interface CommitRepository_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface CommitRepository_Triggers {
  branches?: string[] | Computed<string[]>;
  customData?: string | Computed<string>;
  destinationArn?: string | Computed<string>;
  events?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
}

const CommitRepository_Code_S3Fields: FieldMap = {
  bucket: "bucket",
  key: "key",
  objectVersion: "object_version",
};

const CommitRepository_CodeFields: FieldMap = {
  branchName: "branch_name",
  s3: {
    wireName: "s3",
    kind: "object",
    fields: CommitRepository_Code_S3Fields,
  },
};

const CommitRepository_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

const CommitRepository_TriggersFields: FieldMap = {
  branches: "branches",
  customData: "custom_data",
  destinationArn: "destination_arn",
  events: "events",
  name: "name",
};

export interface CommitRepositoryConfig {
  code?: CommitRepository_Code | Computed<CommitRepository_Code>;
  kmsKeyId?: string | Computed<string>;
  repositoryDescription?: string | Computed<string>;
  repositoryName: string | Computed<string>;
  tags?: CommitRepository_Tags[] | Computed<CommitRepository_Tags[]>;
  triggers?: CommitRepository_Triggers[] | Computed<CommitRepository_Triggers[]>;
}

export interface CommitRepositoryAttrs {
  arn: string;
  cloneUrlHttp: string;
  cloneUrlSsh: string;
  code: CommitRepository_Code;
  id: string;
  kmsKeyId: string;
  name: string;
  repositoryDescription: string;
  repositoryName: string;
  tags: CommitRepository_Tags[];
  triggers: CommitRepository_Triggers[];
}

export const CommitRepository: ResourceBinding<CommitRepositoryConfig, CommitRepositoryAttrs> = {
  wireType: "aws_code_commit_repository",
  fields: {
    code: {
      wireName: "code",
      kind: "object",
      fields: CommitRepository_CodeFields,
    },
    kmsKeyId: "kms_key_id",
    repositoryDescription: "repository_description",
    repositoryName: "repository_name",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: CommitRepository_TagsFields,
    },
    triggers: {
      wireName: "triggers",
      kind: "list",
      fields: CommitRepository_TriggersFields,
    },
  },
};
