# Code generated by `ubx sdk gen` from aws_data_zone_user_profile. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ZoneUserProfile_Details_Iam:
    arn: Any = None
    group_profile_id: Any = None
    session_name: Any = None

@dataclasses.dataclass
class ZoneUserProfile_Details_Sso:
    first_name: Any = None
    last_name: Any = None
    username: Any = None

@dataclasses.dataclass
class ZoneUserProfile_Details:
    iam: Any = None
    sso: Any = None

@dataclasses.dataclass
class ZoneUserProfileConfig:
    # The identifier of the Amazon DataZone domain in which the user profile would be created.
    domain_identifier: Any = None
    # The session name of the user profile.
    session_name: Any = None
    # The status of the user profile.
    status: Any = None
    # The ID of the user.
    user_identifier: Any = None
    # The type of the user.
    user_type: Any = None

@dataclasses.dataclass
class ZoneUserProfileAttrs:
    details: Any = None
    # The identifier of the Amazon DataZone domain in which the user profile is created.
    domain_id: Any = None
    # The identifier of the Amazon DataZone domain in which the user profile would be created.
    domain_identifier: Any = None
    # The ID of the Amazon DataZone user profile.
    id: Any = None
    # The session name of the user profile.
    session_name: Any = None
    # The status of the user profile.
    status: Any = None
    # The type of the user profile.
    type: Any = None
    # The ID of the user.
    user_identifier: Any = None
    # The type of the user.
    user_type: Any = None

ZoneUserProfile = ubx.ResourceBinding(
    wire_type="aws_data_zone_user_profile",
    fields={
        "domain_identifier": ubx.FieldSpec(wire_name="domain_identifier"),
        "session_name": ubx.FieldSpec(wire_name="session_name"),
        "status": ubx.FieldSpec(wire_name="status"),
        "user_identifier": ubx.FieldSpec(wire_name="user_identifier"),
        "user_type": ubx.FieldSpec(wire_name="user_type"),
    },
)
