# Code generated by `ubx sdk gen` from aws_sagemaker_app. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class App_ResourceSpec:
    instance_type: Any = None
    lifecycle_config_arn: Any = None
    sagemaker_image_arn: Any = None
    sagemaker_image_version_alias: Any = None
    sagemaker_image_version_arn: Any = None

_App_ResourceSpecFields = {
    "instance_type": ubx.FieldSpec(wire_name="instance_type"),
    "lifecycle_config_arn": ubx.FieldSpec(wire_name="lifecycle_config_arn"),
    "sagemaker_image_arn": ubx.FieldSpec(wire_name="sagemaker_image_arn"),
    "sagemaker_image_version_alias": ubx.FieldSpec(wire_name="sagemaker_image_version_alias"),
    "sagemaker_image_version_arn": ubx.FieldSpec(wire_name="sagemaker_image_version_arn"),
}

@dataclasses.dataclass
class AppConfig:
    app_name: Any = None
    app_type: Any = None
    domain_id: Any = None
    id: Any = None
    region: Any = None
    space_name: Any = None
    tags: Any = None
    tags_all: Any = None
    user_profile_name: Any = None
    resource_spec: Any = None

App = ubx.ResourceBinding(
    wire_type="aws_sagemaker_app",
    fields={
        "app_name": ubx.FieldSpec(wire_name="app_name"),
        "app_type": ubx.FieldSpec(wire_name="app_type"),
        "domain_id": ubx.FieldSpec(wire_name="domain_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "region": ubx.FieldSpec(wire_name="region"),
        "space_name": ubx.FieldSpec(wire_name="space_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "user_profile_name": ubx.FieldSpec(wire_name="user_profile_name"),
        "resource_spec": ubx.FieldSpec(
            wire_name="resource_spec",
            kind="list",
            fields=_App_ResourceSpecFields,
        ),
    },
)
