# Code generated by `ubx sdk gen` from aws_networkmanager_link_association. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LinkAssociation_Timeouts:
    create: Any = None
    delete: Any = None

_LinkAssociation_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
}

@dataclasses.dataclass
class LinkAssociationConfig:
    device_id: Any = None
    global_network_id: Any = None
    id: Any = None
    link_id: Any = None
    timeouts: Any = None

LinkAssociation = ubx.ResourceBinding(
    wire_type="aws_networkmanager_link_association",
    fields={
        "device_id": ubx.FieldSpec(wire_name="device_id"),
        "global_network_id": ubx.FieldSpec(wire_name="global_network_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "link_id": ubx.FieldSpec(wire_name="link_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LinkAssociation_TimeoutsFields,
        ),
    },
)
