// Code generated by `ubx sdk gen` from aws_media_connect_router_output. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManager {
  roleArn?: string | Computed<string>;
  secretArn?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration {
  automatic?: unknown | Computed<unknown>;
  secretsManager?: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManager | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManager>;
}

export interface ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption {
  encryptionKeyConfiguration?: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration>;
  encryptionKeyType?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_MediaConnectFlow {
  destinationTransitEncryption?: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption>;
  flowArn?: string | Computed<string>;
  flowSourceArn?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_MediaLiveInput {
  destinationTransitEncryption?: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption>;
  mediaLiveInputArn?: string | Computed<string>;
  mediaLivePipelineId?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rist {
  destinationAddress?: string | Computed<string>;
  destinationPort?: number | Computed<number>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rtp {
  destinationAddress?: string | Computed<string>;
  destinationPort?: number | Computed<number>;
  forwardErrorCorrection?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfiguration {
  encryptionKey?: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManager | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManager>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller {
  destinationAddress?: string | Computed<string>;
  destinationPort?: number | Computed<number>;
  encryptionConfiguration?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfiguration | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfiguration>;
  minimumLatencyMilliseconds?: number | Computed<number>;
  streamId?: string | Computed<string>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtListener {
  encryptionConfiguration?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfiguration | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfiguration>;
  minimumLatencyMilliseconds?: number | Computed<number>;
  port?: number | Computed<number>;
}

export interface ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration {
  rist?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rist | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rist>;
  rtp?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rtp | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_Rtp>;
  srtCaller?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller>;
  srtListener?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtListener | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtListener>;
}

export interface ConnectRouterOutput_Configuration_Standard {
  networkInterfaceArn?: string | Computed<string>;
  protocol?: string | Computed<string>;
  protocolConfiguration?: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration | Computed<ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration>;
}

export interface ConnectRouterOutput_Configuration {
  mediaConnectFlow?: ConnectRouterOutput_Configuration_MediaConnectFlow | Computed<ConnectRouterOutput_Configuration_MediaConnectFlow>;
  mediaLiveInput?: ConnectRouterOutput_Configuration_MediaLiveInput | Computed<ConnectRouterOutput_Configuration_MediaLiveInput>;
  standard?: ConnectRouterOutput_Configuration_Standard | Computed<ConnectRouterOutput_Configuration_Standard>;
}

export interface ConnectRouterOutput_MaintenanceConfiguration_PreferredDayTime {
  day?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface ConnectRouterOutput_MaintenanceConfiguration {
  default?: unknown | Computed<unknown>;
  preferredDayTime?: ConnectRouterOutput_MaintenanceConfiguration_PreferredDayTime | Computed<ConnectRouterOutput_MaintenanceConfiguration_PreferredDayTime>;
}

export interface ConnectRouterOutput_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManagerFields: FieldMap = {
  roleArn: "role_arn",
  secretArn: "secret_arn",
};

const ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfigurationFields: FieldMap = {
  automatic: "automatic",
  secretsManager: {
    wireName: "secrets_manager",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManagerFields,
  },
};

const ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryptionFields: FieldMap = {
  encryptionKeyConfiguration: {
    wireName: "encryption_key_configuration",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfigurationFields,
  },
  encryptionKeyType: "encryption_key_type",
};

const ConnectRouterOutput_Configuration_MediaConnectFlowFields: FieldMap = {
  destinationTransitEncryption: {
    wireName: "destination_transit_encryption",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryptionFields,
  },
  flowArn: "flow_arn",
  flowSourceArn: "flow_source_arn",
};

const ConnectRouterOutput_Configuration_MediaLiveInputFields: FieldMap = {
  destinationTransitEncryption: {
    wireName: "destination_transit_encryption",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryptionFields,
  },
  mediaLiveInputArn: "media_live_input_arn",
  mediaLivePipelineId: "media_live_pipeline_id",
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_RistFields: FieldMap = {
  destinationAddress: "destination_address",
  destinationPort: "destination_port",
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_RtpFields: FieldMap = {
  destinationAddress: "destination_address",
  destinationPort: "destination_port",
  forwardErrorCorrection: "forward_error_correction",
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfigurationFields: FieldMap = {
  encryptionKey: {
    wireName: "encryption_key",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlow_DestinationTransitEncryption_EncryptionKeyConfiguration_SecretsManagerFields,
  },
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCallerFields: FieldMap = {
  destinationAddress: "destination_address",
  destinationPort: "destination_port",
  encryptionConfiguration: {
    wireName: "encryption_configuration",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfigurationFields,
  },
  minimumLatencyMilliseconds: "minimum_latency_milliseconds",
  streamId: "stream_id",
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtListenerFields: FieldMap = {
  encryptionConfiguration: {
    wireName: "encryption_configuration",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCaller_EncryptionConfigurationFields,
  },
  minimumLatencyMilliseconds: "minimum_latency_milliseconds",
  port: "port",
};

const ConnectRouterOutput_Configuration_Standard_ProtocolConfigurationFields: FieldMap = {
  rist: {
    wireName: "rist",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_RistFields,
  },
  rtp: {
    wireName: "rtp",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_RtpFields,
  },
  srtCaller: {
    wireName: "srt_caller",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtCallerFields,
  },
  srtListener: {
    wireName: "srt_listener",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfiguration_SrtListenerFields,
  },
};

const ConnectRouterOutput_Configuration_StandardFields: FieldMap = {
  networkInterfaceArn: "network_interface_arn",
  protocol: "protocol",
  protocolConfiguration: {
    wireName: "protocol_configuration",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_Standard_ProtocolConfigurationFields,
  },
};

const ConnectRouterOutput_ConfigurationFields: FieldMap = {
  mediaConnectFlow: {
    wireName: "media_connect_flow",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaConnectFlowFields,
  },
  mediaLiveInput: {
    wireName: "media_live_input",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_MediaLiveInputFields,
  },
  standard: {
    wireName: "standard",
    kind: "object",
    fields: ConnectRouterOutput_Configuration_StandardFields,
  },
};

const ConnectRouterOutput_MaintenanceConfiguration_PreferredDayTimeFields: FieldMap = {
  day: "day",
  time: "time",
};

const ConnectRouterOutput_MaintenanceConfigurationFields: FieldMap = {
  default: "default",
  preferredDayTime: {
    wireName: "preferred_day_time",
    kind: "object",
    fields: ConnectRouterOutput_MaintenanceConfiguration_PreferredDayTimeFields,
  },
};

const ConnectRouterOutput_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface ConnectRouterOutputConfig {
  /** The Availability Zone where you want to create the router output. This must be a valid Availability Zone for the region specified by regionName, or the current region if no regionName is provided. */
  availabilityZone?: string | Computed<string>;
  /** The configuration settings for a router output. */
  configuration: ConnectRouterOutput_Configuration | Computed<ConnectRouterOutput_Configuration>;
  /** The configuration settings for maintenance operations, including preferred maintenance windows and schedules. */
  maintenanceConfiguration?: ConnectRouterOutput_MaintenanceConfiguration | Computed<ConnectRouterOutput_MaintenanceConfiguration>;
  /** The maximum bitrate for the router output. */
  maximumBitrate: number | Computed<number>;
  /** The name of the router output. */
  name: string | Computed<string>;
  /** The Amazon Web Services Region for the router output. Defaults to the current region if not specified. */
  regionName?: string | Computed<string>;
  routingScope: string | Computed<string>;
  /** Key-value pairs that can be used to tag this router output. */
  tags?: ConnectRouterOutput_Tags[] | Computed<ConnectRouterOutput_Tags[]>;
  tier: string | Computed<string>;
}

export interface ConnectRouterOutputAttrs {
  arn: string;
  /** The Availability Zone where you want to create the router output. This must be a valid Availability Zone for the region specified by regionName, or the current region if no regionName is provided. */
  availabilityZone: string;
  /** The configuration settings for a router output. */
  configuration: ConnectRouterOutput_Configuration;
  /** The timestamp when the router output was created. */
  createdAt: string;
  /** The unique identifier of the router output. */
  id: string;
  /** The IP address of the router output. */
  ipAddress: string;
  /** The configuration settings for maintenance operations, including preferred maintenance windows and schedules. */
  maintenanceConfiguration: ConnectRouterOutput_MaintenanceConfiguration;
  maintenanceType: string;
  /** The maximum bitrate for the router output. */
  maximumBitrate: number;
  /** The name of the router output. */
  name: string;
  outputType: string;
  /** The Amazon Web Services Region for the router output. Defaults to the current region if not specified. */
  regionName: string;
  routedState: string;
  routingScope: string;
  state: string;
  /** Key-value pairs that can be used to tag this router output. */
  tags: ConnectRouterOutput_Tags[];
  tier: string;
  /** The timestamp when the router output was last updated. */
  updatedAt: string;
}

export const ConnectRouterOutput: ResourceBinding<ConnectRouterOutputConfig, ConnectRouterOutputAttrs> = {
  wireType: "aws_media_connect_router_output",
  fields: {
    availabilityZone: "availability_zone",
    configuration: {
      wireName: "configuration",
      kind: "object",
      fields: ConnectRouterOutput_ConfigurationFields,
    },
    maintenanceConfiguration: {
      wireName: "maintenance_configuration",
      kind: "object",
      fields: ConnectRouterOutput_MaintenanceConfigurationFields,
    },
    maximumBitrate: "maximum_bitrate",
    name: "name",
    regionName: "region_name",
    routingScope: "routing_scope",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: ConnectRouterOutput_TagsFields,
    },
    tier: "tier",
  },
};
