// Code generated by `ubx sdk gen` from aws_media_package_channel. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PackageChannel_EgressAccessLogs {
  /** Sets a custom AWS CloudWatch log group name for access logs. If a log group name isn't specified, the defaults are used: /aws/MediaPackage/EgressAccessLogs for egress access logs and /aws/MediaPackage/IngressAccessLogs for ingress access logs. */
  logGroupName?: string | Computed<string>;
}

export interface PackageChannel_HlsIngest_IngestEndpoints {
  /** The unique identifier assigned by AWS MediaPackage to this HLS ingest endpoint. (AI-inferred) */
  id?: string | Computed<string>;
  /** The password used to authenticate HTTP requests to the HLS ingest endpoint when pushing media content from an upstream encoder. (AI-inferred) */
  password?: string | Computed<string>;
  /** The URL of the HLS ingest endpoint that receives live content from an upstream encoder for the MediaPackage channel. (AI-inferred) */
  url?: string | Computed<string>;
  /** The username used to authenticate to the ingest endpoint when pushing content into the MediaPackage channel. (AI-inferred) */
  username?: string | Computed<string>;
}

export interface PackageChannel_HlsIngest {
  /** A list of endpoints to which the source stream should be sent. */
  ingestEndpoints?: PackageChannel_HlsIngest_IngestEndpoints[] | Computed<PackageChannel_HlsIngest_IngestEndpoints[]>;
}

export interface PackageChannel_Tags {
  /** The key of a tag attached to the AWS Elemental MediaPackage channel, enabling you to assign metadata such as environment or project for resource filtering and cost tracking. (AI-inferred) */
  key?: string | Computed<string>;
  /** The value portion of a tag key-value pair applied to an AWS Elemental MediaPackage channel, used for resource identification and management. (AI-inferred) */
  value?: string | Computed<string>;
}

const PackageChannel_EgressAccessLogsFields: FieldMap = {
  logGroupName: "log_group_name",
};

const PackageChannel_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface PackageChannelConfig {
  /** A short text description of the Channel. */
  description?: string | Computed<string>;
  /** This property specifies the CloudWatch Logs log group where egress access logs for the MediaPackage channel are delivered. (AI-inferred) */
  egressAccessLogs?: PackageChannel_EgressAccessLogs | Computed<PackageChannel_EgressAccessLogs>;
  /** The ID of the Channel. */
  id: string | Computed<string>;
  /** Specifies the CloudWatch Logs log group that captures access logs for incoming requests to the MediaPackage channel's ingress endpoints. (AI-inferred) */
  ingressAccessLogs?: PackageChannel_EgressAccessLogs | Computed<PackageChannel_EgressAccessLogs>;
  /** A collection of tags associated with a resource */
  tags?: PackageChannel_Tags[] | Computed<PackageChannel_Tags[]>;
}

export interface PackageChannelAttrs {
  /** The Amazon Resource Name (ARN) assigned to the Channel. */
  arn: string;
  /** A short text description of the Channel. */
  description: string;
  /** This property specifies the CloudWatch Logs log group where egress access logs for the MediaPackage channel are delivered. (AI-inferred) */
  egressAccessLogs: PackageChannel_EgressAccessLogs;
  /** An HTTP Live Streaming (HLS) ingest resource configuration. */
  hlsIngest: PackageChannel_HlsIngest;
  /** The ID of the Channel. */
  id: string;
  /** Specifies the CloudWatch Logs log group that captures access logs for incoming requests to the MediaPackage channel's ingress endpoints. (AI-inferred) */
  ingressAccessLogs: PackageChannel_EgressAccessLogs;
  /** A collection of tags associated with a resource */
  tags: PackageChannel_Tags[];
}

export const PackageChannel: ResourceBinding<PackageChannelConfig, PackageChannelAttrs> = {
  wireType: "aws_media_package_channel",
  fields: {
    description: "description",
    egressAccessLogs: {
      wireName: "egress_access_logs",
      kind: "object",
      fields: PackageChannel_EgressAccessLogsFields,
    },
    id: "id",
    ingressAccessLogs: {
      wireName: "ingress_access_logs",
      kind: "object",
      fields: PackageChannel_EgressAccessLogsFields,
    },
    tags: {
      wireName: "tags",
      kind: "list",
      fields: PackageChannel_TagsFields,
    },
  },
};
