# Code generated by `ubx sdk gen` from aws_lambda_event_source_mapping. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_AccessConfig:
    type: Any = None
    uri: Any = None

@dataclasses.dataclass
class EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_SchemaValidationConfig:
    attribute: Any = None

@dataclasses.dataclass
class EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig:
    event_record_format: Any = None
    schema_registry_uri: Any = None
    access_config: Any = None
    schema_validation_config: Any = None

@dataclasses.dataclass
class EventSourceMapping_AmazonManagedKafkaEventSourceConfig:
    consumer_group_id: Any = None
    schema_registry_config: Any = None

@dataclasses.dataclass
class EventSourceMapping_DestinationConfig_OnFailure:
    destination_arn: Any = None

@dataclasses.dataclass
class EventSourceMapping_DestinationConfig:
    on_failure: Any = None

@dataclasses.dataclass
class EventSourceMapping_DocumentDbEventSourceConfig:
    collection_name: Any = None
    database_name: Any = None
    full_document: Any = None

@dataclasses.dataclass
class EventSourceMapping_FilterCriteria_Filter:
    pattern: Any = None

@dataclasses.dataclass
class EventSourceMapping_FilterCriteria:
    filter: Any = None

@dataclasses.dataclass
class EventSourceMapping_MetricsConfig:
    metrics: Any = None

@dataclasses.dataclass
class EventSourceMapping_ProvisionedPollerConfig:
    maximum_pollers: Any = None
    minimum_pollers: Any = None
    poller_group_name: Any = None

@dataclasses.dataclass
class EventSourceMapping_ScalingConfig:
    maximum_concurrency: Any = None

@dataclasses.dataclass
class EventSourceMapping_SelfManagedEventSource:
    endpoints: Any = None

@dataclasses.dataclass
class EventSourceMapping_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_AccessConfigFields = {
    "type": ubx.FieldSpec(wire_name="type"),
    "uri": ubx.FieldSpec(wire_name="uri"),
}

_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_SchemaValidationConfigFields = {
    "attribute": ubx.FieldSpec(wire_name="attribute"),
}

_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfigFields = {
    "event_record_format": ubx.FieldSpec(wire_name="event_record_format"),
    "schema_registry_uri": ubx.FieldSpec(wire_name="schema_registry_uri"),
    "access_config": ubx.FieldSpec(
        wire_name="access_config",
        kind="set",
        fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_AccessConfigFields,
    ),
    "schema_validation_config": ubx.FieldSpec(
        wire_name="schema_validation_config",
        kind="set",
        fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_SchemaValidationConfigFields,
    ),
}

_EventSourceMapping_AmazonManagedKafkaEventSourceConfigFields = {
    "consumer_group_id": ubx.FieldSpec(wire_name="consumer_group_id"),
    "schema_registry_config": ubx.FieldSpec(
        wire_name="schema_registry_config",
        kind="list",
        fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfigFields,
    ),
}

_EventSourceMapping_DestinationConfig_OnFailureFields = {
    "destination_arn": ubx.FieldSpec(wire_name="destination_arn"),
}

_EventSourceMapping_DestinationConfigFields = {
    "on_failure": ubx.FieldSpec(
        wire_name="on_failure",
        kind="list",
        fields=_EventSourceMapping_DestinationConfig_OnFailureFields,
    ),
}

_EventSourceMapping_DocumentDbEventSourceConfigFields = {
    "collection_name": ubx.FieldSpec(wire_name="collection_name"),
    "database_name": ubx.FieldSpec(wire_name="database_name"),
    "full_document": ubx.FieldSpec(wire_name="full_document"),
}

_EventSourceMapping_FilterCriteria_FilterFields = {
    "pattern": ubx.FieldSpec(wire_name="pattern"),
}

_EventSourceMapping_FilterCriteriaFields = {
    "filter": ubx.FieldSpec(
        wire_name="filter",
        kind="set",
        fields=_EventSourceMapping_FilterCriteria_FilterFields,
    ),
}

_EventSourceMapping_MetricsConfigFields = {
    "metrics": ubx.FieldSpec(wire_name="metrics"),
}

_EventSourceMapping_ProvisionedPollerConfigFields = {
    "maximum_pollers": ubx.FieldSpec(wire_name="maximum_pollers"),
    "minimum_pollers": ubx.FieldSpec(wire_name="minimum_pollers"),
    "poller_group_name": ubx.FieldSpec(wire_name="poller_group_name"),
}

_EventSourceMapping_ScalingConfigFields = {
    "maximum_concurrency": ubx.FieldSpec(wire_name="maximum_concurrency"),
}

_EventSourceMapping_SelfManagedEventSourceFields = {
    "endpoints": ubx.FieldSpec(wire_name="endpoints"),
}

_EventSourceMapping_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class EventSourceMappingConfig:
    batch_size: Any = None
    bisect_batch_on_function_error: Any = None
    enabled: Any = None
    event_source_arn: Any = None
    function_name: Any = None
    function_response_types: Any = None
    id: Any = None
    kms_key_arn: Any = None
    maximum_batching_window_in_seconds: Any = None
    maximum_record_age_in_seconds: Any = None
    maximum_retry_attempts: Any = None
    parallelization_factor: Any = None
    queues: Any = None
    region: Any = None
    starting_position: Any = None
    starting_position_timestamp: Any = None
    tags: Any = None
    tags_all: Any = None
    topics: Any = None
    tumbling_window_in_seconds: Any = None
    use_resource_timeout_for_propagation: Any = None
    amazon_managed_kafka_event_source_config: Any = None
    destination_config: Any = None
    document_db_event_source_config: Any = None
    filter_criteria: Any = None
    metrics_config: Any = None
    provisioned_poller_config: Any = None
    scaling_config: Any = None
    self_managed_event_source: Any = None
    self_managed_kafka_event_source_config: Any = None
    source_access_configuration: Any = None
    timeouts: Any = None

EventSourceMapping = ubx.ResourceBinding(
    wire_type="aws_lambda_event_source_mapping",
    fields={
        "batch_size": ubx.FieldSpec(wire_name="batch_size"),
        "bisect_batch_on_function_error": ubx.FieldSpec(wire_name="bisect_batch_on_function_error"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "event_source_arn": ubx.FieldSpec(wire_name="event_source_arn"),
        "function_name": ubx.FieldSpec(wire_name="function_name"),
        "function_response_types": ubx.FieldSpec(wire_name="function_response_types"),
        "id": ubx.FieldSpec(wire_name="id"),
        "kms_key_arn": ubx.FieldSpec(wire_name="kms_key_arn"),
        "maximum_batching_window_in_seconds": ubx.FieldSpec(wire_name="maximum_batching_window_in_seconds"),
        "maximum_record_age_in_seconds": ubx.FieldSpec(wire_name="maximum_record_age_in_seconds"),
        "maximum_retry_attempts": ubx.FieldSpec(wire_name="maximum_retry_attempts"),
        "parallelization_factor": ubx.FieldSpec(wire_name="parallelization_factor"),
        "queues": ubx.FieldSpec(wire_name="queues"),
        "region": ubx.FieldSpec(wire_name="region"),
        "starting_position": ubx.FieldSpec(wire_name="starting_position"),
        "starting_position_timestamp": ubx.FieldSpec(wire_name="starting_position_timestamp"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "topics": ubx.FieldSpec(wire_name="topics"),
        "tumbling_window_in_seconds": ubx.FieldSpec(wire_name="tumbling_window_in_seconds"),
        "use_resource_timeout_for_propagation": ubx.FieldSpec(wire_name="use_resource_timeout_for_propagation"),
        "amazon_managed_kafka_event_source_config": ubx.FieldSpec(
            wire_name="amazon_managed_kafka_event_source_config",
            kind="list",
            fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfigFields,
        ),
        "destination_config": ubx.FieldSpec(
            wire_name="destination_config",
            kind="list",
            fields=_EventSourceMapping_DestinationConfigFields,
        ),
        "document_db_event_source_config": ubx.FieldSpec(
            wire_name="document_db_event_source_config",
            kind="list",
            fields=_EventSourceMapping_DocumentDbEventSourceConfigFields,
        ),
        "filter_criteria": ubx.FieldSpec(
            wire_name="filter_criteria",
            kind="list",
            fields=_EventSourceMapping_FilterCriteriaFields,
        ),
        "metrics_config": ubx.FieldSpec(
            wire_name="metrics_config",
            kind="list",
            fields=_EventSourceMapping_MetricsConfigFields,
        ),
        "provisioned_poller_config": ubx.FieldSpec(
            wire_name="provisioned_poller_config",
            kind="list",
            fields=_EventSourceMapping_ProvisionedPollerConfigFields,
        ),
        "scaling_config": ubx.FieldSpec(
            wire_name="scaling_config",
            kind="list",
            fields=_EventSourceMapping_ScalingConfigFields,
        ),
        "self_managed_event_source": ubx.FieldSpec(
            wire_name="self_managed_event_source",
            kind="list",
            fields=_EventSourceMapping_SelfManagedEventSourceFields,
        ),
        "self_managed_kafka_event_source_config": ubx.FieldSpec(
            wire_name="self_managed_kafka_event_source_config",
            kind="list",
            fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfigFields,
        ),
        "source_access_configuration": ubx.FieldSpec(
            wire_name="source_access_configuration",
            kind="set",
            fields=_EventSourceMapping_AmazonManagedKafkaEventSourceConfig_SchemaRegistryConfig_AccessConfigFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_EventSourceMapping_TimeoutsFields,
        ),
    },
)
