// Code generated by `ubx sdk gen` from aws_systems_manager_sap_application. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagerSapApplication_ComponentsInfo {
  componentType?: string | Computed<string>;
  ec2InstanceId?: string | Computed<string>;
  sid?: string | Computed<string>;
}

export interface ManagerSapApplication_Credentials {
  credentialType?: string | Computed<string>;
  databaseName?: string | Computed<string>;
  secretId?: string | Computed<string>;
}

export interface ManagerSapApplication_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const ManagerSapApplication_ComponentsInfoFields: FieldMap = {
  componentType: "component_type",
  ec2InstanceId: "ec2_instance_id",
  sid: "sid",
};

const ManagerSapApplication_CredentialsFields: FieldMap = {
  credentialType: "credential_type",
  databaseName: "database_name",
  secretId: "secret_id",
};

const ManagerSapApplication_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface ManagerSapApplicationConfig {
  applicationId: string | Computed<string>;
  applicationType: string | Computed<string>;
  /** This is an optional parameter for component details to which the SAP ABAP application is attached, such as Web Dispatcher. */
  componentsInfo?: ManagerSapApplication_ComponentsInfo[] | Computed<ManagerSapApplication_ComponentsInfo[]>;
  credentials?: ManagerSapApplication_Credentials[] | Computed<ManagerSapApplication_Credentials[]>;
  /** The ARN of the SAP HANA database */
  databaseArn?: string | Computed<string>;
  instances?: string[] | Computed<string[]>;
  sapInstanceNumber?: string | Computed<string>;
  sid?: string | Computed<string>;
  /** The tags of a SystemsManagerSAP application. */
  tags?: ManagerSapApplication_Tags[] | Computed<ManagerSapApplication_Tags[]>;
}

export interface ManagerSapApplicationAttrs {
  applicationId: string;
  applicationType: string;
  /** The ARN of the SSM-SAP application */
  arn: string;
  /** This is an optional parameter for component details to which the SAP ABAP application is attached, such as Web Dispatcher. */
  componentsInfo: ManagerSapApplication_ComponentsInfo[];
  credentials: ManagerSapApplication_Credentials[];
  /** The ARN of the SAP HANA database */
  databaseArn: string;
  instances: string[];
  sapInstanceNumber: string;
  sid: string;
  /** The tags of a SystemsManagerSAP application. */
  tags: ManagerSapApplication_Tags[];
}

export const ManagerSapApplication: ResourceBinding<ManagerSapApplicationConfig, ManagerSapApplicationAttrs> = {
  wireType: "aws_systems_manager_sap_application",
  fields: {
    applicationId: "application_id",
    applicationType: "application_type",
    componentsInfo: {
      wireName: "components_info",
      kind: "list",
      fields: ManagerSapApplication_ComponentsInfoFields,
    },
    credentials: {
      wireName: "credentials",
      kind: "list",
      fields: ManagerSapApplication_CredentialsFields,
    },
    databaseArn: "database_arn",
    instances: "instances",
    sapInstanceNumber: "sap_instance_number",
    sid: "sid",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: ManagerSapApplication_TagsFields,
    },
  },
};
