// Code generated by `ubx sdk gen` from aws_apprunner_observability_configurations. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ObservabilityConfigurations_ObservabilityConfigurationSummaryList {
  observabilityConfigurationArn?: string | Computed<string>;
  observabilityConfigurationName?: string | Computed<string>;
  observabilityConfigurationRevision?: number | Computed<number>;
}

export interface ObservabilityConfigurationsConfig {
  latestOnly?: boolean | Computed<boolean>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  observabilityConfigurationName?: string | Computed<string>;
}

export interface ObservabilityConfigurationsAttrs {
  latestOnly: boolean;
  maxResults: number;
  nextToken: string;
  observabilityConfigurationName: string;
  observabilityConfigurationSummaryList: ObservabilityConfigurations_ObservabilityConfigurationSummaryList[];
}

export const ObservabilityConfigurations: DataSourceBinding<ObservabilityConfigurationsConfig, ObservabilityConfigurationsAttrs> = {
  wireType: "aws_apprunner_observability_configurations",
  fields: {
    latestOnly: "latest_only",
    maxResults: "max_results",
    nextToken: "next_token",
    observabilityConfigurationName: "observability_configuration_name",
  },
};
