// Code generated by `ubx sdk gen` from aws_auditmanager_change_logs. DO NOT EDIT.
package auditmanager

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ChangeLogs_ChangeLogs struct {
	Action any
	CreatedAt any
	CreatedBy any
	ObjectName any
	ObjectType any
}

type ChangeLogsConfig struct {
	AssessmentId any
	ControlId any
	ControlSetId any
	// Max results in the page.
	MaxResults any
	NextToken any
}

type ChangeLogsAttrs struct {
	AssessmentId any
	ChangeLogs any
	ControlId any
	ControlSetId any
	// Max results in the page.
	MaxResults any
	NextToken any
}

var ChangeLogs = ubx.DataSourceBinding{
	WireType: "aws_auditmanager_change_logs",
	Fields: ubx.FieldMap{
		"AssessmentId": ubx.FieldSpec{WireName: "assessment_id"},
		"ControlId": ubx.FieldSpec{WireName: "control_id"},
		"ControlSetId": ubx.FieldSpec{WireName: "control_set_id"},
		"MaxResults": ubx.FieldSpec{WireName: "max_results"},
		"NextToken": ubx.FieldSpec{WireName: "next_token"},
	},
}
