// Code generated by `ubx sdk gen` from aws_athena_workgroup. DO NOT EDIT.
package athena

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Workgroup_Configuration_CustomerContentEncryptionConfiguration struct {
	KmsKey any
}

type Workgroup_Configuration_EngineVersion struct {
	EffectiveEngineVersion any
	SelectedEngineVersion any
}

type Workgroup_Configuration_IdentityCenterConfiguration struct {
	EnableIdentityCenter any
	IdentityCenterInstanceArn any
}

type Workgroup_Configuration_ManagedQueryResultsConfiguration struct {
	Enabled any
	EncryptionConfiguration any
}

type Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfiguration_LogType struct {
	Key any
	Values any
}

type Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfiguration struct {
	Enabled any
	LogGroup any
	LogStreamNamePrefix any
	LogType any
}

type Workgroup_Configuration_MonitoringConfiguration_ManagedLoggingConfiguration struct {
	Enabled any
	KmsKey any
}

type Workgroup_Configuration_MonitoringConfiguration_S3LoggingConfiguration struct {
	Enabled any
	KmsKey any
	LogLocation any
}

type Workgroup_Configuration_MonitoringConfiguration struct {
	CloudWatchLoggingConfiguration any
	ManagedLoggingConfiguration any
	S3LoggingConfiguration any
}

type Workgroup_Configuration_QueryResultsS3AccessGrantsConfiguration struct {
	AuthenticationType any
	CreateUserLevelPrefix any
	EnableS3AccessGrants any
}

type Workgroup_Configuration_ResultConfiguration_AclConfiguration struct {
	S3AclOption any
}

type Workgroup_Configuration_ResultConfiguration_EncryptionConfiguration struct {
	EncryptionOption any
	KmsKeyArn any
}

type Workgroup_Configuration_ResultConfiguration struct {
	ExpectedBucketOwner any
	OutputLocation any
	AclConfiguration any
	EncryptionConfiguration any
}

type Workgroup_Configuration struct {
	BytesScannedCutoffPerQuery any
	EnableMinimumEncryptionConfiguration any
	EnforceWorkgroupConfiguration any
	ExecutionRole any
	PublishCloudwatchMetricsEnabled any
	RequesterPaysEnabled any
	CustomerContentEncryptionConfiguration any
	EngineVersion any
	IdentityCenterConfiguration any
	ManagedQueryResultsConfiguration any
	MonitoringConfiguration any
	QueryResultsS3AccessGrantsConfiguration any
	ResultConfiguration any
}

var Workgroup_Configuration_CustomerContentEncryptionConfigurationFields = ubx.FieldMap{
		"KmsKey": ubx.FieldSpec{WireName: "kms_key"},
	}

var Workgroup_Configuration_EngineVersionFields = ubx.FieldMap{
		"EffectiveEngineVersion": ubx.FieldSpec{WireName: "effective_engine_version"},
		"SelectedEngineVersion": ubx.FieldSpec{WireName: "selected_engine_version"},
	}

var Workgroup_Configuration_IdentityCenterConfigurationFields = ubx.FieldMap{
		"EnableIdentityCenter": ubx.FieldSpec{WireName: "enable_identity_center"},
		"IdentityCenterInstanceArn": ubx.FieldSpec{WireName: "identity_center_instance_arn"},
	}

var Workgroup_Configuration_ManagedQueryResultsConfigurationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"EncryptionConfiguration": ubx.FieldSpec{
			WireName: "encryption_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_CustomerContentEncryptionConfigurationFields,
		},
	}

var Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfiguration_LogTypeFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Values": ubx.FieldSpec{WireName: "values"},
	}

var Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfigurationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"LogGroup": ubx.FieldSpec{WireName: "log_group"},
		"LogStreamNamePrefix": ubx.FieldSpec{WireName: "log_stream_name_prefix"},
		"LogType": ubx.FieldSpec{
			WireName: "log_type",
			Kind: "set",
			Fields: Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfiguration_LogTypeFields,
		},
	}

var Workgroup_Configuration_MonitoringConfiguration_ManagedLoggingConfigurationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"KmsKey": ubx.FieldSpec{WireName: "kms_key"},
	}

var Workgroup_Configuration_MonitoringConfiguration_S3LoggingConfigurationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"KmsKey": ubx.FieldSpec{WireName: "kms_key"},
		"LogLocation": ubx.FieldSpec{WireName: "log_location"},
	}

var Workgroup_Configuration_MonitoringConfigurationFields = ubx.FieldMap{
		"CloudWatchLoggingConfiguration": ubx.FieldSpec{
			WireName: "cloud_watch_logging_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_MonitoringConfiguration_CloudWatchLoggingConfigurationFields,
		},
		"ManagedLoggingConfiguration": ubx.FieldSpec{
			WireName: "managed_logging_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_MonitoringConfiguration_ManagedLoggingConfigurationFields,
		},
		"S3LoggingConfiguration": ubx.FieldSpec{
			WireName: "s3_logging_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_MonitoringConfiguration_S3LoggingConfigurationFields,
		},
	}

var Workgroup_Configuration_QueryResultsS3AccessGrantsConfigurationFields = ubx.FieldMap{
		"AuthenticationType": ubx.FieldSpec{WireName: "authentication_type"},
		"CreateUserLevelPrefix": ubx.FieldSpec{WireName: "create_user_level_prefix"},
		"EnableS3AccessGrants": ubx.FieldSpec{WireName: "enable_s3_access_grants"},
	}

var Workgroup_Configuration_ResultConfiguration_AclConfigurationFields = ubx.FieldMap{
		"S3AclOption": ubx.FieldSpec{WireName: "s3_acl_option"},
	}

var Workgroup_Configuration_ResultConfiguration_EncryptionConfigurationFields = ubx.FieldMap{
		"EncryptionOption": ubx.FieldSpec{WireName: "encryption_option"},
		"KmsKeyArn": ubx.FieldSpec{WireName: "kms_key_arn"},
	}

var Workgroup_Configuration_ResultConfigurationFields = ubx.FieldMap{
		"ExpectedBucketOwner": ubx.FieldSpec{WireName: "expected_bucket_owner"},
		"OutputLocation": ubx.FieldSpec{WireName: "output_location"},
		"AclConfiguration": ubx.FieldSpec{
			WireName: "acl_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_ResultConfiguration_AclConfigurationFields,
		},
		"EncryptionConfiguration": ubx.FieldSpec{
			WireName: "encryption_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_ResultConfiguration_EncryptionConfigurationFields,
		},
	}

var Workgroup_ConfigurationFields = ubx.FieldMap{
		"BytesScannedCutoffPerQuery": ubx.FieldSpec{WireName: "bytes_scanned_cutoff_per_query"},
		"EnableMinimumEncryptionConfiguration": ubx.FieldSpec{WireName: "enable_minimum_encryption_configuration"},
		"EnforceWorkgroupConfiguration": ubx.FieldSpec{WireName: "enforce_workgroup_configuration"},
		"ExecutionRole": ubx.FieldSpec{WireName: "execution_role"},
		"PublishCloudwatchMetricsEnabled": ubx.FieldSpec{WireName: "publish_cloudwatch_metrics_enabled"},
		"RequesterPaysEnabled": ubx.FieldSpec{WireName: "requester_pays_enabled"},
		"CustomerContentEncryptionConfiguration": ubx.FieldSpec{
			WireName: "customer_content_encryption_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_CustomerContentEncryptionConfigurationFields,
		},
		"EngineVersion": ubx.FieldSpec{
			WireName: "engine_version",
			Kind: "list",
			Fields: Workgroup_Configuration_EngineVersionFields,
		},
		"IdentityCenterConfiguration": ubx.FieldSpec{
			WireName: "identity_center_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_IdentityCenterConfigurationFields,
		},
		"ManagedQueryResultsConfiguration": ubx.FieldSpec{
			WireName: "managed_query_results_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_ManagedQueryResultsConfigurationFields,
		},
		"MonitoringConfiguration": ubx.FieldSpec{
			WireName: "monitoring_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_MonitoringConfigurationFields,
		},
		"QueryResultsS3AccessGrantsConfiguration": ubx.FieldSpec{
			WireName: "query_results_s3_access_grants_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_QueryResultsS3AccessGrantsConfigurationFields,
		},
		"ResultConfiguration": ubx.FieldSpec{
			WireName: "result_configuration",
			Kind: "list",
			Fields: Workgroup_Configuration_ResultConfigurationFields,
		},
	}

type WorkgroupConfig struct {
	Description any
	ForceDestroy any
	Id any
	Name any
	Region any
	State any
	Tags any
	TagsAll any
	Configuration any
}

var Workgroup = ubx.ResourceBinding{
	WireType: "aws_athena_workgroup",
	Fields: ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"ForceDestroy": ubx.FieldSpec{WireName: "force_destroy"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"State": ubx.FieldSpec{WireName: "state"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"TagsAll": ubx.FieldSpec{WireName: "tags_all"},
		"Configuration": ubx.FieldSpec{
			WireName: "configuration",
			Kind: "list",
			Fields: Workgroup_ConfigurationFields,
		},
	},
}
