// Code generated by `ubx sdk gen` from aws_s3control_storage_lens_configuration. DO NOT EDIT.
package s3control

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetrics struct {
	Enabled any
}

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetrics_SelectionCriteria struct {
	Delimiter any
	MaxDepth any
	MinStorageBytesPercentage any
}

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetrics struct {
	Enabled any
	SelectionCriteria any
}

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel struct {
	StorageMetrics any
}

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel struct {
	ActivityMetrics any
	AdvancedCostOptimizationMetrics any
	AdvancedDataProtectionMetrics any
	AdvancedPerformanceMetrics any
	DetailedStatusCodeMetrics any
	PrefixLevel any
}

type StorageLensConfiguration_StorageLensConfiguration_AccountLevel struct {
	ActivityMetrics any
	AdvancedCostOptimizationMetrics any
	AdvancedDataProtectionMetrics any
	AdvancedPerformanceMetrics any
	BucketLevel any
	DetailedStatusCodeMetrics any
}

type StorageLensConfiguration_StorageLensConfiguration_AwsOrg struct {
	Arn any
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseKms struct {
	KeyId any
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseS3 struct {
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption struct {
	SseKms any
	SseS3 any
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination struct {
	AccountId any
	Arn any
	Format any
	OutputSchemaVersion any
	Prefix any
	Encryption any
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport_StorageLensTableDestination struct {
	Enabled any
	Encryption any
}

type StorageLensConfiguration_StorageLensConfiguration_DataExport struct {
	CloudWatchMetrics any
	S3BucketDestination any
	StorageLensTableDestination any
}

type StorageLensConfiguration_StorageLensConfiguration_Exclude struct {
	Buckets any
	Regions any
}

type StorageLensConfiguration_StorageLensConfiguration_ExpandedPrefixesDataExport struct {
	S3BucketDestination any
	StorageLensTableDestination any
}

type StorageLensConfiguration_StorageLensConfiguration struct {
	Enabled any
	PrefixDelimiter any
	AccountLevel any
	AwsOrg any
	DataExport any
	Exclude any
	ExpandedPrefixesDataExport any
	Include any
}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
	}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetrics_SelectionCriteriaFields = ubx.FieldMap{
		"Delimiter": ubx.FieldSpec{WireName: "delimiter"},
		"MaxDepth": ubx.FieldSpec{WireName: "max_depth"},
		"MinStorageBytesPercentage": ubx.FieldSpec{WireName: "min_storage_bytes_percentage"},
	}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetricsFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"SelectionCriteria": ubx.FieldSpec{
			WireName: "selection_criteria",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetrics_SelectionCriteriaFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevelFields = ubx.FieldMap{
		"StorageMetrics": ubx.FieldSpec{
			WireName: "storage_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevel_StorageMetricsFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevelFields = ubx.FieldMap{
		"ActivityMetrics": ubx.FieldSpec{
			WireName: "activity_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedCostOptimizationMetrics": ubx.FieldSpec{
			WireName: "advanced_cost_optimization_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedDataProtectionMetrics": ubx.FieldSpec{
			WireName: "advanced_data_protection_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedPerformanceMetrics": ubx.FieldSpec{
			WireName: "advanced_performance_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"DetailedStatusCodeMetrics": ubx.FieldSpec{
			WireName: "detailed_status_code_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"PrefixLevel": ubx.FieldSpec{
			WireName: "prefix_level",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevel_PrefixLevelFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_AccountLevelFields = ubx.FieldMap{
		"ActivityMetrics": ubx.FieldSpec{
			WireName: "activity_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedCostOptimizationMetrics": ubx.FieldSpec{
			WireName: "advanced_cost_optimization_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedDataProtectionMetrics": ubx.FieldSpec{
			WireName: "advanced_data_protection_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"AdvancedPerformanceMetrics": ubx.FieldSpec{
			WireName: "advanced_performance_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"BucketLevel": ubx.FieldSpec{
			WireName: "bucket_level",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_BucketLevelFields,
		},
		"DetailedStatusCodeMetrics": ubx.FieldSpec{
			WireName: "detailed_status_code_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_AwsOrgFields = ubx.FieldMap{
		"Arn": ubx.FieldSpec{WireName: "arn"},
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseKmsFields = ubx.FieldMap{
		"KeyId": ubx.FieldSpec{WireName: "key_id"},
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseS3Fields = ubx.FieldMap{
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_EncryptionFields = ubx.FieldMap{
		"SseKms": ubx.FieldSpec{
			WireName: "sse_kms",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseKmsFields,
		},
		"SseS3": ubx.FieldSpec{
			WireName: "sse_s3",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_Encryption_SseS3Fields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestinationFields = ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"Arn": ubx.FieldSpec{WireName: "arn"},
		"Format": ubx.FieldSpec{WireName: "format"},
		"OutputSchemaVersion": ubx.FieldSpec{WireName: "output_schema_version"},
		"Prefix": ubx.FieldSpec{WireName: "prefix"},
		"Encryption": ubx.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_EncryptionFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExport_StorageLensTableDestinationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"Encryption": ubx.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestination_EncryptionFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_DataExportFields = ubx.FieldMap{
		"CloudWatchMetrics": ubx.FieldSpec{
			WireName: "cloud_watch_metrics",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevel_ActivityMetricsFields,
		},
		"S3BucketDestination": ubx.FieldSpec{
			WireName: "s3_bucket_destination",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestinationFields,
		},
		"StorageLensTableDestination": ubx.FieldSpec{
			WireName: "storage_lens_table_destination",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_StorageLensTableDestinationFields,
		},
	}

var StorageLensConfiguration_StorageLensConfiguration_ExcludeFields = ubx.FieldMap{
		"Buckets": ubx.FieldSpec{WireName: "buckets"},
		"Regions": ubx.FieldSpec{WireName: "regions"},
	}

var StorageLensConfiguration_StorageLensConfiguration_ExpandedPrefixesDataExportFields = ubx.FieldMap{
		"S3BucketDestination": ubx.FieldSpec{
			WireName: "s3_bucket_destination",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_S3BucketDestinationFields,
		},
		"StorageLensTableDestination": ubx.FieldSpec{
			WireName: "storage_lens_table_destination",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExport_StorageLensTableDestinationFields,
		},
	}

var StorageLensConfiguration_StorageLensConfigurationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"PrefixDelimiter": ubx.FieldSpec{WireName: "prefix_delimiter"},
		"AccountLevel": ubx.FieldSpec{
			WireName: "account_level",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AccountLevelFields,
		},
		"AwsOrg": ubx.FieldSpec{
			WireName: "aws_org",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_AwsOrgFields,
		},
		"DataExport": ubx.FieldSpec{
			WireName: "data_export",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_DataExportFields,
		},
		"Exclude": ubx.FieldSpec{
			WireName: "exclude",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_ExcludeFields,
		},
		"ExpandedPrefixesDataExport": ubx.FieldSpec{
			WireName: "expanded_prefixes_data_export",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_ExpandedPrefixesDataExportFields,
		},
		"Include": ubx.FieldSpec{
			WireName: "include",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfiguration_ExcludeFields,
		},
	}

type StorageLensConfigurationConfig struct {
	AccountId any
	ConfigId any
	Id any
	Region any
	Tags any
	TagsAll any
	StorageLensConfiguration any
}

var StorageLensConfiguration = ubx.ResourceBinding{
	WireType: "aws_s3control_storage_lens_configuration",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"ConfigId": ubx.FieldSpec{WireName: "config_id"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"TagsAll": ubx.FieldSpec{WireName: "tags_all"},
		"StorageLensConfiguration": ubx.FieldSpec{
			WireName: "storage_lens_configuration",
			Kind: "list",
			Fields: StorageLensConfiguration_StorageLensConfigurationFields,
		},
	},
}
