// Code generated by `ubx sdk gen` from aws_ssmincidents_replication_set. DO NOT EDIT.
package ssmincidents

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ReplicationSet_Regions_RegionConfiguration struct {
	SseKmsKeyId any
}

type ReplicationSet_Regions struct {
	RegionConfiguration any
	RegionName any
}

type ReplicationSet_Tags struct {
	Key any
	Value any
}

var ReplicationSet_Regions_RegionConfigurationFields = ubx.FieldMap{
		"SseKmsKeyId": ubx.FieldSpec{WireName: "sse_kms_key_id"},
	}

var ReplicationSet_RegionsFields = ubx.FieldMap{
		"RegionConfiguration": ubx.FieldSpec{
			WireName: "region_configuration",
			Kind: "object",
			Fields: ReplicationSet_Regions_RegionConfigurationFields,
		},
		"RegionName": ubx.FieldSpec{WireName: "region_name"},
	}

var ReplicationSet_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type ReplicationSetConfig struct {
	// Configures the ReplicationSet deletion protection.
	DeletionProtected any
	Regions any
	// The tags to apply to the replication set.
	Tags any
}

type ReplicationSetAttrs struct {
	// The ARN of the ReplicationSet.
	Arn any
	// Configures the ReplicationSet deletion protection.
	DeletionProtected any
	Regions any
	// The tags to apply to the replication set.
	Tags any
}

var ReplicationSet = ubx.ResourceBinding{
	WireType: "aws_ssmincidents_replication_set",
	Fields: ubx.FieldMap{
		"DeletionProtected": ubx.FieldSpec{WireName: "deletion_protected"},
		"Regions": ubx.FieldSpec{
			WireName: "regions",
			Kind: "list",
			Fields: ReplicationSet_RegionsFields,
		},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: ReplicationSet_TagsFields,
		},
	},
}
