// Code generated by `ubx sdk gen` from aws_servicequotas_association_for_service_quota_template. DO NOT EDIT.
package servicequotas

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AssociationForServiceQuotaTemplateConfig struct {
}

type AssociationForServiceQuotaTemplateAttrs struct {
	ServiceQuotaTemplateAssociationStatus any
}

var AssociationForServiceQuotaTemplate = ubx.DataSourceBinding{
	WireType: "aws_servicequotas_association_for_service_quota_template",
	Fields: ubx.FieldMap{
	},
}
