// Code generated by `ubx sdk gen` from aws_cloud_watch_metric_stream. DO NOT EDIT.
package cloudwatch

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MetricStream_ExcludeFilters struct {
	// The list of metric names within the specified namespace to exclude from the metric stream. (AI-inferred)
	MetricNames any
	// Defines the CloudWatch namespace (e.g., AWS/EC2) whose metrics are excluded from the metric stream when matched by this exclusion filter. (AI-inferred)
	Namespace any
}

type MetricStream_StatisticsConfigurations_IncludeMetrics struct {
	// The name of the CloudWatch metric for which the specified additional statistics are included in the metric stream. (AI-inferred)
	MetricName any
	// The name of the AWS service or custom application namespace (e.g., AWS/EC2, AWS/Lambda) whose metrics are included in this statistics configuration, filtering which metric namespaces are sent to the stream. (AI-inferred)
	Namespace any
}

type MetricStream_StatisticsConfigurations struct {
	// Specifies additional statistics (such as percentiles like p99) to include in the metric stream for metrics that match the namespace and metric name of this statistics configuration. (AI-inferred)
	AdditionalStatistics any
	// Specifies the list of metrics (namespace and metric name) to which the corresponding statistics configuration's allowed statistics apply, controlling which metric streams include the configured statistics. (AI-inferred)
	IncludeMetrics any
}

type MetricStream_Tags struct {
	// The key of a tag attached to the CloudWatch metric stream, used for identifying and organizing the resource. (AI-inferred)
	Key any
	Value any
}

var MetricStream_ExcludeFiltersFields = ubx.FieldMap{
		"MetricNames": ubx.FieldSpec{WireName: "metric_names"},
		"Namespace": ubx.FieldSpec{WireName: "namespace"},
	}

var MetricStream_StatisticsConfigurations_IncludeMetricsFields = ubx.FieldMap{
		"MetricName": ubx.FieldSpec{WireName: "metric_name"},
		"Namespace": ubx.FieldSpec{WireName: "namespace"},
	}

var MetricStream_StatisticsConfigurationsFields = ubx.FieldMap{
		"AdditionalStatistics": ubx.FieldSpec{WireName: "additional_statistics"},
		"IncludeMetrics": ubx.FieldSpec{
			WireName: "include_metrics",
			Kind: "list",
			Fields: MetricStream_StatisticsConfigurations_IncludeMetricsFields,
		},
	}

var MetricStream_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type MetricStreamConfig struct {
	// Define which metrics will be not streamed. Metrics matched by multiple instances of MetricStreamFilter are joined with an OR operation by default. If both IncludeFilters and ExcludeFilters are omitted, all metrics in the account will be streamed. IncludeFilters and ExcludeFilters are mutually exclusive. Default to null.
	ExcludeFilters any
	// The ARN of the Kinesis Firehose where to stream the data.
	FirehoseArn any
	// Define which metrics will be streamed. Metrics matched by multiple instances of MetricStreamFilter are joined with an OR operation by default. If both IncludeFilters and ExcludeFilters are omitted, all metrics in the account will be streamed. IncludeFilters and ExcludeFilters are mutually exclusive. Default to null.
	IncludeFilters any
	// If you are creating a metric stream in a monitoring account, specify true to include metrics from source accounts that are linked to this monitoring account, in the metric stream. The default is false.
	IncludeLinkedAccountsMetrics any
	// Name of the metric stream.
	Name any
	// The output format of the data streamed to the Kinesis Firehose.
	OutputFormat any
	// The ARN of the role that provides access to the Kinesis Firehose.
	RoleArn any
	// By default, a metric stream always sends the MAX, MIN, SUM, and SAMPLECOUNT statistics for each metric that is streamed. You can use this parameter to have the metric stream also send additional statistics in the stream. This array can have up to 100 members.
	StatisticsConfigurations any
	// A set of tags to assign to the delivery stream.
	Tags any
}

type MetricStreamAttrs struct {
	// Amazon Resource Name of the metric stream.
	Arn any
	// The date of creation of the metric stream.
	CreationDate any
	// Define which metrics will be not streamed. Metrics matched by multiple instances of MetricStreamFilter are joined with an OR operation by default. If both IncludeFilters and ExcludeFilters are omitted, all metrics in the account will be streamed. IncludeFilters and ExcludeFilters are mutually exclusive. Default to null.
	ExcludeFilters any
	// The ARN of the Kinesis Firehose where to stream the data.
	FirehoseArn any
	// Define which metrics will be streamed. Metrics matched by multiple instances of MetricStreamFilter are joined with an OR operation by default. If both IncludeFilters and ExcludeFilters are omitted, all metrics in the account will be streamed. IncludeFilters and ExcludeFilters are mutually exclusive. Default to null.
	IncludeFilters any
	// If you are creating a metric stream in a monitoring account, specify true to include metrics from source accounts that are linked to this monitoring account, in the metric stream. The default is false.
	IncludeLinkedAccountsMetrics any
	// The date of the last update of the metric stream.
	LastUpdateDate any
	// Name of the metric stream.
	Name any
	// The output format of the data streamed to the Kinesis Firehose.
	OutputFormat any
	// The ARN of the role that provides access to the Kinesis Firehose.
	RoleArn any
	// Displays the state of the Metric Stream.
	State any
	// By default, a metric stream always sends the MAX, MIN, SUM, and SAMPLECOUNT statistics for each metric that is streamed. You can use this parameter to have the metric stream also send additional statistics in the stream. This array can have up to 100 members.
	StatisticsConfigurations any
	// A set of tags to assign to the delivery stream.
	Tags any
}

var MetricStream = ubx.ResourceBinding{
	WireType: "aws_cloud_watch_metric_stream",
	Fields: ubx.FieldMap{
		"ExcludeFilters": ubx.FieldSpec{
			WireName: "exclude_filters",
			Kind: "list",
			Fields: MetricStream_ExcludeFiltersFields,
		},
		"FirehoseArn": ubx.FieldSpec{WireName: "firehose_arn"},
		"IncludeFilters": ubx.FieldSpec{
			WireName: "include_filters",
			Kind: "list",
			Fields: MetricStream_ExcludeFiltersFields,
		},
		"IncludeLinkedAccountsMetrics": ubx.FieldSpec{WireName: "include_linked_accounts_metrics"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"OutputFormat": ubx.FieldSpec{WireName: "output_format"},
		"RoleArn": ubx.FieldSpec{WireName: "role_arn"},
		"StatisticsConfigurations": ubx.FieldSpec{
			WireName: "statistics_configurations",
			Kind: "list",
			Fields: MetricStream_StatisticsConfigurationsFields,
		},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: MetricStream_TagsFields,
		},
	},
}
