// Code generated by `ubx sdk gen` from aws_qbusiness_data_source_sync_jobs. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DataSourceSyncJobs_History_Error {
  errorCode?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
}

export interface DataSourceSyncJobs_History_Metrics {
  documentsAdded?: string | Computed<string>;
  documentsDeleted?: string | Computed<string>;
  documentsFailed?: string | Computed<string>;
  documentsModified?: string | Computed<string>;
  documentsScanned?: string | Computed<string>;
}

export interface DataSourceSyncJobs_History {
  dataSourceErrorCode?: string | Computed<string>;
  endTime?: string | Computed<string>;
  error?: DataSourceSyncJobs_History_Error | Computed<DataSourceSyncJobs_History_Error>;
  executionId?: string | Computed<string>;
  metrics?: DataSourceSyncJobs_History_Metrics | Computed<DataSourceSyncJobs_History_Metrics>;
  startTime?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface DataSourceSyncJobsConfig {
  applicationId: string | Computed<string>;
  dataSourceId: string | Computed<string>;
  endTime?: string | Computed<string>;
  indexId: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  startTime?: string | Computed<string>;
  statusFilter?: string | Computed<string>;
}

export interface DataSourceSyncJobsAttrs {
  applicationId: string;
  dataSourceId: string;
  endTime: string;
  history: DataSourceSyncJobs_History[];
  indexId: string;
  maxResults: number;
  nextToken: string;
  startTime: string;
  statusFilter: string;
}

export const DataSourceSyncJobs: DataSourceBinding<DataSourceSyncJobsConfig, DataSourceSyncJobsAttrs> = {
  wireType: "aws_qbusiness_data_source_sync_jobs",
  fields: {
    applicationId: "application_id",
    dataSourceId: "data_source_id",
    endTime: "end_time",
    indexId: "index_id",
    maxResults: "max_results",
    nextToken: "next_token",
    startTime: "start_time",
    statusFilter: "status_filter",
  },
};
