// Code generated by `ubx sdk gen` from aws_qbusiness_messages. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Messages_Messages_ActionExecution_Payload {
  value?: unknown | Computed<unknown>;
}

export interface Messages_Messages_ActionExecution {
  payload?: Record<string, Messages_Messages_ActionExecution_Payload> | Computed<Record<string, Messages_Messages_ActionExecution_Payload>>;
  payloadFieldNameSeparator?: string | Computed<string>;
  pluginId?: string | Computed<string>;
}

export interface Messages_Messages_ActionReview_Payload_AllowedValues {
  displayValue?: unknown | Computed<unknown>;
  value?: unknown | Computed<unknown>;
}

export interface Messages_Messages_ActionReview_Payload {
  allowedFormat?: string | Computed<string>;
  allowedValues?: Messages_Messages_ActionReview_Payload_AllowedValues[] | Computed<Messages_Messages_ActionReview_Payload_AllowedValues[]>;
  arrayItemJsonSchema?: unknown | Computed<unknown>;
  displayDescription?: string | Computed<string>;
  displayName?: string | Computed<string>;
  displayOrder?: number | Computed<number>;
  required?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
}

export interface Messages_Messages_ActionReview {
  payload?: Record<string, Messages_Messages_ActionReview_Payload> | Computed<Record<string, Messages_Messages_ActionReview_Payload>>;
  payloadFieldNameSeparator?: string | Computed<string>;
  pluginId?: string | Computed<string>;
  pluginType?: string | Computed<string>;
}

export interface Messages_Messages_Attachments_Error {
  errorCode?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
}

export interface Messages_Messages_Attachments {
  attachmentId?: string | Computed<string>;
  conversationId?: string | Computed<string>;
  error?: Messages_Messages_Attachments_Error | Computed<Messages_Messages_Attachments_Error>;
  name?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments_SnippetExcerpt {
  text?: string | Computed<string>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_AudioSourceDetails {
  audioExtractionType?: string | Computed<string>;
  endTimeMilliseconds?: number | Computed<number>;
  mediaId?: string | Computed<string>;
  mediaMimeType?: string | Computed<string>;
  startTimeMilliseconds?: number | Computed<number>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_ImageSourceDetails {
  mediaId?: string | Computed<string>;
  mediaMimeType?: string | Computed<string>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_VideoSourceDetails {
  endTimeMilliseconds?: number | Computed<number>;
  mediaId?: string | Computed<string>;
  mediaMimeType?: string | Computed<string>;
  startTimeMilliseconds?: number | Computed<number>;
  videoExtractionType?: string | Computed<string>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails {
  audioSourceDetails?: Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_AudioSourceDetails | Computed<Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_AudioSourceDetails>;
  imageSourceDetails?: Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_ImageSourceDetails | Computed<Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_ImageSourceDetails>;
  videoSourceDetails?: Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_VideoSourceDetails | Computed<Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails_VideoSourceDetails>;
}

export interface Messages_Messages_SourceAttribution_TextMessageSegments {
  beginOffset?: number | Computed<number>;
  endOffset?: number | Computed<number>;
  mediaId?: string | Computed<string>;
  mediaMimeType?: string | Computed<string>;
  snippetExcerpt?: Messages_Messages_SourceAttribution_TextMessageSegments_SnippetExcerpt | Computed<Messages_Messages_SourceAttribution_TextMessageSegments_SnippetExcerpt>;
  sourceDetails?: Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails | Computed<Messages_Messages_SourceAttribution_TextMessageSegments_SourceDetails>;
}

export interface Messages_Messages_SourceAttribution {
  citationNumber?: number | Computed<number>;
  datasourceId?: string | Computed<string>;
  documentId?: string | Computed<string>;
  indexId?: string | Computed<string>;
  snippet?: string | Computed<string>;
  textMessageSegments?: Messages_Messages_SourceAttribution_TextMessageSegments[] | Computed<Messages_Messages_SourceAttribution_TextMessageSegments[]>;
  title?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface Messages_Messages {
  actionExecution?: Messages_Messages_ActionExecution | Computed<Messages_Messages_ActionExecution>;
  actionReview?: Messages_Messages_ActionReview | Computed<Messages_Messages_ActionReview>;
  attachments?: Messages_Messages_Attachments[] | Computed<Messages_Messages_Attachments[]>;
  body?: string | Computed<string>;
  messageId?: string | Computed<string>;
  sourceAttribution?: Messages_Messages_SourceAttribution[] | Computed<Messages_Messages_SourceAttribution[]>;
  time?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface MessagesConfig {
  applicationId: string | Computed<string>;
  conversationId: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  userId?: string | Computed<string>;
}

export interface MessagesAttrs {
  applicationId: string;
  conversationId: string;
  maxResults: number;
  messages: Messages_Messages[];
  nextToken: string;
  userId: string;
}

export const Messages: DataSourceBinding<MessagesConfig, MessagesAttrs> = {
  wireType: "aws_qbusiness_messages",
  fields: {
    applicationId: "application_id",
    conversationId: "conversation_id",
    maxResults: "max_results",
    nextToken: "next_token",
    userId: "user_id",
  },
};
