// Code generated by `ubx sdk gen` from aws_pcs_cluster. DO NOT EDIT.
package pcs

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Cluster_Endpoints struct {
	Ipv6Address any
	Port any
	PrivateIpAddress any
	PublicIpAddress any
	Type any
}

type Cluster_ErrorInfo struct {
	Code any
	Message any
}

type Cluster_Networking struct {
	// The IP of the cluster (IPV4 or IPV6)
	NetworkType any
	// The list of security group IDs associated with the Elastic Network Interface (ENI) created in subnets.
	SecurityGroupIds any
	// The list of subnet IDs where AWS PCS creates an Elastic Network Interface (ENI) to enable communication between managed controllers and AWS PCS resources. The subnet must have an available IP address, cannot reside in AWS Outposts, AWS Wavelength, or an AWS Local Zone. AWS PCS currently supports only 1 subnet in this list.
	SubnetIds any
}

type Cluster_Scheduler struct {
	// The software AWS PCS uses to manage cluster scaling and job scheduling.
	Type any
	// The version of the specified scheduling software that AWS PCS uses to manage cluster scaling and job scheduling.
	Version any
}

type Cluster_SlurmConfiguration_Accounting struct {
	// The default value for all purge settings for `slurmdbd.conf`. For more information, see the [slurmdbd.conf documentation at SchedMD](https://slurm.schedmd.com/slurmdbd.conf.html). The default value is `-1`. A value of `-1` means there is no purge time and records persist as long as the cluster exists.
	DefaultPurgeTimeInDays any
	// The default value is `NONE`. A value of `STANDARD` means that Slurm accounting is enabled.
	Mode any
}

type Cluster_SlurmConfiguration_AuthKey struct {
	// The Amazon Resource Name (ARN) of the the shared Slurm key.
	SecretArn any
	// The version of the shared Slurm key.
	SecretVersion any
}

type Cluster_SlurmConfiguration_CgroupCustomSettings struct {
	ParameterName any
	ParameterValue any
}

type Cluster_SlurmConfiguration_JwtAuth struct {
	// JWT key configuration.
	JwtKey any
}

type Cluster_SlurmConfiguration_SlurmRest struct {
	// The default value is `NONE`. A value of `STANDARD` means that Slurm Rest is enabled.
	Mode any
}

type Cluster_SlurmConfiguration struct {
	// The accounting configuration includes configurable settings for Slurm accounting.
	Accounting any
	// The shared Slurm key for authentication, also known as the cluster secret.
	AuthKey any
	// Additional cgroup-specific configuration that directly maps to cgroup.conf settings.
	CgroupCustomSettings any
	// JWT authentication configuration for Slurm.
	JwtAuth any
	// The time before an idle node is scaled down.
	ScaleDownIdleTimeInSeconds any
	// Additional Slurm-specific configuration that directly maps to Slurm settings.
	SlurmCustomSettings any
	// The SlurmRest configuration includes configurable settings for Slurm Rest.
	SlurmRest any
	// Additional slurmdbd-specific configuration that directly maps to slurmdbd.conf settings.
	SlurmdbdCustomSettings any
}

var Cluster_NetworkingFields = ubx.FieldMap{
		"NetworkType": ubx.FieldSpec{WireName: "network_type"},
		"SecurityGroupIds": ubx.FieldSpec{WireName: "security_group_ids"},
		"SubnetIds": ubx.FieldSpec{WireName: "subnet_ids"},
	}

var Cluster_SchedulerFields = ubx.FieldMap{
		"Type": ubx.FieldSpec{WireName: "type"},
		"Version": ubx.FieldSpec{WireName: "version"},
	}

var Cluster_SlurmConfiguration_AccountingFields = ubx.FieldMap{
		"DefaultPurgeTimeInDays": ubx.FieldSpec{WireName: "default_purge_time_in_days"},
		"Mode": ubx.FieldSpec{WireName: "mode"},
	}

var Cluster_SlurmConfiguration_AuthKeyFields = ubx.FieldMap{
		"SecretArn": ubx.FieldSpec{WireName: "secret_arn"},
		"SecretVersion": ubx.FieldSpec{WireName: "secret_version"},
	}

var Cluster_SlurmConfiguration_CgroupCustomSettingsFields = ubx.FieldMap{
		"ParameterName": ubx.FieldSpec{WireName: "parameter_name"},
		"ParameterValue": ubx.FieldSpec{WireName: "parameter_value"},
	}

var Cluster_SlurmConfiguration_JwtAuthFields = ubx.FieldMap{
		"JwtKey": ubx.FieldSpec{
			WireName: "jwt_key",
			Kind: "object",
			Fields: Cluster_SlurmConfiguration_AuthKeyFields,
		},
	}

var Cluster_SlurmConfiguration_SlurmRestFields = ubx.FieldMap{
		"Mode": ubx.FieldSpec{WireName: "mode"},
	}

var Cluster_SlurmConfigurationFields = ubx.FieldMap{
		"Accounting": ubx.FieldSpec{
			WireName: "accounting",
			Kind: "object",
			Fields: Cluster_SlurmConfiguration_AccountingFields,
		},
		"AuthKey": ubx.FieldSpec{
			WireName: "auth_key",
			Kind: "object",
			Fields: Cluster_SlurmConfiguration_AuthKeyFields,
		},
		"CgroupCustomSettings": ubx.FieldSpec{
			WireName: "cgroup_custom_settings",
			Kind: "list",
			Fields: Cluster_SlurmConfiguration_CgroupCustomSettingsFields,
		},
		"JwtAuth": ubx.FieldSpec{
			WireName: "jwt_auth",
			Kind: "object",
			Fields: Cluster_SlurmConfiguration_JwtAuthFields,
		},
		"ScaleDownIdleTimeInSeconds": ubx.FieldSpec{WireName: "scale_down_idle_time_in_seconds"},
		"SlurmCustomSettings": ubx.FieldSpec{
			WireName: "slurm_custom_settings",
			Kind: "list",
			Fields: Cluster_SlurmConfiguration_CgroupCustomSettingsFields,
		},
		"SlurmRest": ubx.FieldSpec{
			WireName: "slurm_rest",
			Kind: "object",
			Fields: Cluster_SlurmConfiguration_SlurmRestFields,
		},
		"SlurmdbdCustomSettings": ubx.FieldSpec{
			WireName: "slurmdbd_custom_settings",
			Kind: "list",
			Fields: Cluster_SlurmConfiguration_CgroupCustomSettingsFields,
		},
	}

type ClusterConfig struct {
	// The name that identifies the cluster.
	Name any
	// The networking configuration for the cluster's control plane.
	Networking any
	// The cluster management and job scheduling software associated with the cluster.
	Scheduler any
	// The size of the cluster.
	Size any
	// Additional options related to the Slurm scheduler.
	SlurmConfiguration any
	// 1 or more tags added to the resource. Each tag consists of a tag key and tag value. The tag value is optional and can be an empty string.
	Tags any
}

type ClusterAttrs struct {
	// The unique Amazon Resource Name (ARN) of the cluster.
	Arn any
	// The list of endpoints available for interaction with the scheduler.
	Endpoints any
	// The list of errors that occurred during cluster provisioning.
	ErrorInfo any
	// The generated unique ID of the cluster.
	Id any
	// The name that identifies the cluster.
	Name any
	// The networking configuration for the cluster's control plane.
	Networking any
	// The cluster management and job scheduling software associated with the cluster.
	Scheduler any
	// The size of the cluster.
	Size any
	// Additional options related to the Slurm scheduler.
	SlurmConfiguration any
	// The provisioning status of the cluster. The provisioning status doesn't indicate the overall health of the cluster.
	Status any
	// 1 or more tags added to the resource. Each tag consists of a tag key and tag value. The tag value is optional and can be an empty string.
	Tags any
}

var Cluster = ubx.ResourceBinding{
	WireType: "aws_pcs_cluster",
	Fields: ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"Networking": ubx.FieldSpec{
			WireName: "networking",
			Kind: "object",
			Fields: Cluster_NetworkingFields,
		},
		"Scheduler": ubx.FieldSpec{
			WireName: "scheduler",
			Kind: "object",
			Fields: Cluster_SchedulerFields,
		},
		"Size": ubx.FieldSpec{WireName: "size"},
		"SlurmConfiguration": ubx.FieldSpec{
			WireName: "slurm_configuration",
			Kind: "object",
			Fields: Cluster_SlurmConfigurationFields,
		},
		"Tags": ubx.FieldSpec{WireName: "tags"},
	},
}
