// Code generated by `ubx sdk gen` from aws_pcaconnector_ad_service_principal_name. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServicePrincipalNameConfig {
  /** The ARN of the Active Directory connector to which this service principal name is registered. (AI-inferred) */
  connectorArn: string | Computed<string>;
  /** The ARN of the directory registration that this service principal name belongs to, linking the SPN to the associated AWS Managed Microsoft Active Directory. (AI-inferred) */
  directoryRegistrationArn: string | Computed<string>;
}

export interface ServicePrincipalNameAttrs {
  /** The ARN of the Active Directory connector to which this service principal name is registered. (AI-inferred) */
  connectorArn: string;
  /** The ARN of the directory registration that this service principal name belongs to, linking the SPN to the associated AWS Managed Microsoft Active Directory. (AI-inferred) */
  directoryRegistrationArn: string;
}

export const ServicePrincipalName: ResourceBinding<ServicePrincipalNameConfig, ServicePrincipalNameAttrs> = {
  wireType: "aws_pcaconnector_ad_service_principal_name",
  fields: {
    connectorArn: "connector_arn",
    directoryRegistrationArn: "directory_registration_arn",
  },
};
