# Code generated by `ubx sdk gen` from aws_cloudwatch_log_anomaly_detector. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LogAnomalyDetectorConfig:
    anomaly_visibility_time: Any = None
    detector_name: Any = None
    enabled: Any = None
    evaluation_frequency: Any = None
    filter_pattern: Any = None
    kms_key_id: Any = None
    log_group_arn_list: Any = None
    region: Any = None
    tags: Any = None

LogAnomalyDetector = ubx.ResourceBinding(
    wire_type="aws_cloudwatch_log_anomaly_detector",
    fields={
        "anomaly_visibility_time": ubx.FieldSpec(wire_name="anomaly_visibility_time"),
        "detector_name": ubx.FieldSpec(wire_name="detector_name"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "evaluation_frequency": ubx.FieldSpec(wire_name="evaluation_frequency"),
        "filter_pattern": ubx.FieldSpec(wire_name="filter_pattern"),
        "kms_key_id": ubx.FieldSpec(wire_name="kms_key_id"),
        "log_group_arn_list": ubx.FieldSpec(wire_name="log_group_arn_list"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
    },
)
