# Code generated by `ubx sdk gen` from aws_lookoutequipment_inference_executions. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries_CustomerResultObject:
    bucket: Any = None
    key: Any = None

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries_DataInputConfiguration_InferenceInputNameConfiguration:
    component_timestamp_delimiter: Any = None
    timestamp_format: Any = None

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries_DataInputConfiguration_S3InputConfiguration:
    bucket: Any = None
    prefix: Any = None

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries_DataInputConfiguration:
    inference_input_name_configuration: Any = None
    input_time_zone_offset: Any = None
    s3_input_configuration: Any = None

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries_DataOutputConfiguration:
    kms_key_id: Any = None
    s3_output_configuration: Any = None

@dataclasses.dataclass
class InferenceExecutions_InferenceExecutionSummaries:
    customer_result_object: Any = None
    data_end_time: Any = None
    data_input_configuration: Any = None
    data_output_configuration: Any = None
    data_start_time: Any = None
    failed_reason: Any = None
    inference_scheduler_arn: Any = None
    inference_scheduler_name: Any = None
    model_arn: Any = None
    model_name: Any = None
    model_version: Any = None
    model_version_arn: Any = None
    scheduled_start_time: Any = None
    status: Any = None

@dataclasses.dataclass
class InferenceExecutionsConfig:
    data_end_time_before: Any = None
    data_start_time_after: Any = None
    inference_scheduler_name: Any = None
    max_results: Any = None
    next_token: Any = None
    status: Any = None

@dataclasses.dataclass
class InferenceExecutionsAttrs:
    data_end_time_before: Any = None
    data_start_time_after: Any = None
    inference_execution_summaries: Any = None
    inference_scheduler_name: Any = None
    max_results: Any = None
    next_token: Any = None
    status: Any = None

InferenceExecutions = ubx.DataSourceBinding(
    wire_type="aws_lookoutequipment_inference_executions",
    fields={
        "data_end_time_before": ubx.FieldSpec(wire_name="data_end_time_before"),
        "data_start_time_after": ubx.FieldSpec(wire_name="data_start_time_after"),
        "inference_scheduler_name": ubx.FieldSpec(wire_name="inference_scheduler_name"),
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
        "status": ubx.FieldSpec(wire_name="status"),
    },
)
