# Code generated by `ubx sdk gen` from aws_servicecatalog_provisioned_product_outputs. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ProvisionedProductOutputs_Outputs:
    description: Any = None
    output_key: Any = None
    output_value: Any = None

@dataclasses.dataclass
class ProvisionedProductOutputsConfig:
    accept_language: Any = None
    output_keys: Any = None
    page_size: Any = None
    page_token: Any = None
    provisioned_product_id: Any = None
    provisioned_product_name: Any = None

@dataclasses.dataclass
class ProvisionedProductOutputsAttrs:
    accept_language: Any = None
    next_page_token: Any = None
    output_keys: Any = None
    outputs: Any = None
    page_size: Any = None
    page_token: Any = None
    provisioned_product_id: Any = None
    provisioned_product_name: Any = None

ProvisionedProductOutputs = ubx.DataSourceBinding(
    wire_type="aws_servicecatalog_provisioned_product_outputs",
    fields={
        "accept_language": ubx.FieldSpec(wire_name="accept_language"),
        "output_keys": ubx.FieldSpec(wire_name="output_keys"),
        "page_size": ubx.FieldSpec(wire_name="page_size"),
        "page_token": ubx.FieldSpec(wire_name="page_token"),
        "provisioned_product_id": ubx.FieldSpec(wire_name="provisioned_product_id"),
        "provisioned_product_name": ubx.FieldSpec(wire_name="provisioned_product_name"),
    },
)
