# Code generated by `ubx sdk gen` from aws_messaging_chime_channel_bans. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MessagingChimeChannelBans_ChannelBans_Member:
    arn: Any = None
    name: Any = None

@dataclasses.dataclass
class MessagingChimeChannelBans_ChannelBans:
    member: Any = None

@dataclasses.dataclass
class MessagingChimeChannelBansConfig:
    channel_arn: Any = None
    chime_bearer: Any = None
    max_results: Any = None
    next_token: Any = None

@dataclasses.dataclass
class MessagingChimeChannelBansAttrs:
    channel_arn: Any = None
    channel_bans: Any = None
    chime_bearer: Any = None
    max_results: Any = None
    next_token: Any = None

MessagingChimeChannelBans = ubx.DataSourceBinding(
    wire_type="aws_messaging_chime_channel_bans",
    fields={
        "channel_arn": ubx.FieldSpec(wire_name="channel_arn"),
        "chime_bearer": ubx.FieldSpec(wire_name="chime_bearer"),
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
    },
)
