// Code generated by `ubx sdk gen` from aws_backup_protected_resource. DO NOT EDIT.
package backup

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectedResourceConfig struct {
	ResourceArn any
}

type ProtectedResourceAttrs struct {
	LastBackupTime any
	LastBackupVaultArn any
	LastRecoveryPointArn any
	LatestRestoreExecutionTimeMinutes any
	LatestRestoreJobCreationDate any
	LatestRestoreRecoveryPointCreationDate any
	ResourceArn any
	ResourceName any
	ResourceType any
}

var ProtectedResource = ubx.DataSourceBinding{
	WireType: "aws_backup_protected_resource",
	Fields: ubx.FieldMap{
		"ResourceArn": ubx.FieldSpec{WireName: "resource_arn"},
	},
}
