# Code generated by `ubx sdk gen` from aws_ec2_conversion_tasks. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_ImportInstance_Volumes_Image:
    checksum: Any = None
    format: Any = None
    import_manifest_url: Any = None
    size: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_ImportInstance_Volumes_Volume:
    id: Any = None
    size: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_ImportInstance_Volumes:
    availability_zone: Any = None
    availability_zone_id: Any = None
    bytes_converted: Any = None
    description: Any = None
    image: Any = None
    status: Any = None
    status_message: Any = None
    volume: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_ImportInstance:
    description: Any = None
    instance_id: Any = None
    platform: Any = None
    volumes: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_ImportVolume:
    availability_zone: Any = None
    availability_zone_id: Any = None
    bytes_converted: Any = None
    description: Any = None
    image: Any = None
    volume: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks_Tags:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class ConversionTasks_ConversionTasks:
    conversion_task_id: Any = None
    expiration_time: Any = None
    import_instance: Any = None
    import_volume: Any = None
    state: Any = None
    status_message: Any = None
    tags: Any = None

@dataclasses.dataclass
class ConversionTasksConfig:
    conversion_task_ids: Any = None
    dry_run: Any = None

@dataclasses.dataclass
class ConversionTasksAttrs:
    conversion_task_ids: Any = None
    conversion_tasks: Any = None
    dry_run: Any = None

ConversionTasks = ubx.DataSourceBinding(
    wire_type="aws_ec2_conversion_tasks",
    fields={
        "conversion_task_ids": ubx.FieldSpec(wire_name="conversion_task_ids"),
        "dry_run": ubx.FieldSpec(wire_name="dry_run"),
    },
)
