# Code generated by `ubx sdk gen` from aws_customer_gateway. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Gateway_Tags:
    # The key for a tag assigned to the AWS Customer Gateway resource, used for identification and resource management. (AI-inferred)
    key: Any = None
    # The value portion of a tag assigned to the customer gateway, used for arbitrary metadata. (AI-inferred)
    value: Any = None

_Gateway_TagsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

@dataclasses.dataclass
class GatewayConfig:
    # For customer gateway devices that support BGP, specify the device's ASN. You must specify either ``BgpAsn`` or ``BgpAsnExtended`` when creating the customer gateway. If the ASN is larger than ``2,147,483,647``, you must use ``BgpAsnExtended``. Default: 65000 Valid values: ``1`` to ``2,147,483,647``
    bgp_asn: Any = None
    # For customer gateway devices that support BGP, specify the device's ASN. You must specify either ``BgpAsn`` or ``BgpAsnExtended`` when creating the customer gateway. If the ASN is larger than ``2,147,483,647``, you must use ``BgpAsnExtended``. Valid values: ``2,147,483,648`` to ``4,294,967,295``
    bgp_asn_extended: Any = None
    # The Amazon Resource Name (ARN) for the customer gateway certificate.
    certificate_arn: Any = None
    # The name of customer gateway device.
    device_name: Any = None
    # The IP address for the customer gateway device's outside interface. The address must be static. If ``OutsideIpAddressType`` in your VPN connection options is set to ``PrivateIpv4``, you can use an RFC6598 or RFC1918 private IPv4 address. If ``OutsideIpAddressType`` is set to ``Ipv6``, you can use an IPv6 address.
    ip_address: Any = None
    # One or more tags for the customer gateway.
    tags: Any = None
    # The type of VPN connection that this customer gateway supports (``ipsec.1``).
    type: Any = None

@dataclasses.dataclass
class GatewayAttrs:
    # For customer gateway devices that support BGP, specify the device's ASN. You must specify either ``BgpAsn`` or ``BgpAsnExtended`` when creating the customer gateway. If the ASN is larger than ``2,147,483,647``, you must use ``BgpAsnExtended``. Default: 65000 Valid values: ``1`` to ``2,147,483,647``
    bgp_asn: Any = None
    # For customer gateway devices that support BGP, specify the device's ASN. You must specify either ``BgpAsn`` or ``BgpAsnExtended`` when creating the customer gateway. If the ASN is larger than ``2,147,483,647``, you must use ``BgpAsnExtended``. Valid values: ``2,147,483,648`` to ``4,294,967,295``
    bgp_asn_extended: Any = None
    # The Amazon Resource Name (ARN) for the customer gateway certificate.
    certificate_arn: Any = None
    # The unique identifier assigned by AWS to the customer gateway, such as cgw-0a1b2c3d4e5f6g7h8. (AI-inferred)
    customer_gateway_id: Any = None
    # The name of customer gateway device.
    device_name: Any = None
    # The IP address for the customer gateway device's outside interface. The address must be static. If ``OutsideIpAddressType`` in your VPN connection options is set to ``PrivateIpv4``, you can use an RFC6598 or RFC1918 private IPv4 address. If ``OutsideIpAddressType`` is set to ``Ipv6``, you can use an IPv6 address.
    ip_address: Any = None
    # One or more tags for the customer gateway.
    tags: Any = None
    # The type of VPN connection that this customer gateway supports (``ipsec.1``).
    type: Any = None

Gateway = ubx.ResourceBinding(
    wire_type="aws_customer_gateway",
    fields={
        "bgp_asn": ubx.FieldSpec(wire_name="bgp_asn"),
        "bgp_asn_extended": ubx.FieldSpec(wire_name="bgp_asn_extended"),
        "certificate_arn": ubx.FieldSpec(wire_name="certificate_arn"),
        "device_name": ubx.FieldSpec(wire_name="device_name"),
        "ip_address": ubx.FieldSpec(wire_name="ip_address"),
        "tags": ubx.FieldSpec(
            wire_name="tags",
            kind="list",
            fields=_Gateway_TagsFields,
        ),
        "type": ubx.FieldSpec(wire_name="type"),
    },
)
