// Code generated by `ubx sdk gen` from aws_codecatalyst_project. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Project_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Project_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ProjectConfig {
  description?: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  region?: string | Computed<string>;
  spaceName: string | Computed<string>;
  timeouts?: Project_Timeouts | Computed<Project_Timeouts>;
}

export interface ProjectAttrs {
  description: string;
  displayName: string;
  id: string;
  name: string;
  region: string;
  spaceName: string;
  timeouts: Project_Timeouts;
}

export const Project: ResourceBinding<ProjectConfig, ProjectAttrs> = {
  wireType: "aws_codecatalyst_project",
  fields: {
    description: "description",
    displayName: "display_name",
    id: "id",
    region: "region",
    spaceName: "space_name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Project_TimeoutsFields,
    },
  },
};
