// Code generated by `ubx sdk gen` from aws_quicksight_asset_bundle_export_jobs. DO NOT EDIT.
package quicksight

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AssetBundleExportJobs_AssetBundleExportJobSummaryList struct {
	Arn any
	AssetBundleExportJobId any
	CreatedTime any
	ExportFormat any
	IncludeAllDependencies any
	IncludePermissions any
	IncludeTags any
	JobStatus any
}

type AssetBundleExportJobsConfig struct {
	AwsAccountId any
	MaxResults any
	NextToken any
}

type AssetBundleExportJobsAttrs struct {
	AssetBundleExportJobSummaryList any
	AwsAccountId any
	MaxResults any
	NextToken any
	RequestId any
	Status any
}

var AssetBundleExportJobs = ubx.DataSourceBinding{
	WireType: "aws_quicksight_asset_bundle_export_jobs",
	Fields: ubx.FieldMap{
		"AwsAccountId": ubx.FieldSpec{WireName: "aws_account_id"},
		"MaxResults": ubx.FieldSpec{WireName: "max_results"},
		"NextToken": ubx.FieldSpec{WireName: "next_token"},
	},
}
