// Code generated by `ubx sdk gen` from aws_glue_schema_version_metadata. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SchemaVersionMetadataConfig {
  /** Metadata key */
  key: string | Computed<string>;
  /** Represents the version ID associated with the schema version. */
  schemaVersionId: string | Computed<string>;
  /** Metadata value */
  value: string | Computed<string>;
}

export interface SchemaVersionMetadataAttrs {
  /** Metadata key */
  key: string;
  /** Represents the version ID associated with the schema version. */
  schemaVersionId: string;
  /** Metadata value */
  value: string;
}

export const SchemaVersionMetadata: ResourceBinding<SchemaVersionMetadataConfig, SchemaVersionMetadataAttrs> = {
  wireType: "aws_glue_schema_version_metadata",
  fields: {
    key: "key",
    schemaVersionId: "schema_version_id",
    value: "value",
  },
};
