// Code generated by `ubx sdk gen` from aws_rekognition_person_tracking. DO NOT EDIT.
package rekognition

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PersonTracking_Persons_Person_BoundingBox struct {
	Height any
	Left any
	Top any
	Width any
}

type PersonTracking_Persons_Person_Face_AgeRange struct {
	High any
	Low any
}

type PersonTracking_Persons_Person_Face_Beard struct {
	Confidence any
	Value any
}

type PersonTracking_Persons_Person_Face_Emotions struct {
	Confidence any
	Type any
}

type PersonTracking_Persons_Person_Face_EyeDirection struct {
	Confidence any
	Pitch any
	Yaw any
}

type PersonTracking_Persons_Person_Face_Gender struct {
	Confidence any
	Value any
}

type PersonTracking_Persons_Person_Face_Landmarks struct {
	Type any
	X any
	Y any
}

type PersonTracking_Persons_Person_Face_Pose struct {
	Pitch any
	Roll any
	Yaw any
}

type PersonTracking_Persons_Person_Face_Quality struct {
	Brightness any
	Sharpness any
}

type PersonTracking_Persons_Person_Face struct {
	AgeRange any
	Beard any
	BoundingBox any
	Confidence any
	Emotions any
	EyeDirection any
	Eyeglasses any
	EyesOpen any
	FaceOccluded any
	Gender any
	Landmarks any
	MouthOpen any
	Mustache any
	Pose any
	Quality any
	Smile any
	Sunglasses any
}

type PersonTracking_Persons_Person struct {
	BoundingBox any
	Face any
	Index any
}

type PersonTracking_Persons struct {
	Person any
	Timestamp any
}

type PersonTracking_Video_S3Object struct {
	Bucket any
	Name any
	Version any
}

type PersonTracking_Video struct {
	// <p>Provides the S3 bucket name and object name.</p> <p>The region for the S3 bucket containing the S3 object must match the region you use for Amazon Rekognition operations.</p> <p>For Amazon Rekognition to process an S3 object, the user must have permission to access the S3 object. For more information, see How Amazon Rekognition works with IAM in the Amazon Rekognition Developer Guide. </p>
	S3Object any
}

type PersonTracking_VideoMetadata struct {
	Codec any
	ColorRange any
	DurationMillis any
	Format any
	FrameHeight any
	FrameRate any
	FrameWidth any
}

type PersonTrackingConfig struct {
	JobId any
	MaxResults any
	NextToken any
	SortBy any
}

type PersonTrackingAttrs struct {
	JobId any
	JobStatus any
	JobTag any
	MaxResults any
	NextToken any
	Persons any
	SortBy any
	StatusMessage any
	// <p>Video file stored in an Amazon S3 bucket. Amazon Rekognition video start operations such as <a>StartLabelDetection</a> use <code>Video</code> to specify a video for analysis. The supported file formats are .mp4, .mov and .avi.</p>
	Video any
	// <p>Information about a video that Amazon Rekognition analyzed. <code>Videometadata</code> is returned in every page of paginated responses from a Amazon Rekognition video operation.</p>
	VideoMetadata any
}

var PersonTracking = ubx.DataSourceBinding{
	WireType: "aws_rekognition_person_tracking",
	Fields: ubx.FieldMap{
		"JobId": ubx.FieldSpec{WireName: "job_id"},
		"MaxResults": ubx.FieldSpec{WireName: "max_results"},
		"NextToken": ubx.FieldSpec{WireName: "next_token"},
		"SortBy": ubx.FieldSpec{WireName: "sort_by"},
	},
}
