// Code generated by `ubx sdk gen` from aws_lake_formation_tag. DO NOT EDIT.
package lake

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FormationTagConfig struct {
	CatalogId any
	TagKey any
	TagValues any
}

type FormationTagAttrs struct {
	CatalogId any
	TagKey any
	TagValues any
}

var FormationTag = ubx.ResourceBinding{
	WireType: "aws_lake_formation_tag",
	Fields: ubx.FieldMap{
		"CatalogId": ubx.FieldSpec{WireName: "catalog_id"},
		"TagKey": ubx.FieldSpec{WireName: "tag_key"},
		"TagValues": ubx.FieldSpec{WireName: "tag_values"},
	},
}
