# Code generated by `ubx sdk gen` from aws_datasync_location_object_storage. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LocationObjectStorageConfig:
    access_key: Any = None
    agent_arns: Any = None
    bucket_name: Any = None
    id: Any = None
    region: Any = None
    secret_key: Any = None
    server_certificate: Any = None
    server_hostname: Any = None
    server_port: Any = None
    server_protocol: Any = None
    subdirectory: Any = None
    tags: Any = None
    tags_all: Any = None

LocationObjectStorage = ubx.ResourceBinding(
    wire_type="aws_datasync_location_object_storage",
    fields={
        "access_key": ubx.FieldSpec(wire_name="access_key"),
        "agent_arns": ubx.FieldSpec(wire_name="agent_arns"),
        "bucket_name": ubx.FieldSpec(wire_name="bucket_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "region": ubx.FieldSpec(wire_name="region"),
        "secret_key": ubx.FieldSpec(wire_name="secret_key"),
        "server_certificate": ubx.FieldSpec(wire_name="server_certificate"),
        "server_hostname": ubx.FieldSpec(wire_name="server_hostname"),
        "server_port": ubx.FieldSpec(wire_name="server_port"),
        "server_protocol": ubx.FieldSpec(wire_name="server_protocol"),
        "subdirectory": ubx.FieldSpec(wire_name="subdirectory"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
    },
)
