# Code generated by `ubx sdk gen` from aws_cloudformation_generated_template. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GeneratedTemplate_Progress:
    resources_failed: Any = None
    resources_pending: Any = None
    resources_processing: Any = None
    resources_succeeded: Any = None

@dataclasses.dataclass
class GeneratedTemplate_Resources_Warnings_Properties:
    description: Any = None
    property_path: Any = None
    required: Any = None

@dataclasses.dataclass
class GeneratedTemplate_Resources_Warnings:
    properties: Any = None
    type: Any = None

@dataclasses.dataclass
class GeneratedTemplate_Resources:
    logical_resource_id: Any = None
    resource_identifier: Any = None
    resource_status: Any = None
    resource_status_reason: Any = None
    resource_type: Any = None
    warnings: Any = None

@dataclasses.dataclass
class GeneratedTemplate_TemplateConfiguration:
    deletion_policy: Any = None
    update_replace_policy: Any = None

@dataclasses.dataclass
class GeneratedTemplateConfig:
    generated_template_name: Any = None

@dataclasses.dataclass
class GeneratedTemplateAttrs:
    creation_time: Any = None
    generated_template_id: Any = None
    generated_template_name: Any = None
    last_updated_time: Any = None
    # <p>A summary of the progress of the template generation.</p>
    progress: Any = None
    resources: Any = None
    stack_id: Any = None
    status: Any = None
    status_reason: Any = None
    # <p>The configuration details of a generated template.</p>
    template_configuration: Any = None
    total_warnings: Any = None

GeneratedTemplate = ubx.DataSourceBinding(
    wire_type="aws_cloudformation_generated_template",
    fields={
        "generated_template_name": ubx.FieldSpec(wire_name="generated_template_name"),
    },
)
