# Code generated by `ubx sdk gen` from aws_cloudformation_stack_resources. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StackResources_StackResources_DriftInformation:
    last_check_timestamp: Any = None
    stack_resource_drift_status: Any = None

@dataclasses.dataclass
class StackResources_StackResources_ModuleInfo:
    logical_id_hierarchy: Any = None
    type_hierarchy: Any = None

@dataclasses.dataclass
class StackResources_StackResources:
    description: Any = None
    drift_information: Any = None
    logical_resource_id: Any = None
    module_info: Any = None
    physical_resource_id: Any = None
    resource_status: Any = None
    resource_status_reason: Any = None
    resource_type: Any = None
    stack_id: Any = None
    stack_name: Any = None
    timestamp: Any = None

@dataclasses.dataclass
class StackResourcesConfig:
    logical_resource_id: Any = None
    physical_resource_id: Any = None
    stack_name: Any = None

@dataclasses.dataclass
class StackResourcesAttrs:
    logical_resource_id: Any = None
    physical_resource_id: Any = None
    stack_name: Any = None
    stack_resources: Any = None

StackResources = ubx.DataSourceBinding(
    wire_type="aws_cloudformation_stack_resources",
    fields={
        "logical_resource_id": ubx.FieldSpec(wire_name="logical_resource_id"),
        "physical_resource_id": ubx.FieldSpec(wire_name="physical_resource_id"),
        "stack_name": ubx.FieldSpec(wire_name="stack_name"),
    },
)
