# Code generated by `ubx sdk gen` from aws_media_live_event_bridge_rule_template_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LiveEventBridgeRuleTemplateGroupConfig:
    # A resource's optional description.
    description: Any = None
    # A resource's name. Names must be unique within the scope of a resource type in a specific region.
    name: Any = None
    # Represents the tags associated with a resource.
    tags: Any = None

@dataclasses.dataclass
class LiveEventBridgeRuleTemplateGroupAttrs:
    # An eventbridge rule template group's ARN (Amazon Resource Name)
    arn: Any = None
    created_at: Any = None
    # A resource's optional description.
    description: Any = None
    # An eventbridge rule template group's id. AWS provided template groups have ids that start with `aws-`
    id: Any = None
    identifier: Any = None
    modified_at: Any = None
    # A resource's name. Names must be unique within the scope of a resource type in a specific region.
    name: Any = None
    # Represents the tags associated with a resource.
    tags: Any = None

LiveEventBridgeRuleTemplateGroup = ubx.ResourceBinding(
    wire_type="aws_media_live_event_bridge_rule_template_group",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "name": ubx.FieldSpec(wire_name="name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
    },
)
