// Code generated by `ubx sdk gen` from aws_uxc_account_customizations. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccountCustomizationsConfig {
  accountColor?: string | Computed<string>;
  visibleRegions?: string[] | Computed<string[]>;
  visibleServices?: string[] | Computed<string[]>;
}

export interface AccountCustomizationsAttrs {
  accountColor: string;
  visibleRegions: string[];
  visibleServices: string[];
}

export const AccountCustomizations: ResourceBinding<AccountCustomizationsConfig, AccountCustomizationsAttrs> = {
  wireType: "aws_uxc_account_customizations",
  fields: {
    accountColor: "account_color",
    visibleRegions: "visible_regions",
    visibleServices: "visible_services",
  },
};
