// Code generated by `ubx sdk gen` from aws_sfn_activity. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Activity_EncryptionConfiguration {
  kmsDataKeyReusePeriodSeconds: number;
  kmsKeyId: string;
  type: string;
}

const Activity_EncryptionConfigurationFields: FieldMap = {
  kmsDataKeyReusePeriodSeconds: "kms_data_key_reuse_period_seconds",
  kmsKeyId: "kms_key_id",
  type: "type",
};

export interface ActivityConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  region?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tagsAll?: Record<string, string> | Computed<Record<string, string>>;
  encryptionConfiguration?: Activity_EncryptionConfiguration[] | Computed<Activity_EncryptionConfiguration[]>;
}

export interface ActivityAttrs {
  arn: string;
  creationDate: string;
  id: string;
  name: string;
  region: string;
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  encryptionConfiguration: Activity_EncryptionConfiguration[];
}

export const Activity: ResourceBinding<ActivityConfig, ActivityAttrs> = {
  wireType: "aws_sfn_activity",
  fields: {
    id: "id",
    name: "name",
    region: "region",
    tags: "tags",
    tagsAll: "tags_all",
    encryptionConfiguration: {
      wireName: "encryption_configuration",
      kind: "list",
      fields: Activity_EncryptionConfigurationFields,
    },
  },
};
