// Code generated by `ubx sdk gen` from aws_network_acl. DO NOT EDIT.
package network

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Acl_Tags struct {
	// The key of a tag attached to the network ACL, used to label and organize the resource for identification and management within AWS. (AI-inferred)
	Key any
	// The value portion of a key-value tag applied to the network ACL, used to assign metadata such as purpose or ownership to the ACL. (AI-inferred)
	Value any
}

var Acl_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type AclConfig struct {
	// The tags for the network ACL.
	Tags any
	// The ID of the VPC for the network ACL.
	VpcId any
}

type AclAttrs struct {
	// The AWS-assigned identifier for the network ACL, which uses the format acl-xxxxxxxx. (AI-inferred)
	Id any
	// The tags for the network ACL.
	Tags any
	// The ID of the VPC for the network ACL.
	VpcId any
}

var Acl = ubx.ResourceBinding{
	WireType: "aws_network_acl",
	Fields: ubx.FieldMap{
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: Acl_TagsFields,
		},
		"VpcId": ubx.FieldSpec{WireName: "vpc_id"},
	},
}
