# Code generated by `ubx sdk gen` from aws_email_active_receipt_rule_set. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ActiveReceiptRuleSet_Metadata:
    created_timestamp: Any = None
    name: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_AddHeaderAction:
    header_name: Any = None
    header_value: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_BounceAction:
    message: Any = None
    sender: Any = None
    smtp_reply_code: Any = None
    status_code: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_ConnectAction:
    iamrole_arn: Any = None
    instance_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_LambdaAction:
    function_arn: Any = None
    invocation_type: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_S3Action:
    bucket_name: Any = None
    iam_role_arn: Any = None
    kms_key_arn: Any = None
    object_key_prefix: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_Snsaction:
    encoding: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_StopAction:
    scope: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions_WorkmailAction:
    organization_arn: Any = None
    topic_arn: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules_Actions:
    add_header_action: Any = None
    bounce_action: Any = None
    connect_action: Any = None
    lambda_action: Any = None
    s3_action: Any = None
    snsaction: Any = None
    stop_action: Any = None
    workmail_action: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSet_Rules:
    actions: Any = None
    enabled: Any = None
    name: Any = None
    recipients: Any = None
    scan_enabled: Any = None
    tls_policy: Any = None

@dataclasses.dataclass
class ActiveReceiptRuleSetConfig:
    pass

@dataclasses.dataclass
class ActiveReceiptRuleSetAttrs:
    # <p>Information about a receipt rule set.</p> <p>A receipt rule set is a collection of rules that specify what Amazon SES should do with mail it receives on behalf of your account's verified domains.</p> <p>For information about setting up receipt rule sets, see the <a href="https://docs.aws.amazon.com/ses/latest/dg/receiving-email-concepts.html#receiving-email-concepts-rules">Amazon SES Developer Guide</a>.</p>
    metadata: Any = None
    rules: Any = None

ActiveReceiptRuleSet = ubx.DataSourceBinding(
    wire_type="aws_email_active_receipt_rule_set",
    fields={
    },
)
