// Code generated by `ubx sdk gen` from aws_ec2_traffic_mirror_filter. DO NOT EDIT.
package ec2

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TrafficMirrorFilterConfig struct {
	Description any
	Id any
	NetworkServices any
	Region any
	Tags any
	TagsAll any
}

var TrafficMirrorFilter = ubx.ResourceBinding{
	WireType: "aws_ec2_traffic_mirror_filter",
	Fields: ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"NetworkServices": ubx.FieldSpec{WireName: "network_services"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"TagsAll": ubx.FieldSpec{WireName: "tags_all"},
	},
}
