// Code generated by `ubx sdk gen` from aws_guard_duty_publishing_destination. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PublishingDestination_DestinationProperties {
  /** The ARN of the resource to publish to. */
  destinationArn?: string | Computed<string>;
  /** The ARN of the KMS key to use for encryption. */
  kmsKeyArn?: string | Computed<string>;
}

export interface PublishingDestination_Tags {
  /** The key of a tag assigned to the GuardDuty publishing destination, used to organize and identify the resource. (AI-inferred) */
  key?: string | Computed<string>;
  /** The value portion of a user-defined tag that is associated with the GuardDuty publishing destination, used for resource organization, cost tracking, and management. (AI-inferred) */
  value?: string | Computed<string>;
}

const PublishingDestination_DestinationPropertiesFields: FieldMap = {
  destinationArn: "destination_arn",
  kmsKeyArn: "kms_key_arn",
};

const PublishingDestination_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface PublishingDestinationConfig {
  /** Configures the GuardDuty publishing destination by specifying the ARN of the Amazon S3 bucket to receive findings and the ARN of the AWS KMS key used to encrypt those findings. (AI-inferred) */
  destinationProperties: PublishingDestination_DestinationProperties | Computed<PublishingDestination_DestinationProperties>;
  /** The type of resource for the publishing destination. Currently only Amazon S3 buckets are supported. */
  destinationType: string | Computed<string>;
  /** The ID of the GuardDuty detector associated with the publishing destination. */
  detectorId: string | Computed<string>;
  /** A list of key-value tags to attach to the GuardDuty publishing destination for organizing and identifying the resource. (AI-inferred) */
  tags?: PublishingDestination_Tags[] | Computed<PublishingDestination_Tags[]>;
}

export interface PublishingDestinationAttrs {
  /** Configures the GuardDuty publishing destination by specifying the ARN of the Amazon S3 bucket to receive findings and the ARN of the AWS KMS key used to encrypt those findings. (AI-inferred) */
  destinationProperties: PublishingDestination_DestinationProperties;
  /** The type of resource for the publishing destination. Currently only Amazon S3 buckets are supported. */
  destinationType: string;
  /** The ID of the GuardDuty detector associated with the publishing destination. */
  detectorId: string;
  /** The ID of the publishing destination. */
  id: string;
  /** The time, in epoch millisecond format, at which GuardDuty was first unable to publish findings to the destination. */
  publishingFailureStartTimestamp: string;
  /** The status of the publishing destination. */
  status: string;
  /** A list of key-value tags to attach to the GuardDuty publishing destination for organizing and identifying the resource. (AI-inferred) */
  tags: PublishingDestination_Tags[];
}

export const PublishingDestination: ResourceBinding<PublishingDestinationConfig, PublishingDestinationAttrs> = {
  wireType: "aws_guard_duty_publishing_destination",
  fields: {
    destinationProperties: {
      wireName: "destination_properties",
      kind: "object",
      fields: PublishingDestination_DestinationPropertiesFields,
    },
    destinationType: "destination_type",
    detectorId: "detector_id",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: PublishingDestination_TagsFields,
    },
  },
};
