# Code generated by `ubx sdk gen` from aws_agreement_marketplace_agreement_payment_requests. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AgreementMarketplaceAgreementPaymentRequests_Items:
    agreement_id: Any = None
    charge_amount: Any = None
    charge_id: Any = None
    created_at: Any = None
    currency_code: Any = None
    name: Any = None
    payment_request_id: Any = None
    status: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class AgreementMarketplaceAgreementPaymentRequestsConfig:
    agreement_id: Any = None
    agreement_type: Any = None
    catalog: Any = None
    max_results: Any = None
    next_token: Any = None
    party_type: Any = None
    status: Any = None

@dataclasses.dataclass
class AgreementMarketplaceAgreementPaymentRequestsAttrs:
    agreement_id: Any = None
    agreement_type: Any = None
    catalog: Any = None
    items: Any = None
    max_results: Any = None
    next_token: Any = None
    party_type: Any = None
    status: Any = None

AgreementMarketplaceAgreementPaymentRequests = ubx.DataSourceBinding(
    wire_type="aws_agreement_marketplace_agreement_payment_requests",
    fields={
        "agreement_id": ubx.FieldSpec(wire_name="agreement_id"),
        "agreement_type": ubx.FieldSpec(wire_name="agreement_type"),
        "catalog": ubx.FieldSpec(wire_name="catalog"),
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
        "party_type": ubx.FieldSpec(wire_name="party_type"),
        "status": ubx.FieldSpec(wire_name="status"),
    },
)
