// Code generated by `ubx sdk gen` from aws_route53resolver_resolver_query_log_config_policy. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ResolverQueryLogConfigPolicyConfig {
  arn: string | Computed<string>;
}

export interface ResolverQueryLogConfigPolicyAttrs {
  arn: string;
  resolverQueryLogConfigPolicy: string;
}

export const ResolverQueryLogConfigPolicy: DataSourceBinding<ResolverQueryLogConfigPolicyConfig, ResolverQueryLogConfigPolicyAttrs> = {
  wireType: "aws_route53resolver_resolver_query_log_config_policy",
  fields: {
    arn: "arn",
  },
};
