// Code generated by `ubx sdk gen` from aws_ssm_deployable_patch_snapshot_for_instance. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup_PatchFilters {
  key?: string | Computed<string>;
  values?: string[] | Computed<string[]>;
}

export interface DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup {
  patchFilters?: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup_PatchFilters[] | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup_PatchFilters[]>;
}

export interface DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules {
  approveAfterDays?: number | Computed<number>;
  approveUntilDate?: string | Computed<string>;
  complianceLevel?: string | Computed<string>;
  enableNonSecurity?: boolean | Computed<boolean>;
  patchFilterGroup?: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup>;
}

export interface DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules {
  patchRules: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules[] | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules[]>;
}

export interface DeployablePatchSnapshotForInstance_BaselineOverride_Sources {
  configuration?: string | Computed<string>;
  name?: string | Computed<string>;
  products?: string[] | Computed<string[]>;
}

export interface DeployablePatchSnapshotForInstance_BaselineOverride {
  /** <p>A set of rules defining the approval rules for a patch baseline.</p> */
  approvalRules?: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules>;
  approvedPatches?: string[] | Computed<string[]>;
  approvedPatchesComplianceLevel?: string | Computed<string>;
  approvedPatchesEnableNonSecurity?: boolean | Computed<boolean>;
  availableSecurityUpdatesComplianceStatus?: string | Computed<string>;
  /** <p>A set of patch filters, typically used for approval rules.</p> */
  globalFilters?: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup>;
  operatingSystem?: string | Computed<string>;
  rejectedPatches?: string[] | Computed<string[]>;
  rejectedPatchesAction?: string | Computed<string>;
  sources?: DeployablePatchSnapshotForInstance_BaselineOverride_Sources[] | Computed<DeployablePatchSnapshotForInstance_BaselineOverride_Sources[]>;
}

const DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup_PatchFiltersFields: FieldMap = {
  key: "key",
  values: "values",
};

const DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroupFields: FieldMap = {
  patchFilters: {
    wireName: "patch_filters",
    kind: "list",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroup_PatchFiltersFields,
  },
};

const DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRulesFields: FieldMap = {
  approveAfterDays: "approve_after_days",
  approveUntilDate: "approve_until_date",
  complianceLevel: "compliance_level",
  enableNonSecurity: "enable_non_security",
  patchFilterGroup: {
    wireName: "patch_filter_group",
    kind: "object",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroupFields,
  },
};

const DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRulesFields: FieldMap = {
  patchRules: {
    wireName: "patch_rules",
    kind: "list",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRulesFields,
  },
};

const DeployablePatchSnapshotForInstance_BaselineOverride_SourcesFields: FieldMap = {
  configuration: "configuration",
  name: "name",
  products: "products",
};

const DeployablePatchSnapshotForInstance_BaselineOverrideFields: FieldMap = {
  approvalRules: {
    wireName: "approval_rules",
    kind: "object",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRulesFields,
  },
  approvedPatches: "approved_patches",
  approvedPatchesComplianceLevel: "approved_patches_compliance_level",
  approvedPatchesEnableNonSecurity: "approved_patches_enable_non_security",
  availableSecurityUpdatesComplianceStatus: "available_security_updates_compliance_status",
  globalFilters: {
    wireName: "global_filters",
    kind: "object",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_ApprovalRules_PatchRules_PatchFilterGroupFields,
  },
  operatingSystem: "operating_system",
  rejectedPatches: "rejected_patches",
  rejectedPatchesAction: "rejected_patches_action",
  sources: {
    wireName: "sources",
    kind: "list",
    fields: DeployablePatchSnapshotForInstance_BaselineOverride_SourcesFields,
  },
};

export interface DeployablePatchSnapshotForInstanceConfig {
  /** <p>Defines the basic information about a patch baseline override.</p> */
  baselineOverride?: DeployablePatchSnapshotForInstance_BaselineOverride | Computed<DeployablePatchSnapshotForInstance_BaselineOverride>;
  instanceId: string | Computed<string>;
  snapshotId: string | Computed<string>;
  useS3DualStackEndpoint?: boolean | Computed<boolean>;
}

export interface DeployablePatchSnapshotForInstanceAttrs {
  /** <p>Defines the basic information about a patch baseline override.</p> */
  baselineOverride: DeployablePatchSnapshotForInstance_BaselineOverride;
  instanceId: string;
  product: string;
  snapshotDownloadUrl: string;
  snapshotId: string;
  useS3DualStackEndpoint: boolean;
}

export const DeployablePatchSnapshotForInstance: DataSourceBinding<DeployablePatchSnapshotForInstanceConfig, DeployablePatchSnapshotForInstanceAttrs> = {
  wireType: "aws_ssm_deployable_patch_snapshot_for_instance",
  fields: {
    baselineOverride: {
      wireName: "baseline_override",
      kind: "object",
      fields: DeployablePatchSnapshotForInstance_BaselineOverrideFields,
    },
    instanceId: "instance_id",
    snapshotId: "snapshot_id",
    useS3DualStackEndpoint: "use_s3_dual_stack_endpoint",
  },
};
