# Code generated by `ubx sdk gen` from aws_s3_control_access_points_for_directory_buckets. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class S3ControlAccessPointsForDirectoryBuckets_AccessPointList_VpcConfiguration:
    vpc_id: Any = None

@dataclasses.dataclass
class S3ControlAccessPointsForDirectoryBuckets_AccessPointList:
    access_point_arn: Any = None
    alias: Any = None
    bucket: Any = None
    bucket_account_id: Any = None
    data_source_id: Any = None
    data_source_type: Any = None
    name: Any = None
    network_origin: Any = None
    vpc_configuration: Any = None

@dataclasses.dataclass
class S3ControlAccessPointsForDirectoryBucketsConfig:
    account_id: Any = None
    directory_bucket: Any = None
    max_results: Any = None
    next_token: Any = None

@dataclasses.dataclass
class S3ControlAccessPointsForDirectoryBucketsAttrs:
    access_point_list: Any = None
    account_id: Any = None
    directory_bucket: Any = None
    max_results: Any = None
    next_token: Any = None

S3ControlAccessPointsForDirectoryBuckets = ubx.DataSourceBinding(
    wire_type="aws_s3_control_access_points_for_directory_buckets",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "directory_bucket": ubx.FieldSpec(wire_name="directory_bucket"),
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
    },
)
