# Code generated by `ubx sdk gen` from aws_bedrock_foundation_model_agreement. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FoundationModelAgreement_Timeouts:
    create: Any = None
    delete: Any = None

_FoundationModelAgreement_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
}

@dataclasses.dataclass
class FoundationModelAgreementConfig:
    model_id: Any = None
    offer_token: Any = None
    region: Any = None
    timeouts: Any = None

FoundationModelAgreement = ubx.ResourceBinding(
    wire_type="aws_bedrock_foundation_model_agreement",
    fields={
        "model_id": ubx.FieldSpec(wire_name="model_id"),
        "offer_token": ubx.FieldSpec(wire_name="offer_token"),
        "region": ubx.FieldSpec(wire_name="region"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FoundationModelAgreement_TimeoutsFields,
        ),
    },
)
