# Code generated by `ubx sdk gen` from aws_bedrock_model_invocation_logging_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfig_LargeDataDeliveryS3Config:
    bucket_name: Any = None
    key_prefix: Any = None

@dataclasses.dataclass
class ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfig:
    log_group_name: Any = None
    role_arn: Any = None
    large_data_delivery_s3_config: Any = None

@dataclasses.dataclass
class ModelInvocationLoggingConfiguration_LoggingConfig:
    embedding_data_delivery_enabled: Any = None
    image_data_delivery_enabled: Any = None
    text_data_delivery_enabled: Any = None
    video_data_delivery_enabled: Any = None
    cloudwatch_config: Any = None
    s3_config: Any = None

_ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfig_LargeDataDeliveryS3ConfigFields = {
    "bucket_name": ubx.FieldSpec(wire_name="bucket_name"),
    "key_prefix": ubx.FieldSpec(wire_name="key_prefix"),
}

_ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfigFields = {
    "log_group_name": ubx.FieldSpec(wire_name="log_group_name"),
    "role_arn": ubx.FieldSpec(wire_name="role_arn"),
    "large_data_delivery_s3_config": ubx.FieldSpec(
        wire_name="large_data_delivery_s3_config",
        kind="list",
        fields=_ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfig_LargeDataDeliveryS3ConfigFields,
    ),
}

_ModelInvocationLoggingConfiguration_LoggingConfigFields = {
    "embedding_data_delivery_enabled": ubx.FieldSpec(wire_name="embedding_data_delivery_enabled"),
    "image_data_delivery_enabled": ubx.FieldSpec(wire_name="image_data_delivery_enabled"),
    "text_data_delivery_enabled": ubx.FieldSpec(wire_name="text_data_delivery_enabled"),
    "video_data_delivery_enabled": ubx.FieldSpec(wire_name="video_data_delivery_enabled"),
    "cloudwatch_config": ubx.FieldSpec(
        wire_name="cloudwatch_config",
        kind="list",
        fields=_ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfigFields,
    ),
    "s3_config": ubx.FieldSpec(
        wire_name="s3_config",
        kind="list",
        fields=_ModelInvocationLoggingConfiguration_LoggingConfig_CloudwatchConfig_LargeDataDeliveryS3ConfigFields,
    ),
}

@dataclasses.dataclass
class ModelInvocationLoggingConfigurationConfig:
    region: Any = None
    logging_config: Any = None

ModelInvocationLoggingConfiguration = ubx.ResourceBinding(
    wire_type="aws_bedrock_model_invocation_logging_configuration",
    fields={
        "region": ubx.FieldSpec(wire_name="region"),
        "logging_config": ubx.FieldSpec(
            wire_name="logging_config",
            kind="list",
            fields=_ModelInvocationLoggingConfiguration_LoggingConfigFields,
        ),
    },
)
