// Code generated by `ubx sdk gen` from aws_medialive_event_bridge_rule_templates. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface EventBridgeRuleTemplates_EventBridgeRuleTemplates {
  arn?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  eventTargetCount?: number | Computed<number>;
  eventType?: string | Computed<string>;
  groupId?: string | Computed<string>;
  id?: string | Computed<string>;
  modifiedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface EventBridgeRuleTemplatesConfig {
  /** Placeholder documentation for __string */
  groupIdentifier?: string | Computed<string>;
  /** Placeholder documentation for MaxResults */
  maxResults?: number | Computed<number>;
  /** Placeholder documentation for __string */
  nextToken?: string | Computed<string>;
  /** Placeholder documentation for __string */
  signalMapIdentifier?: string | Computed<string>;
}

export interface EventBridgeRuleTemplatesAttrs {
  /** Placeholder documentation for __listOfEventBridgeRuleTemplateSummary */
  eventBridgeRuleTemplates: EventBridgeRuleTemplates_EventBridgeRuleTemplates[];
  /** Placeholder documentation for __string */
  groupIdentifier: string;
  /** Placeholder documentation for MaxResults */
  maxResults: number;
  /** Placeholder documentation for __string */
  nextToken: string;
  /** Placeholder documentation for __string */
  signalMapIdentifier: string;
}

export const EventBridgeRuleTemplates: DataSourceBinding<EventBridgeRuleTemplatesConfig, EventBridgeRuleTemplatesAttrs> = {
  wireType: "aws_medialive_event_bridge_rule_templates",
  fields: {
    groupIdentifier: "group_identifier",
    maxResults: "max_results",
    nextToken: "next_token",
    signalMapIdentifier: "signal_map_identifier",
  },
};
