// Code generated by `ubx sdk gen` from aws_inspector2_member. DO NOT EDIT.
package inspector2

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Member_Member struct {
	AccountId any
	DelegatedAdminAccountId any
	RelationshipStatus any
	UpdatedAt any
}

type MemberConfig struct {
	AccountId any
}

type MemberAttrs struct {
	AccountId any
	// <p>Details on a member account in your organization.</p>
	Member any
}

var Member = ubx.DataSourceBinding{
	WireType: "aws_inspector2_member",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
