// Code generated by `ubx sdk gen` from aws_mediastore_tags_for_resource. DO NOT EDIT.
package mediastore

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TagsForResource_Tags struct {
	Key any
	Value any
}

type TagsForResourceConfig struct {
	Resource any
}

type TagsForResourceAttrs struct {
	Resource any
	Tags any
}

var TagsForResource = ubx.DataSourceBinding{
	WireType: "aws_mediastore_tags_for_resource",
	Fields: ubx.FieldMap{
		"Resource": ubx.FieldSpec{WireName: "resource"},
	},
}
