// Code generated by `ubx sdk gen` from aws_comprehend_document_classifier. DO NOT EDIT.
package comprehend

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DocumentClassifier_InputDataConfig_AugmentedManifests struct {
	AttributeNames any
	S3Uri any
	Split any
}

type DocumentClassifier_InputDataConfig_DocumentReaderConfig struct {
	DocumentReadAction any
	DocumentReadMode any
	FeatureTypes any
}

type DocumentClassifier_InputDataConfig_Documents struct {
	S3Uri any
	TestS3Uri any
}

type DocumentClassifier_InputDataConfig struct {
	AugmentedManifests any
	DataFormat any
	DocumentReaderConfig any
	DocumentType any
	Documents any
	LabelDelimiter any
	S3Uri any
	TestS3Uri any
}

type DocumentClassifier_OutputDataConfig struct {
	KmsKeyId any
	S3Uri any
}

type DocumentClassifier_Tags struct {
	Key any
	Value any
}

type DocumentClassifier_VpcConfig struct {
	SecurityGroupIds any
	Subnets any
}

var DocumentClassifier_InputDataConfig_AugmentedManifestsFields = ubx.FieldMap{
		"AttributeNames": ubx.FieldSpec{WireName: "attribute_names"},
		"S3Uri": ubx.FieldSpec{WireName: "s3_uri"},
		"Split": ubx.FieldSpec{WireName: "split"},
	}

var DocumentClassifier_InputDataConfig_DocumentReaderConfigFields = ubx.FieldMap{
		"DocumentReadAction": ubx.FieldSpec{WireName: "document_read_action"},
		"DocumentReadMode": ubx.FieldSpec{WireName: "document_read_mode"},
		"FeatureTypes": ubx.FieldSpec{WireName: "feature_types"},
	}

var DocumentClassifier_InputDataConfig_DocumentsFields = ubx.FieldMap{
		"S3Uri": ubx.FieldSpec{WireName: "s3_uri"},
		"TestS3Uri": ubx.FieldSpec{WireName: "test_s3_uri"},
	}

var DocumentClassifier_InputDataConfigFields = ubx.FieldMap{
		"AugmentedManifests": ubx.FieldSpec{
			WireName: "augmented_manifests",
			Kind: "list",
			Fields: DocumentClassifier_InputDataConfig_AugmentedManifestsFields,
		},
		"DataFormat": ubx.FieldSpec{WireName: "data_format"},
		"DocumentReaderConfig": ubx.FieldSpec{
			WireName: "document_reader_config",
			Kind: "object",
			Fields: DocumentClassifier_InputDataConfig_DocumentReaderConfigFields,
		},
		"DocumentType": ubx.FieldSpec{WireName: "document_type"},
		"Documents": ubx.FieldSpec{
			WireName: "documents",
			Kind: "object",
			Fields: DocumentClassifier_InputDataConfig_DocumentsFields,
		},
		"LabelDelimiter": ubx.FieldSpec{WireName: "label_delimiter"},
		"S3Uri": ubx.FieldSpec{WireName: "s3_uri"},
		"TestS3Uri": ubx.FieldSpec{WireName: "test_s3_uri"},
	}

var DocumentClassifier_OutputDataConfigFields = ubx.FieldMap{
		"KmsKeyId": ubx.FieldSpec{WireName: "kms_key_id"},
		"S3Uri": ubx.FieldSpec{WireName: "s3_uri"},
	}

var DocumentClassifier_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

var DocumentClassifier_VpcConfigFields = ubx.FieldMap{
		"SecurityGroupIds": ubx.FieldSpec{WireName: "security_group_ids"},
		"Subnets": ubx.FieldSpec{WireName: "subnets"},
	}

type DocumentClassifierConfig struct {
	DataAccessRoleArn any
	DocumentClassifierName any
	InputDataConfig any
	LanguageCode any
	Mode any
	ModelKmsKeyId any
	ModelPolicy any
	OutputDataConfig any
	Tags any
	VersionName any
	VolumeKmsKeyId any
	VpcConfig any
}

type DocumentClassifierAttrs struct {
	Arn any
	DataAccessRoleArn any
	DocumentClassifierName any
	InputDataConfig any
	LanguageCode any
	Mode any
	ModelKmsKeyId any
	ModelPolicy any
	OutputDataConfig any
	Tags any
	VersionName any
	VolumeKmsKeyId any
	VpcConfig any
}

var DocumentClassifier = ubx.ResourceBinding{
	WireType: "aws_comprehend_document_classifier",
	Fields: ubx.FieldMap{
		"DataAccessRoleArn": ubx.FieldSpec{WireName: "data_access_role_arn"},
		"DocumentClassifierName": ubx.FieldSpec{WireName: "document_classifier_name"},
		"InputDataConfig": ubx.FieldSpec{
			WireName: "input_data_config",
			Kind: "object",
			Fields: DocumentClassifier_InputDataConfigFields,
		},
		"LanguageCode": ubx.FieldSpec{WireName: "language_code"},
		"Mode": ubx.FieldSpec{WireName: "mode"},
		"ModelKmsKeyId": ubx.FieldSpec{WireName: "model_kms_key_id"},
		"ModelPolicy": ubx.FieldSpec{WireName: "model_policy"},
		"OutputDataConfig": ubx.FieldSpec{
			WireName: "output_data_config",
			Kind: "object",
			Fields: DocumentClassifier_OutputDataConfigFields,
		},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: DocumentClassifier_TagsFields,
		},
		"VersionName": ubx.FieldSpec{WireName: "version_name"},
		"VolumeKmsKeyId": ubx.FieldSpec{WireName: "volume_kms_key_id"},
		"VpcConfig": ubx.FieldSpec{
			WireName: "vpc_config",
			Kind: "object",
			Fields: DocumentClassifier_VpcConfigFields,
		},
	},
}
