// Code generated by `ubx sdk gen` from aws_organizations_accounts_for_parent. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccountsForParent_Accounts {
  arn?: string | Computed<string>;
  email?: string | Computed<string>;
  id?: string | Computed<string>;
  joinedMethod?: string | Computed<string>;
  joinedTimestamp?: string | Computed<string>;
  name?: string | Computed<string>;
  paths?: string[] | Computed<string[]>;
  state?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface AccountsForParentConfig {
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  parentId: string | Computed<string>;
}

export interface AccountsForParentAttrs {
  accounts: AccountsForParent_Accounts[];
  maxResults: number;
  nextToken: string;
  parentId: string;
}

export const AccountsForParent: DataSourceBinding<AccountsForParentConfig, AccountsForParentAttrs> = {
  wireType: "aws_organizations_accounts_for_parent",
  fields: {
    maxResults: "max_results",
    nextToken: "next_token",
    parentId: "parent_id",
  },
};
