// Code generated by `ubx sdk gen` from aws_organizations_delegated_administrators. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DelegatedAdministrators_DelegatedAdministrators {
  arn?: string | Computed<string>;
  delegationEnabledDate?: string | Computed<string>;
  email?: string | Computed<string>;
  id?: string | Computed<string>;
  joinedMethod?: string | Computed<string>;
  joinedTimestamp?: string | Computed<string>;
  name?: string | Computed<string>;
  state?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface DelegatedAdministratorsConfig {
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  servicePrincipal?: string | Computed<string>;
}

export interface DelegatedAdministratorsAttrs {
  delegatedAdministrators: DelegatedAdministrators_DelegatedAdministrators[];
  maxResults: number;
  nextToken: string;
  servicePrincipal: string;
}

export const DelegatedAdministrators: DataSourceBinding<DelegatedAdministratorsConfig, DelegatedAdministratorsAttrs> = {
  wireType: "aws_organizations_delegated_administrators",
  fields: {
    maxResults: "max_results",
    nextToken: "next_token",
    servicePrincipal: "service_principal",
  },
};
