// Code generated by `ubx sdk gen` from aws_organizations_inbound_responsibility_transfers. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface InboundResponsibilityTransfers_ResponsibilityTransfers_Source {
  managementAccountEmail?: string | Computed<string>;
  managementAccountId?: string | Computed<string>;
}

export interface InboundResponsibilityTransfers_ResponsibilityTransfers {
  activeHandshakeId?: string | Computed<string>;
  arn?: string | Computed<string>;
  endTimestamp?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  source?: InboundResponsibilityTransfers_ResponsibilityTransfers_Source | Computed<InboundResponsibilityTransfers_ResponsibilityTransfers_Source>;
  startTimestamp?: string | Computed<string>;
  status?: string | Computed<string>;
  target?: InboundResponsibilityTransfers_ResponsibilityTransfers_Source | Computed<InboundResponsibilityTransfers_ResponsibilityTransfers_Source>;
  type?: string | Computed<string>;
}

export interface InboundResponsibilityTransfersConfig {
  id?: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  type: string | Computed<string>;
}

export interface InboundResponsibilityTransfersAttrs {
  id: string;
  maxResults: number;
  nextToken: string;
  responsibilityTransfers: InboundResponsibilityTransfers_ResponsibilityTransfers[];
  type: string;
}

export const InboundResponsibilityTransfers: DataSourceBinding<InboundResponsibilityTransfersConfig, InboundResponsibilityTransfersAttrs> = {
  wireType: "aws_organizations_inbound_responsibility_transfers",
  fields: {
    id: "id",
    maxResults: "max_results",
    nextToken: "next_token",
    type: "type",
  },
};
