# Code generated by `ubx sdk gen` from aws_iam_users. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Users_Users_PermissionsBoundary:
    permissions_boundary_arn: Any = None
    permissions_boundary_type: Any = None

@dataclasses.dataclass
class Users_Users_Tags:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class Users_Users:
    arn: Any = None
    create_date: Any = None
    password_last_used: Any = None
    path: Any = None
    permissions_boundary: Any = None
    tags: Any = None
    user_id: Any = None
    user_name: Any = None

@dataclasses.dataclass
class UsersConfig:
    marker: Any = None
    max_items: Any = None
    path_prefix: Any = None

@dataclasses.dataclass
class UsersAttrs:
    is_truncated: Any = None
    marker: Any = None
    max_items: Any = None
    path_prefix: Any = None
    # <p>Contains a list of users.</p> <p>This data type is used as a response element in the <a href="https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetGroup.html">GetGroup</a> and <a href="https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUsers.html">ListUsers</a> operations. </p>
    users: Any = None

Users = ubx.DataSourceBinding(
    wire_type="aws_iam_users",
    fields={
        "marker": ubx.FieldSpec(wire_name="marker"),
        "max_items": ubx.FieldSpec(wire_name="max_items"),
        "path_prefix": ubx.FieldSpec(wire_name="path_prefix"),
    },
)
