# Code generated by `ubx sdk gen` from aws_s3_object_tagging. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ObjectTagging_TagSet:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class ObjectTaggingConfig:
    bucket: Any = None
    expected_bucket_owner: Any = None
    key: Any = None
    # <p>Confirms that the requester knows that they will be charged for the request. Bucket owners need not specify this parameter in their requests. If either the source or destination S3 bucket has Requester Pays enabled, the requester will pay for the corresponding charges. For information about downloading objects from Requester Pays buckets, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html">Downloading Objects in Requester Pays Buckets</a> in the <i>Amazon S3 User Guide</i>.</p> <note> <p>This functionality is not supported for directory buckets.</p> </note>
    request_payer: Any = None
    version_id: Any = None

@dataclasses.dataclass
class ObjectTaggingAttrs:
    bucket: Any = None
    expected_bucket_owner: Any = None
    key: Any = None
    # <p>Confirms that the requester knows that they will be charged for the request. Bucket owners need not specify this parameter in their requests. If either the source or destination S3 bucket has Requester Pays enabled, the requester will pay for the corresponding charges. For information about downloading objects from Requester Pays buckets, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html">Downloading Objects in Requester Pays Buckets</a> in the <i>Amazon S3 User Guide</i>.</p> <note> <p>This functionality is not supported for directory buckets.</p> </note>
    request_payer: Any = None
    tag_set: Any = None
    version_id: Any = None

ObjectTagging = ubx.DataSourceBinding(
    wire_type="aws_s3_object_tagging",
    fields={
        "bucket": ubx.FieldSpec(wire_name="bucket"),
        "expected_bucket_owner": ubx.FieldSpec(wire_name="expected_bucket_owner"),
        "key": ubx.FieldSpec(wire_name="key"),
        "request_payer": ubx.FieldSpec(wire_name="request_payer"),
        "version_id": ubx.FieldSpec(wire_name="version_id"),
    },
)
