// Code generated by `ubx sdk gen` from aws_ec2_transit_gateway_multicast_domain_association. DO NOT EDIT.
package ec2

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TransitGatewayMulticastDomainAssociationConfig struct {
	// The IDs of the subnets to associate with the transit gateway multicast domain.
	SubnetId any
	// The ID of the transit gateway attachment.
	TransitGatewayAttachmentId any
	// The ID of the transit gateway multicast domain.
	TransitGatewayMulticastDomainId any
}

type TransitGatewayMulticastDomainAssociationAttrs struct {
	// The ID of the resource.
	ResourceId any
	// The type of resource, for example a VPC attachment.
	ResourceType any
	// The state of the subnet association.
	State any
	// The IDs of the subnets to associate with the transit gateway multicast domain.
	SubnetId any
	// The ID of the transit gateway attachment.
	TransitGatewayAttachmentId any
	// The ID of the transit gateway multicast domain.
	TransitGatewayMulticastDomainId any
}

var TransitGatewayMulticastDomainAssociation = ubx.ResourceBinding{
	WireType: "aws_ec2_transit_gateway_multicast_domain_association",
	Fields: ubx.FieldMap{
		"SubnetId": ubx.FieldSpec{WireName: "subnet_id"},
		"TransitGatewayAttachmentId": ubx.FieldSpec{WireName: "transit_gateway_attachment_id"},
		"TransitGatewayMulticastDomainId": ubx.FieldSpec{WireName: "transit_gateway_multicast_domain_id"},
	},
}
