// Code generated by `ubx sdk gen` from aws_ivsrealtime_stages. DO NOT EDIT.
package ivsrealtime

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Stages_Stages struct {
	ActiveSessionId any
	Arn any
	Name any
	Tags any
}

type StagesConfig struct {
	MaxResults any
	NextToken any
}

type StagesAttrs struct {
	MaxResults any
	NextToken any
	Stages any
}

var Stages = ubx.DataSourceBinding{
	WireType: "aws_ivsrealtime_stages",
	Fields: ubx.FieldMap{
		"MaxResults": ubx.FieldSpec{WireName: "max_results"},
		"NextToken": ubx.FieldSpec{WireName: "next_token"},
	},
}
