# Code generated by `ubx sdk gen` from aws_ec2_local_gateway_route_table. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LocalGatewayRouteTable_Timeouts:
    create: Any = None
    delete: Any = None

_LocalGatewayRouteTable_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
}

@dataclasses.dataclass
class LocalGatewayRouteTableConfig:
    local_gateway_id: Any = None
    mode: Any = None
    region: Any = None
    tags: Any = None
    timeouts: Any = None

LocalGatewayRouteTable = ubx.ResourceBinding(
    wire_type="aws_ec2_local_gateway_route_table",
    fields={
        "local_gateway_id": ubx.FieldSpec(wire_name="local_gateway_id"),
        "mode": ubx.FieldSpec(wire_name="mode"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LocalGatewayRouteTable_TimeoutsFields,
        ),
    },
)
