# Code generated by `ubx sdk gen` from aws_deadline_sessions_statistics_aggregation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SessionsStatisticsAggregation_Statistics_CostInUsd:
    avg: Any = None
    max: Any = None
    min: Any = None
    sum: Any = None

@dataclasses.dataclass
class SessionsStatisticsAggregation_Statistics:
    aggregation_end_time: Any = None
    aggregation_start_time: Any = None
    cost_in_usd: Any = None
    count: Any = None
    fleet_id: Any = None
    instance_type: Any = None
    job_id: Any = None
    job_name: Any = None
    license_product: Any = None
    queue_id: Any = None
    runtime_in_seconds: Any = None
    usage_type: Any = None
    user_id: Any = None

@dataclasses.dataclass
class SessionsStatisticsAggregationConfig:
    aggregation_id: Any = None
    farm_id: Any = None
    max_results: Any = None
    next_token: Any = None

@dataclasses.dataclass
class SessionsStatisticsAggregationAttrs:
    aggregation_id: Any = None
    farm_id: Any = None
    max_results: Any = None
    next_token: Any = None
    statistics: Any = None
    status: Any = None
    status_message: Any = None

SessionsStatisticsAggregation = ubx.DataSourceBinding(
    wire_type="aws_deadline_sessions_statistics_aggregation",
    fields={
        "aggregation_id": ubx.FieldSpec(wire_name="aggregation_id"),
        "farm_id": ubx.FieldSpec(wire_name="farm_id"),
        "max_results": ubx.FieldSpec(wire_name="max_results"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
    },
)
