// Code generated by `ubx sdk gen` from aws_workspacesweb_trust_store. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TrustStore_Certificate {
  body: string;
  issuer: string;
  notValidAfter: string;
  notValidBefore: string;
  subject: string;
  thumbprint: string;
}

const TrustStore_CertificateFields: FieldMap = {
  body: "body",
  issuer: "issuer",
  notValidAfter: "not_valid_after",
  notValidBefore: "not_valid_before",
  subject: "subject",
  thumbprint: "thumbprint",
};

export interface TrustStoreConfig {
  region?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  certificate?: TrustStore_Certificate[] | Computed<TrustStore_Certificate[]>;
}

export interface TrustStoreAttrs {
  associatedPortalArns: string[];
  region: string;
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  trustStoreArn: string;
  certificate: TrustStore_Certificate[];
}

export const TrustStore: ResourceBinding<TrustStoreConfig, TrustStoreAttrs> = {
  wireType: "aws_workspacesweb_trust_store",
  fields: {
    region: "region",
    tags: "tags",
    certificate: {
      wireName: "certificate",
      kind: "set",
      fields: TrustStore_CertificateFields,
    },
  },
};
