// Code generated by `ubx sdk gen` from aws_agreement_marketplace_agreement_terms. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ByolPricingTerm {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration_Dimensions {
  dimensionKey?: string | Computed<string>;
  dimensionValue?: number | Computed<number>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration {
  dimensions?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration_Dimensions[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration_Dimensions[]>;
  selectorValue?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Constraints {
  multipleDimensionSelection?: string | Computed<string>;
  quantityConfiguration?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_RateCard {
  dimensionKey?: string | Computed<string>;
  price?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Selector {
  type?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards {
  constraints?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Constraints | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Constraints>;
  rateCard?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_RateCard[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_RateCard[]>;
  selector?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Selector | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_Selector>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm {
  configuration?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_Configuration>;
  currencyCode?: string | Computed<string>;
  id?: string | Computed<string>;
  rateCards?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards[]>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm_Grants {
  dimensionKey?: string | Computed<string>;
  maxQuantity?: number | Computed<number>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm {
  currencyCode?: string | Computed<string>;
  duration?: string | Computed<string>;
  grants?: AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm_Grants[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm_Grants[]>;
  id?: string | Computed<string>;
  price?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_FreeTrialPricingTerm {
  duration?: string | Computed<string>;
  grants?: AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm_Grants[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm_Grants[]>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm_Documents {
  type?: string | Computed<string>;
  url?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm {
  documents?: AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm_Documents[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm_Documents[]>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_NetPaymentTerm {
  id?: string | Computed<string>;
  paymentDuePeriod?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm_Schedule {
  chargeAmount?: string | Computed<string>;
  chargeDate?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm {
  currencyCode?: string | Computed<string>;
  id?: string | Computed<string>;
  schedule?: AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm_Schedule[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm_Schedule[]>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_RecurringPaymentTerm {
  billingPeriod?: string | Computed<string>;
  currencyCode?: string | Computed<string>;
  id?: string | Computed<string>;
  price?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm_Configuration {
  enableAutoRenew?: boolean | Computed<boolean>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm {
  configuration?: AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm_Configuration | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm_Configuration>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_SupportTerm {
  id?: string | Computed<string>;
  refundPolicy?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm_RateCards {
  rateCard?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_RateCard[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm_RateCards_RateCard[]>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm {
  currencyCode?: string | Computed<string>;
  id?: string | Computed<string>;
  rateCards?: AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm_RateCards[] | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm_RateCards[]>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_ValidityTerm {
  agreementDuration?: string | Computed<string>;
  agreementEndDate?: string | Computed<string>;
  agreementStartDate?: string | Computed<string>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm_Configuration {
  expirationDuration?: string | Computed<string>;
  paymentRequestApprovalStrategy?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm {
  configuration?: AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm_Configuration | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm_Configuration>;
  currencyCode?: string | Computed<string>;
  id?: string | Computed<string>;
  maxTotalChargeAmount?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTerms_AcceptedTerms {
  byolPricingTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ByolPricingTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ByolPricingTerm>;
  configurableUpfrontPricingTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ConfigurableUpfrontPricingTerm>;
  fixedUpfrontPricingTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_FixedUpfrontPricingTerm>;
  freeTrialPricingTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_FreeTrialPricingTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_FreeTrialPricingTerm>;
  legalTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_LegalTerm>;
  netPaymentTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_NetPaymentTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_NetPaymentTerm>;
  paymentScheduleTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_PaymentScheduleTerm>;
  recurringPaymentTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_RecurringPaymentTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_RecurringPaymentTerm>;
  renewalTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_RenewalTerm>;
  supportTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_SupportTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_SupportTerm>;
  usageBasedPricingTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_UsageBasedPricingTerm>;
  validityTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_ValidityTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_ValidityTerm>;
  variablePaymentTerm?: AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm | Computed<AgreementMarketplaceAgreementTerms_AcceptedTerms_VariablePaymentTerm>;
}

export interface AgreementMarketplaceAgreementTermsConfig {
  agreementId: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
}

export interface AgreementMarketplaceAgreementTermsAttrs {
  acceptedTerms: AgreementMarketplaceAgreementTerms_AcceptedTerms[];
  agreementId: string;
  maxResults: number;
  nextToken: string;
}

export const AgreementMarketplaceAgreementTerms: DataSourceBinding<AgreementMarketplaceAgreementTermsConfig, AgreementMarketplaceAgreementTermsAttrs> = {
  wireType: "aws_agreement_marketplace_agreement_terms",
  fields: {
    agreementId: "agreement_id",
    maxResults: "max_results",
    nextToken: "next_token",
  },
};
