# Code generated by `ubx sdk gen` from aws_backup_tiering_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TieringConfiguration_ResourceSelection:
    resource_type: Any = None
    resources: Any = None
    # The number of days after a backup is created that it should be moved to the cold storage tier, controlling the lifecycle transition for the selected resources. (AI-inferred)
    tiering_down_settings_in_days: Any = None

_TieringConfiguration_ResourceSelectionFields = {
    "resource_type": ubx.FieldSpec(wire_name="resource_type"),
    "resources": ubx.FieldSpec(wire_name="resources"),
    "tiering_down_settings_in_days": ubx.FieldSpec(wire_name="tiering_down_settings_in_days"),
}

@dataclasses.dataclass
class TieringConfigurationConfig:
    # The name of the AWS Backup vault to which this tiering configuration is applied. (AI-inferred)
    backup_vault_name: Any = None
    resource_selection: Any = None
    # The name that identifies this tiering configuration, which defines when backups transition to the cold storage tier within an AWS Backup plan. (AI-inferred)
    tiering_configuration_name: Any = None
    tiering_configuration_tags: Any = None

@dataclasses.dataclass
class TieringConfigurationAttrs:
    # The name of the AWS Backup vault to which this tiering configuration is applied. (AI-inferred)
    backup_vault_name: Any = None
    creation_time: Any = None
    # The timestamp of the most recent update to this AWS Backup tiering configuration. (AI-inferred)
    last_updated_time: Any = None
    resource_selection: Any = None
    tiering_configuration_arn: Any = None
    # The name that identifies this tiering configuration, which defines when backups transition to the cold storage tier within an AWS Backup plan. (AI-inferred)
    tiering_configuration_name: Any = None
    tiering_configuration_tags: Any = None

TieringConfiguration = ubx.ResourceBinding(
    wire_type="aws_backup_tiering_configuration",
    fields={
        "backup_vault_name": ubx.FieldSpec(wire_name="backup_vault_name"),
        "resource_selection": ubx.FieldSpec(
            wire_name="resource_selection",
            kind="list",
            fields=_TieringConfiguration_ResourceSelectionFields,
        ),
        "tiering_configuration_name": ubx.FieldSpec(wire_name="tiering_configuration_name"),
        "tiering_configuration_tags": ubx.FieldSpec(wire_name="tiering_configuration_tags"),
    },
)
