// Code generated by `ubx sdk gen` from aws_pinpoint_email_configuration_set. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConfigurationSet_DeliveryOptions {
  /** The name of the dedicated IP pool that Amazon Pinpoint uses to send email for this configuration set. (AI-inferred) */
  sendingPoolName?: string | Computed<string>;
}

export interface ConfigurationSet_ReputationOptions {
  /** Enables or disables the publishing of reputation metrics (such as bounce and complaint rates) for email messages sent using this Pinpoint email configuration set. (AI-inferred) */
  reputationMetricsEnabled?: boolean | Computed<boolean>;
}

export interface ConfigurationSet_SendingOptions {
  /** Enables or disables email sending for the configuration set when set to true or false, respectively. (AI-inferred) */
  sendingEnabled?: boolean | Computed<boolean>;
}

export interface ConfigurationSet_Tags {
  /** The key of a tag attached to the Amazon Pinpoint email configuration set, used to identify and categorize the configuration set for management, cost tracking, and resource organization purposes. (AI-inferred) */
  key?: string | Computed<string>;
  /** The value of an individual tag key on the Amazon Pinpoint email configuration set, used to store metadata for resource identification, organization, and cost allocation. (AI-inferred) */
  value?: string | Computed<string>;
}

export interface ConfigurationSet_TrackingOptions {
  /** Defines the custom domain that Amazon Pinpoint uses to rewrite links in emails for tracking opens and clicks, overriding the default tracking domain. (AI-inferred) */
  customRedirectDomain?: string | Computed<string>;
}

const ConfigurationSet_DeliveryOptionsFields: FieldMap = {
  sendingPoolName: "sending_pool_name",
};

const ConfigurationSet_ReputationOptionsFields: FieldMap = {
  reputationMetricsEnabled: "reputation_metrics_enabled",
};

const ConfigurationSet_SendingOptionsFields: FieldMap = {
  sendingEnabled: "sending_enabled",
};

const ConfigurationSet_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

const ConfigurationSet_TrackingOptionsFields: FieldMap = {
  customRedirectDomain: "custom_redirect_domain",
};

export interface ConfigurationSetConfig {
  /** Configures delivery options for emails sent from this configuration set, including the dedicated IP pool (SendingPoolName) and the TLS policy (TlsPolicy). (AI-inferred) */
  deliveryOptions?: ConfigurationSet_DeliveryOptions | Computed<ConfigurationSet_DeliveryOptions>;
  /** The unique name of the Amazon Pinpoint email configuration set, used as its identifier when you send email or attach event destinations to it. (AI-inferred) */
  name: string | Computed<string>;
  /** Configures reputation metrics tracking for this configuration set, determining whether Amazon Pinpoint publishes email reputation data such as bounce and complaint rates to Amazon CloudWatch. (AI-inferred) */
  reputationOptions?: ConfigurationSet_ReputationOptions | Computed<ConfigurationSet_ReputationOptions>;
  /** Defines the email sending options for the configuration set, specifically whether email sending is enabled via the SendingEnabled sub-property. (AI-inferred) */
  sendingOptions?: ConfigurationSet_SendingOptions | Computed<ConfigurationSet_SendingOptions>;
  /** A list of key-value pairs (Tag objects) to attach to the Amazon Pinpoint email configuration set for identifying, organizing, and managing the resource, including for cost allocation reporting. (AI-inferred) */
  tags?: ConfigurationSet_Tags[] | Computed<ConfigurationSet_Tags[]>;
  /** Specifies the custom redirect domain used for open and click tracking in emails sent using this Pinpoint email configuration set. (AI-inferred) */
  trackingOptions?: ConfigurationSet_TrackingOptions | Computed<ConfigurationSet_TrackingOptions>;
}

export interface ConfigurationSetAttrs {
  /** Configures delivery options for emails sent from this configuration set, including the dedicated IP pool (SendingPoolName) and the TLS policy (TlsPolicy). (AI-inferred) */
  deliveryOptions: ConfigurationSet_DeliveryOptions;
  /** The unique identifier of the configuration set, which corresponds to the configuration set name in Amazon Pinpoint Email. (AI-inferred) */
  id: string;
  /** The unique name of the Amazon Pinpoint email configuration set, used as its identifier when you send email or attach event destinations to it. (AI-inferred) */
  name: string;
  /** Configures reputation metrics tracking for this configuration set, determining whether Amazon Pinpoint publishes email reputation data such as bounce and complaint rates to Amazon CloudWatch. (AI-inferred) */
  reputationOptions: ConfigurationSet_ReputationOptions;
  /** Defines the email sending options for the configuration set, specifically whether email sending is enabled via the SendingEnabled sub-property. (AI-inferred) */
  sendingOptions: ConfigurationSet_SendingOptions;
  /** A list of key-value pairs (Tag objects) to attach to the Amazon Pinpoint email configuration set for identifying, organizing, and managing the resource, including for cost allocation reporting. (AI-inferred) */
  tags: ConfigurationSet_Tags[];
  /** Specifies the custom redirect domain used for open and click tracking in emails sent using this Pinpoint email configuration set. (AI-inferred) */
  trackingOptions: ConfigurationSet_TrackingOptions;
}

export const ConfigurationSet: ResourceBinding<ConfigurationSetConfig, ConfigurationSetAttrs> = {
  wireType: "aws_pinpoint_email_configuration_set",
  fields: {
    deliveryOptions: {
      wireName: "delivery_options",
      kind: "object",
      fields: ConfigurationSet_DeliveryOptionsFields,
    },
    name: "name",
    reputationOptions: {
      wireName: "reputation_options",
      kind: "object",
      fields: ConfigurationSet_ReputationOptionsFields,
    },
    sendingOptions: {
      wireName: "sending_options",
      kind: "object",
      fields: ConfigurationSet_SendingOptionsFields,
    },
    tags: {
      wireName: "tags",
      kind: "list",
      fields: ConfigurationSet_TagsFields,
    },
    trackingOptions: {
      wireName: "tracking_options",
      kind: "object",
      fields: ConfigurationSet_TrackingOptionsFields,
    },
  },
};
