# Code generated by `ubx sdk gen` from aws_event_schemas_discoverer. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Discoverer_Tags:
    # Specifies a tag key to associate with the EventBridge Schema Discoverer, enabling you to categorize, filter, and control access to the resource via resource-level policies or cost allocation tags. (AI-inferred)
    key: Any = None
    # The tag value for the EventBridge Schema Discoverer, paired with a tag key to assign custom metadata such as environment, project, or cost-allocation labels to the discoverer resource. (AI-inferred)
    value: Any = None

_Discoverer_TagsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

@dataclasses.dataclass
class DiscovererConfig:
    # Defines whether event schemas from other accounts are discovered. Default is True.
    cross_account: Any = None
    # A description for the discoverer.
    description: Any = None
    # The ARN of the event bus.
    source_arn: Any = None
    # Tags associated with the resource.
    tags: Any = None

@dataclasses.dataclass
class DiscovererAttrs:
    # Defines whether event schemas from other accounts are discovered. Default is True.
    cross_account: Any = None
    # A description for the discoverer.
    description: Any = None
    # The ARN of the discoverer.
    discoverer_arn: Any = None
    # The Id of the discoverer.
    discoverer_id: Any = None
    # The ARN of the event bus.
    source_arn: Any = None
    # Defines the current state of the discoverer.
    state: Any = None
    # Tags associated with the resource.
    tags: Any = None

Discoverer = ubx.ResourceBinding(
    wire_type="aws_event_schemas_discoverer",
    fields={
        "cross_account": ubx.FieldSpec(wire_name="cross_account"),
        "description": ubx.FieldSpec(wire_name="description"),
        "source_arn": ubx.FieldSpec(wire_name="source_arn"),
        "tags": ubx.FieldSpec(
            wire_name="tags",
            kind="list",
            fields=_Discoverer_TagsFields,
        ),
    },
)
