// Code generated by `ubx sdk gen` from aws_dev_ops_agent_agent_space. DO NOT EDIT.
package dev

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpsAgentAgentSpace_OperatorApp_Iam struct {
	CreatedAt any
	OperatorAppRoleArn any
	UpdatedAt any
}

type OpsAgentAgentSpace_OperatorApp_Idc struct {
	CreatedAt any
	IdcApplicationArn any
	// The Amazon Resource Name (ARN) of the IAM Identity Center (IdC) instance used by the operator application in the agent space for its identity configuration. (AI-inferred)
	IdcInstanceArn any
	// The Amazon Resource Name (ARN) of the IAM role that the operator application assumes within the AWS IAM Identity Center (IDC) configuration for the agent space. (AI-inferred)
	OperatorAppRoleArn any
	UpdatedAt any
}

type OpsAgentAgentSpace_OperatorApp struct {
	// In an AWS::DevOpsAgent::AgentSpace, the `operator_app.iam` field defines the IAM role and permission settings the operator application uses to securely access AWS resources on behalf of the agent space. (AI-inferred)
	Iam any
	Idc any
}

type OpsAgentAgentSpace_Tags struct {
	Key any
	Value any
}

var OpsAgentAgentSpace_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type OpsAgentAgentSpaceConfig struct {
	// The description of the AgentSpace.
	Description any
	// The ARN of the KMS key to use for encryption.
	KmsKeyArn any
	// The locale for the AgentSpace, which determines the language used in agent responses.
	Locale any
	// The name of the AgentSpace.
	Name any
	// An array of key-value pairs to apply to this resource.
	Tags any
}

type OpsAgentAgentSpaceAttrs struct {
	// The unique identifier of the AgentSpace
	AgentSpaceId any
	// The Amazon Resource Name (ARN) of the AgentSpace.
	Arn any
	// The timestamp when the resource was created.
	CreatedAt any
	// The description of the AgentSpace.
	Description any
	// The ARN of the KMS key to use for encryption.
	KmsKeyArn any
	// The locale for the AgentSpace, which determines the language used in agent responses.
	Locale any
	// The name of the AgentSpace.
	Name any
	OperatorApp any
	// An array of key-value pairs to apply to this resource.
	Tags any
	// The timestamp when the resource was last updated.
	UpdatedAt any
}

var OpsAgentAgentSpace = ubx.ResourceBinding{
	WireType: "aws_dev_ops_agent_agent_space",
	Fields: ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"KmsKeyArn": ubx.FieldSpec{WireName: "kms_key_arn"},
		"Locale": ubx.FieldSpec{WireName: "locale"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: OpsAgentAgentSpace_TagsFields,
		},
	},
}
