// Code generated by `ubx sdk gen` from aws_appstream2_app_license_usage. DO NOT EDIT.
package appstream2

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AppLicenseUsage_AppLicenseUsages struct {
	BillingPeriod any
	LicenseType any
	OwnerAwsaccountId any
	SubscriptionFirstUsedDate any
	SubscriptionLastUsedDate any
	UserArn any
	UserId any
}

type AppLicenseUsageConfig struct {
	BillingPeriod any
	MaxResults any
	NextToken any
}

type AppLicenseUsageAttrs struct {
	AppLicenseUsages any
	BillingPeriod any
	MaxResults any
	NextToken any
}

var AppLicenseUsage = ubx.DataSourceBinding{
	WireType: "aws_appstream2_app_license_usage",
	Fields: ubx.FieldMap{
		"BillingPeriod": ubx.FieldSpec{WireName: "billing_period"},
		"MaxResults": ubx.FieldSpec{WireName: "max_results"},
		"NextToken": ubx.FieldSpec{WireName: "next_token"},
	},
}
