// Code generated by `ubx sdk gen` from aws_trustedadvisor_recommendation_resources. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RecommendationResources_RecommendationResourceSummaries {
  arn?: string | Computed<string>;
  awsResourceId?: string | Computed<string>;
  exclusionStatus?: string | Computed<string>;
  id?: string | Computed<string>;
  lastUpdatedAt?: string | Computed<string>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  recommendationArn?: string | Computed<string>;
  regionCode?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface RecommendationResourcesConfig {
  exclusionStatus?: string | Computed<string>;
  language?: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  recommendationIdentifier: string | Computed<string>;
  regionCode?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface RecommendationResourcesAttrs {
  exclusionStatus: string;
  language: string;
  maxResults: number;
  nextToken: string;
  recommendationIdentifier: string;
  recommendationResourceSummaries: RecommendationResources_RecommendationResourceSummaries[];
  regionCode: string;
  status: string;
}

export const RecommendationResources: DataSourceBinding<RecommendationResourcesConfig, RecommendationResourcesAttrs> = {
  wireType: "aws_trustedadvisor_recommendation_resources",
  fields: {
    exclusionStatus: "exclusion_status",
    language: "language",
    maxResults: "max_results",
    nextToken: "next_token",
    recommendationIdentifier: "recommendation_identifier",
    regionCode: "region_code",
    status: "status",
  },
};
