// Code generated by `ubx sdk gen` from aws_cloudwatch_contributor_managed_insight_rule. DO NOT EDIT.
package cloudwatch

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ContributorManagedInsightRuleConfig struct {
	Region any
	ResourceArn any
	State any
	Tags any
	TemplateName any
}

var ContributorManagedInsightRule = ubx.ResourceBinding{
	WireType: "aws_cloudwatch_contributor_managed_insight_rule",
	Fields: ubx.FieldMap{
		"Region": ubx.FieldSpec{WireName: "region"},
		"ResourceArn": ubx.FieldSpec{WireName: "resource_arn"},
		"State": ubx.FieldSpec{WireName: "state"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"TemplateName": ubx.FieldSpec{WireName: "template_name"},
	},
}
