# Code generated by `ubx sdk gen` from aws_datasync_location_hdfs. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LocationHdfs_NameNode:
    hostname: Any = None
    port: Any = None

@dataclasses.dataclass
class LocationHdfs_QopConfiguration:
    data_transfer_protection: Any = None
    rpc_protection: Any = None

_LocationHdfs_NameNodeFields = {
    "hostname": ubx.FieldSpec(wire_name="hostname"),
    "port": ubx.FieldSpec(wire_name="port"),
}

_LocationHdfs_QopConfigurationFields = {
    "data_transfer_protection": ubx.FieldSpec(wire_name="data_transfer_protection"),
    "rpc_protection": ubx.FieldSpec(wire_name="rpc_protection"),
}

@dataclasses.dataclass
class LocationHdfsConfig:
    agent_arns: Any = None
    authentication_type: Any = None
    block_size: Any = None
    id: Any = None
    kerberos_keytab: Any = None
    kerberos_keytab_base64: Any = None
    kerberos_krb5_conf: Any = None
    kerberos_krb5_conf_base64: Any = None
    kerberos_principal: Any = None
    kms_key_provider_uri: Any = None
    region: Any = None
    replication_factor: Any = None
    simple_user: Any = None
    subdirectory: Any = None
    tags: Any = None
    tags_all: Any = None
    name_node: Any = None
    qop_configuration: Any = None

LocationHdfs = ubx.ResourceBinding(
    wire_type="aws_datasync_location_hdfs",
    fields={
        "agent_arns": ubx.FieldSpec(wire_name="agent_arns"),
        "authentication_type": ubx.FieldSpec(wire_name="authentication_type"),
        "block_size": ubx.FieldSpec(wire_name="block_size"),
        "id": ubx.FieldSpec(wire_name="id"),
        "kerberos_keytab": ubx.FieldSpec(wire_name="kerberos_keytab"),
        "kerberos_keytab_base64": ubx.FieldSpec(wire_name="kerberos_keytab_base64"),
        "kerberos_krb5_conf": ubx.FieldSpec(wire_name="kerberos_krb5_conf"),
        "kerberos_krb5_conf_base64": ubx.FieldSpec(wire_name="kerberos_krb5_conf_base64"),
        "kerberos_principal": ubx.FieldSpec(wire_name="kerberos_principal"),
        "kms_key_provider_uri": ubx.FieldSpec(wire_name="kms_key_provider_uri"),
        "region": ubx.FieldSpec(wire_name="region"),
        "replication_factor": ubx.FieldSpec(wire_name="replication_factor"),
        "simple_user": ubx.FieldSpec(wire_name="simple_user"),
        "subdirectory": ubx.FieldSpec(wire_name="subdirectory"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "name_node": ubx.FieldSpec(
            wire_name="name_node",
            kind="set",
            fields=_LocationHdfs_NameNodeFields,
        ),
        "qop_configuration": ubx.FieldSpec(
            wire_name="qop_configuration",
            kind="list",
            fields=_LocationHdfs_QopConfigurationFields,
        ),
    },
)
