# Code generated by `ubx sdk gen` from aws_elasticache_user_group_association. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class UserGroupAssociation_Timeouts:
    create: Any = None
    delete: Any = None

_UserGroupAssociation_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
}

@dataclasses.dataclass
class UserGroupAssociationConfig:
    id: Any = None
    region: Any = None
    user_group_id: Any = None
    user_id: Any = None
    timeouts: Any = None

UserGroupAssociation = ubx.ResourceBinding(
    wire_type="aws_elasticache_user_group_association",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "region": ubx.FieldSpec(wire_name="region"),
        "user_group_id": ubx.FieldSpec(wire_name="user_group_id"),
        "user_id": ubx.FieldSpec(wire_name="user_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_UserGroupAssociation_TimeoutsFields,
        ),
    },
)
