# Code generated by `ubx sdk gen` from aws_states_activity_task. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ActivityTaskConfig:
    activity_arn: Any = None
    worker_name: Any = None

@dataclasses.dataclass
class ActivityTaskAttrs:
    activity_arn: Any = None
    input: Any = None
    task_token: Any = None
    worker_name: Any = None

ActivityTask = ubx.DataSourceBinding(
    wire_type="aws_states_activity_task",
    fields={
        "activity_arn": ubx.FieldSpec(wire_name="activity_arn"),
        "worker_name": ubx.FieldSpec(wire_name="worker_name"),
    },
)
