# Code generated by `ubx sdk gen` from aws_inspector_assessment_template. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AssessmentTemplate_EventSubscription:
    event: Any = None
    topic_arn: Any = None

_AssessmentTemplate_EventSubscriptionFields = {
    "event": ubx.FieldSpec(wire_name="event"),
    "topic_arn": ubx.FieldSpec(wire_name="topic_arn"),
}

@dataclasses.dataclass
class AssessmentTemplateConfig:
    duration: Any = None
    id: Any = None
    name: Any = None
    region: Any = None
    rules_package_arns: Any = None
    tags: Any = None
    tags_all: Any = None
    target_arn: Any = None
    event_subscription: Any = None

AssessmentTemplate = ubx.ResourceBinding(
    wire_type="aws_inspector_assessment_template",
    fields={
        "duration": ubx.FieldSpec(wire_name="duration"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "region": ubx.FieldSpec(wire_name="region"),
        "rules_package_arns": ubx.FieldSpec(wire_name="rules_package_arns"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "target_arn": ubx.FieldSpec(wire_name="target_arn"),
        "event_subscription": ubx.FieldSpec(
            wire_name="event_subscription",
            kind="set",
            fields=_AssessmentTemplate_EventSubscriptionFields,
        ),
    },
)
