# Code generated by `ubx sdk gen` from aws_emr_security_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SecurityConfigurationConfig:
    configuration: Any = None
    id: Any = None
    name: Any = None
    name_prefix: Any = None
    region: Any = None

SecurityConfiguration = ubx.ResourceBinding(
    wire_type="aws_emr_security_configuration",
    fields={
        "configuration": ubx.FieldSpec(wire_name="configuration"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "name_prefix": ubx.FieldSpec(wire_name="name_prefix"),
        "region": ubx.FieldSpec(wire_name="region"),
    },
)
