// Code generated by `ubx sdk gen` from aws_guard_duty_custom_detection_rule_association. DO NOT EDIT.
package guardduty

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CustomDetectionRuleAssociation_Tags struct {
	Key any
	Value any
}

var CustomDetectionRuleAssociation_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type CustomDetectionRuleAssociationConfig struct {
	// Whether the rule runs in LIVE mode (generates findings) or DRY_RUN mode (evaluates without generating findings).
	Mode any
	// The catalog identifier of the custom detection rule to associate.
	RuleId any
	// The tags applied to the association.
	Tags any
}

type CustomDetectionRuleAssociationAttrs struct {
	// The AWS account ID the association applies to.
	AccountId any
	// The Amazon Resource Name (ARN) of the association.
	Arn any
	// The service-generated unique identifier of the association.
	AssociationId any
	// The time the association was created.
	CreatedAt any
	// Whether the rule runs in LIVE mode (generates findings) or DRY_RUN mode (evaluates without generating findings).
	Mode any
	// The catalog identifier of the custom detection rule to associate.
	RuleId any
	// The tags applied to the association.
	Tags any
	// The time the association was last updated.
	UpdatedAt any
}

var CustomDetectionRuleAssociation = ubx.ResourceBinding{
	WireType: "aws_guard_duty_custom_detection_rule_association",
	Fields: ubx.FieldMap{
		"Mode": ubx.FieldSpec{WireName: "mode"},
		"RuleId": ubx.FieldSpec{WireName: "rule_id"},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: CustomDetectionRuleAssociation_TagsFields,
		},
	},
}
