// Code generated by `ubx sdk gen` from aws_cognito_idp_users_in_group. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CognitoIdpUsersInGroup_Users_Attributes {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface CognitoIdpUsersInGroup_Users_Mfaoptions {
  attributeName?: string | Computed<string>;
  deliveryMedium?: string | Computed<string>;
}

export interface CognitoIdpUsersInGroup_Users {
  attributes?: CognitoIdpUsersInGroup_Users_Attributes[] | Computed<CognitoIdpUsersInGroup_Users_Attributes[]>;
  enabled?: boolean | Computed<boolean>;
  mfaoptions?: CognitoIdpUsersInGroup_Users_Mfaoptions[] | Computed<CognitoIdpUsersInGroup_Users_Mfaoptions[]>;
  userCreateDate?: string | Computed<string>;
  userLastModifiedDate?: string | Computed<string>;
  userStatus?: string | Computed<string>;
  username?: string | Computed<string>;
}

export interface CognitoIdpUsersInGroupConfig {
  groupName: string | Computed<string>;
  limit?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  userPoolId: string | Computed<string>;
}

export interface CognitoIdpUsersInGroupAttrs {
  groupName: string;
  limit: number;
  nextToken: string;
  userPoolId: string;
  users: CognitoIdpUsersInGroup_Users[];
}

export const CognitoIdpUsersInGroup: DataSourceBinding<CognitoIdpUsersInGroupConfig, CognitoIdpUsersInGroupAttrs> = {
  wireType: "aws_cognito_idp_users_in_group",
  fields: {
    groupName: "group_name",
    limit: "limit",
    nextToken: "next_token",
    userPoolId: "user_pool_id",
  },
};
