# Code generated by `ubx sdk gen` from aws_gamelift_instances. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Instances_Instances:
    creation_time: Any = None
    dns_name: Any = None
    fleet_arn: Any = None
    fleet_id: Any = None
    instance_id: Any = None
    ip_address: Any = None
    location: Any = None
    operating_system: Any = None
    status: Any = None
    type: Any = None

@dataclasses.dataclass
class InstancesConfig:
    fleet_id: Any = None
    instance_id: Any = None
    limit: Any = None
    location: Any = None
    next_token: Any = None

@dataclasses.dataclass
class InstancesAttrs:
    fleet_id: Any = None
    instance_id: Any = None
    instances: Any = None
    limit: Any = None
    location: Any = None
    next_token: Any = None

Instances = ubx.DataSourceBinding(
    wire_type="aws_gamelift_instances",
    fields={
        "fleet_id": ubx.FieldSpec(wire_name="fleet_id"),
        "instance_id": ubx.FieldSpec(wire_name="instance_id"),
        "limit": ubx.FieldSpec(wire_name="limit"),
        "location": ubx.FieldSpec(wire_name="location"),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
    },
)
