# Code generated by `ubx sdk gen` from aws_licensemanager_license_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LicenseConfigurationConfig:
    description: Any = None
    id: Any = None
    license_count: Any = None
    license_count_hard_limit: Any = None
    license_counting_type: Any = None
    license_rules: Any = None
    name: Any = None
    region: Any = None
    tags: Any = None
    tags_all: Any = None

LicenseConfiguration = ubx.ResourceBinding(
    wire_type="aws_licensemanager_license_configuration",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "license_count": ubx.FieldSpec(wire_name="license_count"),
        "license_count_hard_limit": ubx.FieldSpec(wire_name="license_count_hard_limit"),
        "license_counting_type": ubx.FieldSpec(wire_name="license_counting_type"),
        "license_rules": ubx.FieldSpec(wire_name="license_rules"),
        "name": ubx.FieldSpec(wire_name="name"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
    },
)
