// Code generated by `ubx sdk gen` from aws_certificate_manager_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Account_ExpiryEventsConfiguration {
  /** Specifies the number of days before certificate expiration when ACM begins emitting expiry-related events, allowing you to adjust the notification lead time. (AI-inferred) */
  daysBeforeExpiry?: number | Computed<number>;
}

const Account_ExpiryEventsConfigurationFields: FieldMap = {
  daysBeforeExpiry: "days_before_expiry",
};

export interface AccountConfig {
  /** Configures the day-based threshold (DaysBeforeExpiry) at which AWS Certificate Manager emits certificate expiration events, enabling EventBridge notifications for upcoming renewals. (AI-inferred) */
  expiryEventsConfiguration: Account_ExpiryEventsConfiguration | Computed<Account_ExpiryEventsConfiguration>;
}

export interface AccountAttrs {
  /** The AWS account ID that owns this ACM account-level configuration, automatically derived from the account in which the resource is deployed. (AI-inferred) */
  accountId: string;
  /** Configures the day-based threshold (DaysBeforeExpiry) at which AWS Certificate Manager emits certificate expiration events, enabling EventBridge notifications for upcoming renewals. (AI-inferred) */
  expiryEventsConfiguration: Account_ExpiryEventsConfiguration;
}

export const Account: ResourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "aws_certificate_manager_account",
  fields: {
    expiryEventsConfiguration: {
      wireName: "expiry_events_configuration",
      kind: "object",
      fields: Account_ExpiryEventsConfigurationFields,
    },
  },
};
