// Code generated by `ubx sdk gen` from aws_certificate_manager_acme_external_account_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AcmeExternalAccountBinding_Expiration {
  /** The time unit for the expiration value. */
  type: string | Computed<string>;
  /** The expiration value. */
  value: number | Computed<number>;
}

export interface AcmeExternalAccountBinding_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const AcmeExternalAccountBinding_ExpirationFields: FieldMap = {
  type: "type",
  value: "value",
};

const AcmeExternalAccountBinding_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface AcmeExternalAccountBindingConfig {
  /** The ARN of the ACME endpoint this binding is associated with. */
  acmeEndpointArn: string | Computed<string>;
  /** The expiration configuration for the external account binding. */
  expiration?: AcmeExternalAccountBinding_Expiration | Computed<AcmeExternalAccountBinding_Expiration>;
  /** The IAM role ARN for cross-account access. */
  roleArn: string | Computed<string>;
  /** Tags associated with the external account binding. */
  tags?: AcmeExternalAccountBinding_Tags[] | Computed<AcmeExternalAccountBinding_Tags[]>;
}

export interface AcmeExternalAccountBindingAttrs {
  /** The ARN of the ACME endpoint this binding is associated with. */
  acmeEndpointArn: string;
  /** The Amazon Resource Name (ARN) of the external account binding. */
  acmeExternalAccountBindingArn: string;
  /** The expiration configuration for the external account binding. */
  expiration: AcmeExternalAccountBinding_Expiration;
  /** The IAM role ARN for cross-account access. */
  roleArn: string;
  /** Tags associated with the external account binding. */
  tags: AcmeExternalAccountBinding_Tags[];
}

export const AcmeExternalAccountBinding: ResourceBinding<AcmeExternalAccountBindingConfig, AcmeExternalAccountBindingAttrs> = {
  wireType: "aws_certificate_manager_acme_external_account_binding",
  fields: {
    acmeEndpointArn: "acme_endpoint_arn",
    expiration: {
      wireName: "expiration",
      kind: "object",
      fields: AcmeExternalAccountBinding_ExpirationFields,
    },
    roleArn: "role_arn",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: AcmeExternalAccountBinding_TagsFields,
    },
  },
};
