# Code generated by `ubx sdk gen` from aws_swf_workflow_execution_history. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskCancelRequestedEventAttributes:
    activity_id: Any = None
    decision_task_completed_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskCanceledEventAttributes:
    details: Any = None
    latest_cancel_requested_event_id: Any = None
    scheduled_event_id: Any = None
    started_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskCompletedEventAttributes:
    result: Any = None
    scheduled_event_id: Any = None
    started_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskFailedEventAttributes:
    details: Any = None
    reason: Any = None
    scheduled_event_id: Any = None
    started_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskScheduledEventAttributes_ActivityType:
    name: Any = None
    version: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskScheduledEventAttributes_TaskList:
    name: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskScheduledEventAttributes:
    activity_id: Any = None
    activity_type: Any = None
    control: Any = None
    decision_task_completed_event_id: Any = None
    heartbeat_timeout: Any = None
    input: Any = None
    schedule_to_close_timeout: Any = None
    schedule_to_start_timeout: Any = None
    start_to_close_timeout: Any = None
    task_list: Any = None
    task_priority: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskStartedEventAttributes:
    identity: Any = None
    scheduled_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ActivityTaskTimedOutEventAttributes:
    details: Any = None
    scheduled_event_id: Any = None
    started_event_id: Any = None
    timeout_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_CancelTimerFailedEventAttributes:
    cause: Any = None
    decision_task_completed_event_id: Any = None
    timer_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_CancelWorkflowExecutionFailedEventAttributes:
    cause: Any = None
    decision_task_completed_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionCanceledEventAttributes_WorkflowExecution:
    run_id: Any = None
    workflow_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionCanceledEventAttributes:
    details: Any = None
    initiated_event_id: Any = None
    started_event_id: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionCompletedEventAttributes:
    initiated_event_id: Any = None
    result: Any = None
    started_event_id: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionFailedEventAttributes:
    details: Any = None
    initiated_event_id: Any = None
    reason: Any = None
    started_event_id: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionStartedEventAttributes:
    initiated_event_id: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionTerminatedEventAttributes:
    initiated_event_id: Any = None
    started_event_id: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ChildWorkflowExecutionTimedOutEventAttributes:
    initiated_event_id: Any = None
    started_event_id: Any = None
    timeout_type: Any = None
    workflow_execution: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_DecisionTaskCompletedEventAttributes:
    execution_context: Any = None
    scheduled_event_id: Any = None
    started_event_id: Any = None
    task_list: Any = None
    task_list_schedule_to_start_timeout: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_DecisionTaskScheduledEventAttributes:
    schedule_to_start_timeout: Any = None
    start_to_close_timeout: Any = None
    task_list: Any = None
    task_priority: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_DecisionTaskTimedOutEventAttributes:
    scheduled_event_id: Any = None
    started_event_id: Any = None
    timeout_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ExternalWorkflowExecutionCancelRequestedEventAttributes:
    initiated_event_id: Any = None
    workflow_execution: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_LambdaFunctionScheduledEventAttributes:
    control: Any = None
    decision_task_completed_event_id: Any = None
    id: Any = None
    input: Any = None
    name: Any = None
    start_to_close_timeout: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_LambdaFunctionStartedEventAttributes:
    scheduled_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_MarkerRecordedEventAttributes:
    decision_task_completed_event_id: Any = None
    details: Any = None
    marker_name: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_RecordMarkerFailedEventAttributes:
    cause: Any = None
    decision_task_completed_event_id: Any = None
    marker_name: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_RequestCancelActivityTaskFailedEventAttributes:
    activity_id: Any = None
    cause: Any = None
    decision_task_completed_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_RequestCancelExternalWorkflowExecutionFailedEventAttributes:
    cause: Any = None
    control: Any = None
    decision_task_completed_event_id: Any = None
    initiated_event_id: Any = None
    run_id: Any = None
    workflow_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_RequestCancelExternalWorkflowExecutionInitiatedEventAttributes:
    control: Any = None
    decision_task_completed_event_id: Any = None
    run_id: Any = None
    workflow_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ScheduleActivityTaskFailedEventAttributes:
    activity_id: Any = None
    activity_type: Any = None
    cause: Any = None
    decision_task_completed_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_ScheduleLambdaFunctionFailedEventAttributes:
    cause: Any = None
    decision_task_completed_event_id: Any = None
    id: Any = None
    name: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_SignalExternalWorkflowExecutionInitiatedEventAttributes:
    control: Any = None
    decision_task_completed_event_id: Any = None
    input: Any = None
    run_id: Any = None
    signal_name: Any = None
    workflow_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_StartChildWorkflowExecutionFailedEventAttributes:
    cause: Any = None
    control: Any = None
    decision_task_completed_event_id: Any = None
    initiated_event_id: Any = None
    workflow_id: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_StartChildWorkflowExecutionInitiatedEventAttributes:
    child_policy: Any = None
    control: Any = None
    decision_task_completed_event_id: Any = None
    execution_start_to_close_timeout: Any = None
    input: Any = None
    lambda_role: Any = None
    tag_list: Any = None
    task_list: Any = None
    task_priority: Any = None
    task_start_to_close_timeout: Any = None
    workflow_id: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_StartLambdaFunctionFailedEventAttributes:
    cause: Any = None
    message: Any = None
    scheduled_event_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_TimerCanceledEventAttributes:
    decision_task_completed_event_id: Any = None
    started_event_id: Any = None
    timer_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_TimerFiredEventAttributes:
    started_event_id: Any = None
    timer_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_TimerStartedEventAttributes:
    control: Any = None
    decision_task_completed_event_id: Any = None
    start_to_fire_timeout: Any = None
    timer_id: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionCancelRequestedEventAttributes:
    cause: Any = None
    external_initiated_event_id: Any = None
    external_workflow_execution: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionCanceledEventAttributes:
    decision_task_completed_event_id: Any = None
    details: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionCompletedEventAttributes:
    decision_task_completed_event_id: Any = None
    result: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionContinuedAsNewEventAttributes:
    child_policy: Any = None
    decision_task_completed_event_id: Any = None
    execution_start_to_close_timeout: Any = None
    input: Any = None
    lambda_role: Any = None
    new_execution_run_id: Any = None
    tag_list: Any = None
    task_list: Any = None
    task_priority: Any = None
    task_start_to_close_timeout: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionFailedEventAttributes:
    decision_task_completed_event_id: Any = None
    details: Any = None
    reason: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionSignaledEventAttributes:
    external_initiated_event_id: Any = None
    external_workflow_execution: Any = None
    input: Any = None
    signal_name: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionStartedEventAttributes:
    child_policy: Any = None
    continued_execution_run_id: Any = None
    execution_start_to_close_timeout: Any = None
    input: Any = None
    lambda_role: Any = None
    parent_initiated_event_id: Any = None
    parent_workflow_execution: Any = None
    tag_list: Any = None
    task_list: Any = None
    task_priority: Any = None
    task_start_to_close_timeout: Any = None
    workflow_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionTerminatedEventAttributes:
    cause: Any = None
    child_policy: Any = None
    details: Any = None
    reason: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events_WorkflowExecutionTimedOutEventAttributes:
    child_policy: Any = None
    timeout_type: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistory_Events:
    activity_task_cancel_requested_event_attributes: Any = None
    activity_task_canceled_event_attributes: Any = None
    activity_task_completed_event_attributes: Any = None
    activity_task_failed_event_attributes: Any = None
    activity_task_scheduled_event_attributes: Any = None
    activity_task_started_event_attributes: Any = None
    activity_task_timed_out_event_attributes: Any = None
    cancel_timer_failed_event_attributes: Any = None
    cancel_workflow_execution_failed_event_attributes: Any = None
    child_workflow_execution_canceled_event_attributes: Any = None
    child_workflow_execution_completed_event_attributes: Any = None
    child_workflow_execution_failed_event_attributes: Any = None
    child_workflow_execution_started_event_attributes: Any = None
    child_workflow_execution_terminated_event_attributes: Any = None
    child_workflow_execution_timed_out_event_attributes: Any = None
    complete_workflow_execution_failed_event_attributes: Any = None
    continue_as_new_workflow_execution_failed_event_attributes: Any = None
    decision_task_completed_event_attributes: Any = None
    decision_task_scheduled_event_attributes: Any = None
    decision_task_started_event_attributes: Any = None
    decision_task_timed_out_event_attributes: Any = None
    event_id: Any = None
    event_timestamp: Any = None
    event_type: Any = None
    external_workflow_execution_cancel_requested_event_attributes: Any = None
    external_workflow_execution_signaled_event_attributes: Any = None
    fail_workflow_execution_failed_event_attributes: Any = None
    lambda_function_completed_event_attributes: Any = None
    lambda_function_failed_event_attributes: Any = None
    lambda_function_scheduled_event_attributes: Any = None
    lambda_function_started_event_attributes: Any = None
    lambda_function_timed_out_event_attributes: Any = None
    marker_recorded_event_attributes: Any = None
    record_marker_failed_event_attributes: Any = None
    request_cancel_activity_task_failed_event_attributes: Any = None
    request_cancel_external_workflow_execution_failed_event_attributes: Any = None
    request_cancel_external_workflow_execution_initiated_event_attributes: Any = None
    schedule_activity_task_failed_event_attributes: Any = None
    schedule_lambda_function_failed_event_attributes: Any = None
    signal_external_workflow_execution_failed_event_attributes: Any = None
    signal_external_workflow_execution_initiated_event_attributes: Any = None
    start_child_workflow_execution_failed_event_attributes: Any = None
    start_child_workflow_execution_initiated_event_attributes: Any = None
    start_lambda_function_failed_event_attributes: Any = None
    start_timer_failed_event_attributes: Any = None
    timer_canceled_event_attributes: Any = None
    timer_fired_event_attributes: Any = None
    timer_started_event_attributes: Any = None
    workflow_execution_cancel_requested_event_attributes: Any = None
    workflow_execution_canceled_event_attributes: Any = None
    workflow_execution_completed_event_attributes: Any = None
    workflow_execution_continued_as_new_event_attributes: Any = None
    workflow_execution_failed_event_attributes: Any = None
    workflow_execution_signaled_event_attributes: Any = None
    workflow_execution_started_event_attributes: Any = None
    workflow_execution_terminated_event_attributes: Any = None
    workflow_execution_timed_out_event_attributes: Any = None

_WorkflowExecutionHistory_Events_ChildWorkflowExecutionCanceledEventAttributes_WorkflowExecutionFields = {
    "run_id": ubx.FieldSpec(wire_name="run_id"),
    "workflow_id": ubx.FieldSpec(wire_name="workflow_id"),
}

@dataclasses.dataclass
class WorkflowExecutionHistoryConfig:
    domain: Any = None
    # <p>Represents a workflow execution.</p>
    execution: Any = None
    maximum_page_size: Any = None
    next_page_token: Any = None
    reverse_order: Any = None

@dataclasses.dataclass
class WorkflowExecutionHistoryAttrs:
    domain: Any = None
    events: Any = None
    # <p>Represents a workflow execution.</p>
    execution: Any = None
    maximum_page_size: Any = None
    next_page_token: Any = None
    reverse_order: Any = None

WorkflowExecutionHistory = ubx.DataSourceBinding(
    wire_type="aws_swf_workflow_execution_history",
    fields={
        "domain": ubx.FieldSpec(wire_name="domain"),
        "execution": ubx.FieldSpec(
            wire_name="execution",
            kind="object",
            fields=_WorkflowExecutionHistory_Events_ChildWorkflowExecutionCanceledEventAttributes_WorkflowExecutionFields,
        ),
        "maximum_page_size": ubx.FieldSpec(wire_name="maximum_page_size"),
        "next_page_token": ubx.FieldSpec(wire_name="next_page_token"),
        "reverse_order": ubx.FieldSpec(wire_name="reverse_order"),
    },
)
