// Code generated by `ubx sdk gen` from aws_macie2_sensitive_data_occurrences_availability. DO NOT EDIT.
package macie2

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SensitiveDataOccurrencesAvailabilityConfig struct {
	FindingId any
}

type SensitiveDataOccurrencesAvailabilityAttrs struct {
	// <p>Specifies whether occurrences of sensitive data can be retrieved for a finding. Possible values are:</p>
	Code any
	FindingId any
	Reasons any
}

var SensitiveDataOccurrencesAvailability = ubx.DataSourceBinding{
	WireType: "aws_macie2_sensitive_data_occurrences_availability",
	Fields: ubx.FieldMap{
		"FindingId": ubx.FieldSpec{WireName: "finding_id"},
	},
}
