// Code generated by `ubx sdk gen` from aws_forecast_accuracy_metrics. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_ErrorMetrics {
  forecastType?: string | Computed<string>;
  mape?: number | Computed<number>;
  mase?: number | Computed<number>;
  rmse?: number | Computed<number>;
  wape?: number | Computed<number>;
}

export interface AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_WeightedQuantileLosses {
  lossValue?: number | Computed<number>;
  quantile?: number | Computed<number>;
}

export interface AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics {
  averageWeightedQuantileLoss?: number | Computed<number>;
  errorMetrics?: AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_ErrorMetrics[] | Computed<AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_ErrorMetrics[]>;
  rmse?: number | Computed<number>;
  weightedQuantileLosses?: AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_WeightedQuantileLosses[] | Computed<AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics_WeightedQuantileLosses[]>;
}

export interface AccuracyMetrics_PredictorEvaluationResults_TestWindows {
  evaluationType?: string | Computed<string>;
  itemCount?: number | Computed<number>;
  metrics?: AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics | Computed<AccuracyMetrics_PredictorEvaluationResults_TestWindows_Metrics>;
  testWindowEnd?: string | Computed<string>;
  testWindowStart?: string | Computed<string>;
}

export interface AccuracyMetrics_PredictorEvaluationResults {
  algorithmArn?: string | Computed<string>;
  testWindows?: AccuracyMetrics_PredictorEvaluationResults_TestWindows[] | Computed<AccuracyMetrics_PredictorEvaluationResults_TestWindows[]>;
}

export interface AccuracyMetricsConfig {
  predictorArn: string | Computed<string>;
}

export interface AccuracyMetricsAttrs {
  autoMloverrideStrategy: string;
  isAutoPredictor: boolean;
  optimizationMetric: string;
  predictorArn: string;
  predictorEvaluationResults: AccuracyMetrics_PredictorEvaluationResults[];
}

export const AccuracyMetrics: DataSourceBinding<AccuracyMetricsConfig, AccuracyMetricsAttrs> = {
  wireType: "aws_forecast_accuracy_metrics",
  fields: {
    predictorArn: "predictor_arn",
  },
};
