// Code generated by `ubx sdk gen` from aws_db_proxy_target. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ProxyTargetConfig {
  dbClusterIdentifier?: string | Computed<string>;
  dbInstanceIdentifier?: string | Computed<string>;
  dbProxyName: string | Computed<string>;
  id?: string | Computed<string>;
  region?: string | Computed<string>;
  targetGroupName: string | Computed<string>;
}

export interface ProxyTargetAttrs {
  dbClusterIdentifier: string;
  dbInstanceIdentifier: string;
  dbProxyName: string;
  endpoint: string;
  id: string;
  port: number;
  rdsResourceId: string;
  region: string;
  targetArn: string;
  targetGroupName: string;
  trackedClusterId: string;
  type: string;
}

export const ProxyTarget: ResourceBinding<ProxyTargetConfig, ProxyTargetAttrs> = {
  wireType: "aws_db_proxy_target",
  fields: {
    dbClusterIdentifier: "db_cluster_identifier",
    dbInstanceIdentifier: "db_instance_identifier",
    dbProxyName: "db_proxy_name",
    id: "id",
    region: "region",
    targetGroupName: "target_group_name",
  },
};
