// Code generated by `ubx sdk gen` from aws_ecr_account_setting. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccountSettingConfig {
  name: string | Computed<string>;
  region?: string | Computed<string>;
  value: string | Computed<string>;
}

export interface AccountSettingAttrs {
  name: string;
  region: string;
  value: string;
}

export const AccountSetting: ResourceBinding<AccountSettingConfig, AccountSettingAttrs> = {
  wireType: "aws_ecr_account_setting",
  fields: {
    name: "name",
    region: "region",
    value: "value",
  },
};
