# Code generated by `ubx sdk gen` from aws_code_pipeline_webhook. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PipelineWebhook_AuthenticationConfiguration:
    # The property used to configure acceptance of webhooks in an IP address range. For IP, only the AllowedIPRange property must be set. This property must be set to a valid CIDR range.
    allowed_iprange: Any = None
    # The property used to configure GitHub authentication. For GITHUB_HMAC, only the SecretToken property must be set.
    secret_token: Any = None

@dataclasses.dataclass
class PipelineWebhook_Filters:
    json_path: Any = None
    match_equals: Any = None

@dataclasses.dataclass
class PipelineWebhook_Tags:
    key: Any = None
    value: Any = None

_PipelineWebhook_AuthenticationConfigurationFields = {
    "allowed_iprange": ubx.FieldSpec(wire_name="allowed_iprange"),
    "secret_token": ubx.FieldSpec(wire_name="secret_token"),
}

_PipelineWebhook_FiltersFields = {
    "json_path": ubx.FieldSpec(wire_name="json_path"),
    "match_equals": ubx.FieldSpec(wire_name="match_equals"),
}

_PipelineWebhook_TagsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

@dataclasses.dataclass
class PipelineWebhookConfig:
    # Supported options are GITHUB_HMAC, IP, and UNAUTHENTICATED.
    authentication: Any = None
    # Properties that configure the authentication applied to incoming webhook trigger requests
    authentication_configuration: Any = None
    # A list of rules applied to the body/payload sent in the POST request to a webhook URL
    filters: Any = None
    # The name of the webhook
    name: Any = None
    # Configures a connection between the webhook that was created and the external tool with events to be detected.
    register_with_third_party: Any = None
    # An array of key-value pairs to apply to this resource.
    tags: Any = None
    # The name of the action in a pipeline you want to connect to the webhook.
    target_action: Any = None
    # The name of the pipeline you want to connect to the webhook.
    target_pipeline: Any = None
    # The version number of the pipeline to be connected to the trigger request.
    target_pipeline_version: Any = None

@dataclasses.dataclass
class PipelineWebhookAttrs:
    # Supported options are GITHUB_HMAC, IP, and UNAUTHENTICATED.
    authentication: Any = None
    # Properties that configure the authentication applied to incoming webhook trigger requests
    authentication_configuration: Any = None
    # A list of rules applied to the body/payload sent in the POST request to a webhook URL
    filters: Any = None
    # logical id of the webhook
    id: Any = None
    # The name of the webhook
    name: Any = None
    # Configures a connection between the webhook that was created and the external tool with events to be detected.
    register_with_third_party: Any = None
    # An array of key-value pairs to apply to this resource.
    tags: Any = None
    # The name of the action in a pipeline you want to connect to the webhook.
    target_action: Any = None
    # The name of the pipeline you want to connect to the webhook.
    target_pipeline: Any = None
    # The version number of the pipeline to be connected to the trigger request.
    target_pipeline_version: Any = None
    # The webhook URL generated by AWS CodePipeline
    url: Any = None

PipelineWebhook = ubx.ResourceBinding(
    wire_type="aws_code_pipeline_webhook",
    fields={
        "authentication": ubx.FieldSpec(wire_name="authentication"),
        "authentication_configuration": ubx.FieldSpec(
            wire_name="authentication_configuration",
            kind="object",
            fields=_PipelineWebhook_AuthenticationConfigurationFields,
        ),
        "filters": ubx.FieldSpec(
            wire_name="filters",
            kind="list",
            fields=_PipelineWebhook_FiltersFields,
        ),
        "name": ubx.FieldSpec(wire_name="name"),
        "register_with_third_party": ubx.FieldSpec(wire_name="register_with_third_party"),
        "tags": ubx.FieldSpec(
            wire_name="tags",
            kind="list",
            fields=_PipelineWebhook_TagsFields,
        ),
        "target_action": ubx.FieldSpec(wire_name="target_action"),
        "target_pipeline": ubx.FieldSpec(wire_name="target_pipeline"),
        "target_pipeline_version": ubx.FieldSpec(wire_name="target_pipeline_version"),
    },
)
