// Code generated by `ubx sdk gen` from aws_cloudfront_trust_stores. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TrustStores_TrustStoreList {
  arn?: string | Computed<string>;
  etag?: string | Computed<string>;
  id?: string | Computed<string>;
  lastModifiedTime?: string | Computed<string>;
  name?: string | Computed<string>;
  numberOfCaCertificates?: number | Computed<number>;
  reason?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface TrustStoresConfig {
  marker?: string | Computed<string>;
  maxItems?: number | Computed<number>;
}

export interface TrustStoresAttrs {
  marker: string;
  maxItems: number;
  nextMarker: string;
  trustStoreList: TrustStores_TrustStoreList[];
}

export const TrustStores: DataSourceBinding<TrustStoresConfig, TrustStoresAttrs> = {
  wireType: "aws_cloudfront_trust_stores",
  fields: {
    marker: "marker",
    maxItems: "max_items",
  },
};
