# Code generated by `ubx sdk gen` from aws_dx_lag. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LagConfig:
    connection_id: Any = None
    connections_bandwidth: Any = None
    force_destroy: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    provider_name: Any = None
    region: Any = None
    tags: Any = None
    tags_all: Any = None

Lag = ubx.ResourceBinding(
    wire_type="aws_dx_lag",
    fields={
        "connection_id": ubx.FieldSpec(wire_name="connection_id"),
        "connections_bandwidth": ubx.FieldSpec(wire_name="connections_bandwidth"),
        "force_destroy": ubx.FieldSpec(wire_name="force_destroy"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "provider_name": ubx.FieldSpec(wire_name="provider_name"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
    },
)
