// Code generated by `ubx sdk gen` from aws_acm_pca_certificate_authorities. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_KeyUsage {
  crlsign?: boolean | Computed<boolean>;
  dataEncipherment?: boolean | Computed<boolean>;
  decipherOnly?: boolean | Computed<boolean>;
  digitalSignature?: boolean | Computed<boolean>;
  encipherOnly?: boolean | Computed<boolean>;
  keyAgreement?: boolean | Computed<boolean>;
  keyCertSign?: boolean | Computed<boolean>;
  keyEncipherment?: boolean | Computed<boolean>;
  nonRepudiation?: boolean | Computed<boolean>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName_CustomAttributes {
  objectIdentifier?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName {
  commonName?: string | Computed<string>;
  country?: string | Computed<string>;
  customAttributes?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName_CustomAttributes[] | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName_CustomAttributes[]>;
  distinguishedNameQualifier?: string | Computed<string>;
  generationQualifier?: string | Computed<string>;
  givenName?: string | Computed<string>;
  initials?: string | Computed<string>;
  locality?: string | Computed<string>;
  organization?: string | Computed<string>;
  organizationalUnit?: string | Computed<string>;
  pseudonym?: string | Computed<string>;
  serialNumber?: string | Computed<string>;
  state?: string | Computed<string>;
  surname?: string | Computed<string>;
  title?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_EdiPartyName {
  nameAssigner?: string | Computed<string>;
  partyName?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_OtherName {
  typeId?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation {
  directoryName?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName>;
  dnsName?: string | Computed<string>;
  ediPartyName?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_EdiPartyName | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_EdiPartyName>;
  ipAddress?: string | Computed<string>;
  otherName?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_OtherName | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_OtherName>;
  registeredId?: string | Computed<string>;
  rfc822Name?: string | Computed<string>;
  uniformResourceIdentifier?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessMethod {
  accessMethodType?: string | Computed<string>;
  customObjectIdentifier?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess {
  accessLocation?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation>;
  accessMethod?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessMethod | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessMethod>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions {
  keyUsage?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_KeyUsage | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_KeyUsage>;
  subjectInformationAccess?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess[] | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess[]>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration {
  csrExtensions?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions>;
  keyAlgorithm?: string | Computed<string>;
  signingAlgorithm?: string | Computed<string>;
  subject?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration_CsrExtensions_SubjectInformationAccess_AccessLocation_DirectoryName>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration_CrlDistributionPointExtensionConfiguration {
  omitExtension?: boolean | Computed<boolean>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration {
  crlDistributionPointExtensionConfiguration?: AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration_CrlDistributionPointExtensionConfiguration | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration_CrlDistributionPointExtensionConfiguration>;
  crlType?: string | Computed<string>;
  customCname?: string | Computed<string>;
  customPath?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  expirationInDays?: number | Computed<number>;
  s3BucketName?: string | Computed<string>;
  s3ObjectAcl?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_OcspConfiguration {
  enabled?: boolean | Computed<boolean>;
  ocspCustomCname?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration {
  crlConfiguration?: AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_CrlConfiguration>;
  ocspConfiguration?: AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_OcspConfiguration | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration_OcspConfiguration>;
}

export interface AcmPcaCertificateAuthorities_CertificateAuthorities {
  arn?: string | Computed<string>;
  certificateAuthorityConfiguration?: AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_CertificateAuthorityConfiguration>;
  createdAt?: string | Computed<string>;
  failureReason?: string | Computed<string>;
  keyStorageSecurityStandard?: string | Computed<string>;
  lastStateChangeAt?: string | Computed<string>;
  notAfter?: string | Computed<string>;
  notBefore?: string | Computed<string>;
  ownerAccount?: string | Computed<string>;
  restorableUntil?: string | Computed<string>;
  revocationConfiguration?: AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration | Computed<AcmPcaCertificateAuthorities_CertificateAuthorities_RevocationConfiguration>;
  serial?: string | Computed<string>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
  usageMode?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthoritiesConfig {
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  resourceOwner?: string | Computed<string>;
}

export interface AcmPcaCertificateAuthoritiesAttrs {
  certificateAuthorities: AcmPcaCertificateAuthorities_CertificateAuthorities[];
  maxResults: number;
  nextToken: string;
  resourceOwner: string;
}

export const AcmPcaCertificateAuthorities: DataSourceBinding<AcmPcaCertificateAuthoritiesConfig, AcmPcaCertificateAuthoritiesAttrs> = {
  wireType: "aws_acm_pca_certificate_authorities",
  fields: {
    maxResults: "max_results",
    nextToken: "next_token",
    resourceOwner: "resource_owner",
  },
};
