# Code generated by `ubx sdk gen` from aws_sesv2_contacts. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Contacts_Contacts_TopicDefaultPreferences:
    subscription_status: Any = None
    topic_name: Any = None

@dataclasses.dataclass
class Contacts_Contacts:
    email_address: Any = None
    last_updated_timestamp: Any = None
    topic_default_preferences: Any = None
    topic_preferences: Any = None
    unsubscribe_all: Any = None

@dataclasses.dataclass
class Contacts_Filter_TopicFilter:
    topic_name: Any = None
    use_default_if_preference_unavailable: Any = None

@dataclasses.dataclass
class Contacts_Filter:
    filtered_status: Any = None
    # <p>Used for filtering by a specific topic preference.</p>
    topic_filter: Any = None

_Contacts_Filter_TopicFilterFields = {
    "topic_name": ubx.FieldSpec(wire_name="topic_name"),
    "use_default_if_preference_unavailable": ubx.FieldSpec(wire_name="use_default_if_preference_unavailable"),
}

_Contacts_FilterFields = {
    "filtered_status": ubx.FieldSpec(wire_name="filtered_status"),
    "topic_filter": ubx.FieldSpec(
        wire_name="topic_filter",
        kind="object",
        fields=_Contacts_Filter_TopicFilterFields,
    ),
}

@dataclasses.dataclass
class ContactsConfig:
    contact_list_name: Any = None
    # <p>A filter that can be applied to a list of contacts.</p>
    filter: Any = None
    next_token: Any = None
    page_size: Any = None

@dataclasses.dataclass
class ContactsAttrs:
    contact_list_name: Any = None
    contacts: Any = None
    # <p>A filter that can be applied to a list of contacts.</p>
    filter: Any = None
    next_token: Any = None
    page_size: Any = None

Contacts = ubx.DataSourceBinding(
    wire_type="aws_sesv2_contacts",
    fields={
        "contact_list_name": ubx.FieldSpec(wire_name="contact_list_name"),
        "filter": ubx.FieldSpec(
            wire_name="filter",
            kind="object",
            fields=_Contacts_FilterFields,
        ),
        "next_token": ubx.FieldSpec(wire_name="next_token"),
        "page_size": ubx.FieldSpec(wire_name="page_size"),
    },
)
