// Code generated by `ubx sdk gen` from aws_aco_automation_automation_event. DO NOT EDIT.
package aco_automation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AcoAutomationAutomationEvent_EstimatedMonthlySavings struct {
	AfterDiscountSavings any
	BeforeDiscountSavings any
	Currency any
	SavingsEstimationMode any
}

type AcoAutomationAutomationEventConfig struct {
	EventId any
}

type AcoAutomationAutomationEventAttrs struct {
	AccountId any
	CompletedTimestamp any
	CreatedTimestamp any
	// <p> Contains information about estimated monthly cost savings. </p>
	EstimatedMonthlySavings any
	EventDescription any
	EventId any
	EventStatus any
	EventStatusReason any
	// Event type enumeration
	EventType any
	RecommendedActionId any
	Region any
	ResourceArn any
	ResourceId any
	ResourceType any
	RuleId any
}

var AcoAutomationAutomationEvent = ubx.DataSourceBinding{
	WireType: "aws_aco_automation_automation_event",
	Fields: ubx.FieldMap{
		"EventId": ubx.FieldSpec{WireName: "event_id"},
	},
}
