# Code generated by `ubx sdk gen` from aws_servicediscovery_operation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Operation_Operation:
    create_date: Any = None
    error_code: Any = None
    error_message: Any = None
    id: Any = None
    owner_account: Any = None
    status: Any = None
    targets: Any = None
    type: Any = None
    update_date: Any = None

@dataclasses.dataclass
class OperationConfig:
    operation_id: Any = None
    owner_account: Any = None

@dataclasses.dataclass
class OperationAttrs:
    # <p>A complex type that contains information about a specified operation.</p>
    operation: Any = None
    operation_id: Any = None
    owner_account: Any = None

Operation = ubx.DataSourceBinding(
    wire_type="aws_servicediscovery_operation",
    fields={
        "operation_id": ubx.FieldSpec(wire_name="operation_id"),
        "owner_account": ubx.FieldSpec(wire_name="owner_account"),
    },
)
