// Code generated by `ubx sdk gen` from aws_cleanrooms_tags_for_resource. DO NOT EDIT.
package cleanrooms

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TagsForResourceConfig struct {
	ResourceArn any
}

type TagsForResourceAttrs struct {
	ResourceArn any
	// Map of tags assigned to a resource
	Tags any
}

var TagsForResource = ubx.DataSourceBinding{
	WireType: "aws_cleanrooms_tags_for_resource",
	Fields: ubx.FieldMap{
		"ResourceArn": ubx.FieldSpec{WireName: "resource_arn"},
	},
}
