// Code generated by `ubx sdk gen` from aws_ecs_cluster_capacity_providers. DO NOT EDIT.
package ecs

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ClusterCapacityProviders_DefaultCapacityProviderStrategy struct {
	Base any
	CapacityProvider any
	Weight any
}

var ClusterCapacityProviders_DefaultCapacityProviderStrategyFields = ubx.FieldMap{
		"Base": ubx.FieldSpec{WireName: "base"},
		"CapacityProvider": ubx.FieldSpec{WireName: "capacity_provider"},
		"Weight": ubx.FieldSpec{WireName: "weight"},
	}

type ClusterCapacityProvidersConfig struct {
	CapacityProviders any
	ClusterName any
	Id any
	Region any
	DefaultCapacityProviderStrategy any
}

var ClusterCapacityProviders = ubx.ResourceBinding{
	WireType: "aws_ecs_cluster_capacity_providers",
	Fields: ubx.FieldMap{
		"CapacityProviders": ubx.FieldSpec{WireName: "capacity_providers"},
		"ClusterName": ubx.FieldSpec{WireName: "cluster_name"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"DefaultCapacityProviderStrategy": ubx.FieldSpec{
			WireName: "default_capacity_provider_strategy",
			Kind: "set",
			Fields: ClusterCapacityProviders_DefaultCapacityProviderStrategyFields,
		},
	},
}
