// Code generated by `ubx sdk gen` from aws_s3_access_grants_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccessGrantsInstance_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

const AccessGrantsInstance_TagsFields: FieldMap = {
  key: "key",
  value: "value",
};

export interface AccessGrantsInstanceConfig {
  /** The Amazon Resource Name (ARN) of the specified AWS Identity Center. */
  identityCenterArn?: string | Computed<string>;
  tags?: AccessGrantsInstance_Tags[] | Computed<AccessGrantsInstance_Tags[]>;
}

export interface AccessGrantsInstanceAttrs {
  /** The Amazon Resource Name (ARN) of the specified Access Grants instance. */
  accessGrantsInstanceArn: string;
  /** A unique identifier for the specified access grants instance. */
  accessGrantsInstanceId: string;
  /** The Amazon Resource Name (ARN) of the specified AWS Identity Center. */
  identityCenterArn: string;
  tags: AccessGrantsInstance_Tags[];
}

export const AccessGrantsInstance: ResourceBinding<AccessGrantsInstanceConfig, AccessGrantsInstanceAttrs> = {
  wireType: "aws_s3_access_grants_instance",
  fields: {
    identityCenterArn: "identity_center_arn",
    tags: {
      wireName: "tags",
      kind: "list",
      fields: AccessGrantsInstance_TagsFields,
    },
  },
};
