// Code generated by `ubx sdk gen` from aws_codedeploy_git_hub_account_token_names. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GitHubAccountTokenNamesConfig {
  nextToken?: string | Computed<string>;
}

export interface GitHubAccountTokenNamesAttrs {
  nextToken: string;
  tokenNameList: string[];
}

export const GitHubAccountTokenNames: DataSourceBinding<GitHubAccountTokenNamesConfig, GitHubAccountTokenNamesAttrs> = {
  wireType: "aws_codedeploy_git_hub_account_token_names",
  fields: {
    nextToken: "next_token",
  },
};
