# Code generated by `ubx sdk gen` from aws_elasticmapreduce_auto_termination_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AutoTerminationPolicy_AutoTerminationPolicy:
    idle_timeout: Any = None

@dataclasses.dataclass
class AutoTerminationPolicyConfig:
    cluster_id: Any = None

@dataclasses.dataclass
class AutoTerminationPolicyAttrs:
    # <p>An auto-termination policy for an Amazon EMR cluster. An auto-termination policy defines the amount of idle time in seconds after which a cluster automatically terminates. For alternative cluster termination options, see <a href="https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-termination.html">Control cluster termination</a>.</p>
    auto_termination_policy: Any = None
    cluster_id: Any = None

AutoTerminationPolicy = ubx.DataSourceBinding(
    wire_type="aws_elasticmapreduce_auto_termination_policy",
    fields={
        "cluster_id": ubx.FieldSpec(wire_name="cluster_id"),
    },
)
