# Code generated by `ubx sdk gen` from aws_storagegateway_local_disks. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LocalDisks_Disks:
    disk_allocation_resource: Any = None
    disk_allocation_type: Any = None
    disk_attribute_list: Any = None
    disk_id: Any = None
    disk_node: Any = None
    disk_path: Any = None
    disk_size_in_bytes: Any = None
    disk_status: Any = None

@dataclasses.dataclass
class LocalDisksConfig:
    # <p>The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.</p>
    gateway_arn: Any = None

@dataclasses.dataclass
class LocalDisksAttrs:
    disks: Any = None
    # <p>The Amazon Resource Name (ARN) of the gateway. Use the <a>ListGateways</a> operation to return a list of gateways for your account and Amazon Web Services Region.</p>
    gateway_arn: Any = None

LocalDisks = ubx.DataSourceBinding(
    wire_type="aws_storagegateway_local_disks",
    fields={
        "gateway_arn": ubx.FieldSpec(wire_name="gateway_arn"),
    },
)
