// Code generated by `ubx sdk gen` from aws_cloudfront_public_key. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PublicKeyConfig {
  comment?: string | Computed<string>;
  encodedKey: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  namePrefix?: string | Computed<string>;
}

export interface PublicKeyAttrs {
  callerReference: string;
  comment: string;
  encodedKey: string;
  etag: string;
  id: string;
  name: string;
  namePrefix: string;
}

export const PublicKey: ResourceBinding<PublicKeyConfig, PublicKeyAttrs> = {
  wireType: "aws_cloudfront_public_key",
  fields: {
    comment: "comment",
    encodedKey: "encoded_key",
    id: "id",
    name: "name",
    namePrefix: "name_prefix",
  },
};
