// Code generated by `ubx sdk gen` from aws_servicecatalog_portfolios. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Portfolios_PortfolioDetails {
  arn?: string | Computed<string>;
  createdTime?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  providerName?: string | Computed<string>;
}

export interface PortfoliosConfig {
  acceptLanguage?: string | Computed<string>;
  pageSize?: number | Computed<number>;
  pageToken?: string | Computed<string>;
}

export interface PortfoliosAttrs {
  acceptLanguage: string;
  nextPageToken: string;
  pageSize: number;
  pageToken: string;
  portfolioDetails: Portfolios_PortfolioDetails[];
}

export const Portfolios: DataSourceBinding<PortfoliosConfig, PortfoliosAttrs> = {
  wireType: "aws_servicecatalog_portfolios",
  fields: {
    acceptLanguage: "accept_language",
    pageSize: "page_size",
    pageToken: "page_token",
  },
};
