# Code generated by `ubx sdk gen` from aws_dynamodb_global_tables. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GlobalTables_GlobalTables_ReplicationGroup:
    region_name: Any = None

@dataclasses.dataclass
class GlobalTables_GlobalTables:
    global_table_name: Any = None
    replication_group: Any = None

@dataclasses.dataclass
class GlobalTablesConfig:
    exclusive_start_global_table_name: Any = None
    limit: Any = None
    region_name: Any = None

@dataclasses.dataclass
class GlobalTablesAttrs:
    exclusive_start_global_table_name: Any = None
    global_tables: Any = None
    last_evaluated_global_table_name: Any = None
    limit: Any = None
    region_name: Any = None

GlobalTables = ubx.DataSourceBinding(
    wire_type="aws_dynamodb_global_tables",
    fields={
        "exclusive_start_global_table_name": ubx.FieldSpec(wire_name="exclusive_start_global_table_name"),
        "limit": ubx.FieldSpec(wire_name="limit"),
        "region_name": ubx.FieldSpec(wire_name="region_name"),
    },
)
