// Code generated by `ubx sdk gen` from aws_config_organization_custom_rule_policy. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OrganizationCustomRulePolicyConfig {
  organizationConfigRuleName: string | Computed<string>;
}

export interface OrganizationCustomRulePolicyAttrs {
  organizationConfigRuleName: string;
  policyText: string;
}

export const OrganizationCustomRulePolicy: DataSourceBinding<OrganizationCustomRulePolicyConfig, OrganizationCustomRulePolicyAttrs> = {
  wireType: "aws_config_organization_custom_rule_policy",
  fields: {
    organizationConfigRuleName: "organization_config_rule_name",
  },
};
