// Code generated by `ubx sdk gen` from aws_s3_bucket_object_lock_configuration. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface BucketObjectLockConfiguration_Rule_DefaultRetention {
  days: number;
  mode: string;
  years: number;
}

export interface BucketObjectLockConfiguration_Rule {
  defaultRetention: BucketObjectLockConfiguration_Rule_DefaultRetention[];
}

const BucketObjectLockConfiguration_Rule_DefaultRetentionFields: FieldMap = {
  days: "days",
  mode: "mode",
  years: "years",
};

const BucketObjectLockConfiguration_RuleFields: FieldMap = {
  defaultRetention: {
    wireName: "default_retention",
    kind: "list",
    fields: BucketObjectLockConfiguration_Rule_DefaultRetentionFields,
  },
};

export interface BucketObjectLockConfigurationConfig {
  bucket: string | Computed<string>;
  expectedBucketOwner?: string | Computed<string>;
  id?: string | Computed<string>;
  objectLockEnabled?: string | Computed<string>;
  region?: string | Computed<string>;
  token?: string | Computed<string>;
  rule?: BucketObjectLockConfiguration_Rule[] | Computed<BucketObjectLockConfiguration_Rule[]>;
}

export interface BucketObjectLockConfigurationAttrs {
  bucket: string;
  expectedBucketOwner: string;
  id: string;
  objectLockEnabled: string;
  region: string;
  token: string;
  rule: BucketObjectLockConfiguration_Rule[];
}

export const BucketObjectLockConfiguration: ResourceBinding<BucketObjectLockConfigurationConfig, BucketObjectLockConfigurationAttrs> = {
  wireType: "aws_s3_bucket_object_lock_configuration",
  fields: {
    bucket: "bucket",
    expectedBucketOwner: "expected_bucket_owner",
    id: "id",
    objectLockEnabled: "object_lock_enabled",
    region: "region",
    token: "token",
    rule: {
      wireName: "rule",
      kind: "list",
      fields: BucketObjectLockConfiguration_RuleFields,
    },
  },
};
