// Code generated by `ubx sdk gen` from aws_support_app_account_alias. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccountAliasConfig {
  /** An account alias associated with a customer's account. */
  accountAlias: string | Computed<string>;
}

export interface AccountAliasAttrs {
  /** An account alias associated with a customer's account. */
  accountAlias: string;
  /** Unique identifier representing an alias tied to an account */
  accountAliasResourceId: string;
}

export const AccountAlias: ResourceBinding<AccountAliasConfig, AccountAliasAttrs> = {
  wireType: "aws_support_app_account_alias",
  fields: {
    accountAlias: "account_alias",
  },
};
