# Code generated by `ubx sdk gen` from aws_wafv2_available_managed_rule_groups. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AvailableManagedRuleGroups_ManagedRuleGroups:
    description: Any = None
    name: Any = None
    vendor_name: Any = None
    versioning_supported: Any = None

@dataclasses.dataclass
class AvailableManagedRuleGroupsConfig:
    limit: Any = None
    next_marker: Any = None
    scope: Any = None

@dataclasses.dataclass
class AvailableManagedRuleGroupsAttrs:
    limit: Any = None
    managed_rule_groups: Any = None
    next_marker: Any = None
    scope: Any = None

AvailableManagedRuleGroups = ubx.DataSourceBinding(
    wire_type="aws_wafv2_available_managed_rule_groups",
    fields={
        "limit": ubx.FieldSpec(wire_name="limit"),
        "next_marker": ubx.FieldSpec(wire_name="next_marker"),
        "scope": ubx.FieldSpec(wire_name="scope"),
    },
)
