// Code generated by `ubx sdk gen` from aws_sage_maker_mlflow_app. DO NOT EDIT.
package sage

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MakerMlflowApp_Tags struct {
	Key any
	Value any
}

var MakerMlflowApp_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type MakerMlflowAppConfig struct {
	// The S3 URI for a general purpose bucket to use as the MLflow App artifact store.
	ArtifactStoreUri any
	// Whether to enable or disable automatic registration of new MLflow models to the SageMaker Model Registry.
	ModelRegistrationMode any
	// The name of the MLflow App.
	Name any
	// The Amazon Resource Name (ARN) for an IAM role in your account that the MLflow App uses to access the artifact store in Amazon S3.
	RoleArn any
	// Tags to associate with the MLflow App.
	Tags any
	// The day and time of the week in Coordinated Universal Time (UTC) 24-hour standard time that weekly maintenance updates are scheduled. For example: Tue:03:30.
	WeeklyMaintenanceWindowStart any
}

type MakerMlflowAppAttrs struct {
	// The Amazon Resource Name (ARN) of the MLflow App.
	Arn any
	// The S3 URI for a general purpose bucket to use as the MLflow App artifact store.
	ArtifactStoreUri any
	// The date and time that the MLflow App was created.
	CreationTime any
	// The date and time that the MLflow App was last modified.
	LastModifiedTime any
	// The server-generated identifier of the MLflow App.
	MlflowAppId any
	// The MLflow version used by the MLflow App.
	MlflowVersion any
	// Whether to enable or disable automatic registration of new MLflow models to the SageMaker Model Registry.
	ModelRegistrationMode any
	// The name of the MLflow App.
	Name any
	// The Amazon Resource Name (ARN) for an IAM role in your account that the MLflow App uses to access the artifact store in Amazon S3.
	RoleArn any
	// The status of the MLflow App.
	Status any
	// Tags to associate with the MLflow App.
	Tags any
	// The day and time of the week in Coordinated Universal Time (UTC) 24-hour standard time that weekly maintenance updates are scheduled. For example: Tue:03:30.
	WeeklyMaintenanceWindowStart any
}

var MakerMlflowApp = ubx.ResourceBinding{
	WireType: "aws_sage_maker_mlflow_app",
	Fields: ubx.FieldMap{
		"ArtifactStoreUri": ubx.FieldSpec{WireName: "artifact_store_uri"},
		"ModelRegistrationMode": ubx.FieldSpec{WireName: "model_registration_mode"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"RoleArn": ubx.FieldSpec{WireName: "role_arn"},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: MakerMlflowApp_TagsFields,
		},
		"WeeklyMaintenanceWindowStart": ubx.FieldSpec{WireName: "weekly_maintenance_window_start"},
	},
}
