// Code generated by `ubx sdk gen` from aws_sagemaker_pipeline. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Pipeline_ParallelismConfiguration {
  maxParallelExecutionSteps: number;
}

export interface Pipeline_PipelineDefinitionS3Location {
  bucket: string;
  objectKey: string;
  versionId: string;
}

const Pipeline_ParallelismConfigurationFields: FieldMap = {
  maxParallelExecutionSteps: "max_parallel_execution_steps",
};

const Pipeline_PipelineDefinitionS3LocationFields: FieldMap = {
  bucket: "bucket",
  objectKey: "object_key",
  versionId: "version_id",
};

export interface PipelineConfig {
  id?: string | Computed<string>;
  pipelineDefinition?: string | Computed<string>;
  pipelineDescription?: string | Computed<string>;
  pipelineDisplayName: string | Computed<string>;
  pipelineName: string | Computed<string>;
  region?: string | Computed<string>;
  roleArn?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tagsAll?: Record<string, string> | Computed<Record<string, string>>;
  parallelismConfiguration?: Pipeline_ParallelismConfiguration[] | Computed<Pipeline_ParallelismConfiguration[]>;
  pipelineDefinitionS3Location?: Pipeline_PipelineDefinitionS3Location[] | Computed<Pipeline_PipelineDefinitionS3Location[]>;
}

export interface PipelineAttrs {
  arn: string;
  id: string;
  pipelineDefinition: string;
  pipelineDescription: string;
  pipelineDisplayName: string;
  pipelineName: string;
  region: string;
  roleArn: string;
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  parallelismConfiguration: Pipeline_ParallelismConfiguration[];
  pipelineDefinitionS3Location: Pipeline_PipelineDefinitionS3Location[];
}

export const Pipeline: ResourceBinding<PipelineConfig, PipelineAttrs> = {
  wireType: "aws_sagemaker_pipeline",
  fields: {
    id: "id",
    pipelineDefinition: "pipeline_definition",
    pipelineDescription: "pipeline_description",
    pipelineDisplayName: "pipeline_display_name",
    pipelineName: "pipeline_name",
    region: "region",
    roleArn: "role_arn",
    tags: "tags",
    tagsAll: "tags_all",
    parallelismConfiguration: {
      wireName: "parallelism_configuration",
      kind: "list",
      fields: Pipeline_ParallelismConfigurationFields,
    },
    pipelineDefinitionS3Location: {
      wireName: "pipeline_definition_s3_location",
      kind: "list",
      fields: Pipeline_PipelineDefinitionS3LocationFields,
    },
  },
};
