# Code generated by `ubx sdk gen` from aws_dev_ops_agent_service. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Service_Tags:
    key: Any = None
    value: Any = None

_Service_TagsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value": ubx.FieldSpec(wire_name="value"),
}

@dataclasses.dataclass
class ServiceConfig:
    # The name of the private connection to use for OAuth token exchange requests only. Cannot be specified when PrivateConnectionName is provided.
    exchange_url_private_connection_name: Any = None
    # The ARN of the KMS key to use for encryption.
    kms_key_arn: Any = None
    # The name of the private connection to use for VPC connectivity.
    private_connection_name: Any = None
    # Service-specific configuration details - MCPServerSigV4 supports in-place updates; GitLab (TokenValue), MCPServer (ApiKey or BearerToken credential rotation), MCPServerNewRelic (ApiKey rotation), and MCPServerGrafana (BearerToken rotation) support in-place credential rotation; all other service types and fields require replacement when modified
    service_details: Any = None
    # The type of service being registered
    service_type: Any = None
    # An array of key-value pairs to apply to this resource.
    tags: Any = None
    # The name of the private connection to use for API calls (target URL) only. Cannot be specified when PrivateConnectionName is provided.
    target_url_private_connection_name: Any = None

@dataclasses.dataclass
class ServiceAttrs:
    # List of accessible resources for this service
    accessible_resources: Any = None
    # Additional details specific to the service type returned after registration
    additional_service_details: Any = None
    # The Amazon Resource Name (ARN) of the Service.
    arn: Any = None
    # The name of the private connection to use for OAuth token exchange requests only. Cannot be specified when PrivateConnectionName is provided.
    exchange_url_private_connection_name: Any = None
    # The ARN of the KMS key to use for encryption.
    kms_key_arn: Any = None
    # The name of the private connection to use for VPC connectivity.
    private_connection_name: Any = None
    # Service-specific configuration details - MCPServerSigV4 supports in-place updates; GitLab (TokenValue), MCPServer (ApiKey or BearerToken credential rotation), MCPServerNewRelic (ApiKey rotation), and MCPServerGrafana (BearerToken rotation) support in-place credential rotation; all other service types and fields require replacement when modified
    service_details: Any = None
    # The unique identifier of the service
    service_id: Any = None
    # The type of service being registered
    service_type: Any = None
    # An array of key-value pairs to apply to this resource.
    tags: Any = None
    # The name of the private connection to use for API calls (target URL) only. Cannot be specified when PrivateConnectionName is provided.
    target_url_private_connection_name: Any = None

Service = ubx.ResourceBinding(
    wire_type="aws_dev_ops_agent_service",
    fields={
        "exchange_url_private_connection_name": ubx.FieldSpec(wire_name="exchange_url_private_connection_name"),
        "kms_key_arn": ubx.FieldSpec(wire_name="kms_key_arn"),
        "private_connection_name": ubx.FieldSpec(wire_name="private_connection_name"),
        "service_details": ubx.FieldSpec(wire_name="service_details"),
        "service_type": ubx.FieldSpec(wire_name="service_type"),
        "tags": ubx.FieldSpec(
            wire_name="tags",
            kind="list",
            fields=_Service_TagsFields,
        ),
        "target_url_private_connection_name": ubx.FieldSpec(wire_name="target_url_private_connection_name"),
    },
)
