# Code generated by `ubx sdk gen` from aws_ssmquicksetup_configuration_manager. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConfigurationManager_ConfigurationDefinition:
    id: Any = None
    local_deployment_administration_role_arn: Any = None
    local_deployment_execution_role_name: Any = None
    parameters: Any = None
    type: Any = None
    type_version: Any = None

@dataclasses.dataclass
class ConfigurationManager_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_ConfigurationManager_ConfigurationDefinitionFields = {
    "id": ubx.FieldSpec(wire_name="id"),
    "local_deployment_administration_role_arn": ubx.FieldSpec(wire_name="local_deployment_administration_role_arn"),
    "local_deployment_execution_role_name": ubx.FieldSpec(wire_name="local_deployment_execution_role_name"),
    "parameters": ubx.FieldSpec(wire_name="parameters"),
    "type": ubx.FieldSpec(wire_name="type"),
    "type_version": ubx.FieldSpec(wire_name="type_version"),
}

_ConfigurationManager_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConfigurationManagerConfig:
    description: Any = None
    name: Any = None
    region: Any = None
    tags: Any = None
    configuration_definition: Any = None
    timeouts: Any = None

ConfigurationManager = ubx.ResourceBinding(
    wire_type="aws_ssmquicksetup_configuration_manager",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "name": ubx.FieldSpec(wire_name="name"),
        "region": ubx.FieldSpec(wire_name="region"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "configuration_definition": ubx.FieldSpec(
            wire_name="configuration_definition",
            kind="list",
            fields=_ConfigurationManager_ConfigurationDefinitionFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ConfigurationManager_TimeoutsFields,
        ),
    },
)
