// Code generated by `ubx sdk gen` from aws_transfer_tags_for_resource. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TagsForResource_Tags {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface TagsForResourceConfig {
  arn: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
}

export interface TagsForResourceAttrs {
  arn: string;
  maxResults: number;
  nextToken: string;
  tags: TagsForResource_Tags[];
}

export const TagsForResource: DataSourceBinding<TagsForResourceConfig, TagsForResourceAttrs> = {
  wireType: "aws_transfer_tags_for_resource",
  fields: {
    arn: "arn",
    maxResults: "max_results",
    nextToken: "next_token",
  },
};
