// Code generated by `ubx sdk gen` from aws_odb_gi_versions. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GiVersions_GiVersions {
  version?: string | Computed<string>;
}

export interface GiVersionsConfig {
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
  shape?: string | Computed<string>;
}

export interface GiVersionsAttrs {
  giVersions: GiVersions_GiVersions[];
  maxResults: number;
  nextToken: string;
  shape: string;
}

export const GiVersions: DataSourceBinding<GiVersionsConfig, GiVersionsAttrs> = {
  wireType: "aws_odb_gi_versions",
  fields: {
    maxResults: "max_results",
    nextToken: "next_token",
    shape: "shape",
  },
};
