// Code generated by `ubx sdk gen` from aws_api_iotdeviceadvisor_suite_run. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiIotdeviceadvisorSuiteRun_SuiteRunConfiguration_PrimaryDevice {
  certificateArn?: string | Computed<string>;
  deviceRoleArn?: string | Computed<string>;
  thingArn?: string | Computed<string>;
}

export interface ApiIotdeviceadvisorSuiteRun_SuiteRunConfiguration {
  parallelRun?: boolean | Computed<boolean>;
  /** <p>Information of a test device. A thing ARN, certificate ARN or device role ARN is required.</p> */
  primaryDevice: ApiIotdeviceadvisorSuiteRun_SuiteRunConfiguration_PrimaryDevice | Computed<ApiIotdeviceadvisorSuiteRun_SuiteRunConfiguration_PrimaryDevice>;
  selectedTestList?: string[] | Computed<string[]>;
}

export interface ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests_TestScenarios {
  failure?: string | Computed<string>;
  status?: string | Computed<string>;
  systemMessage?: string | Computed<string>;
  testCaseScenarioId?: string | Computed<string>;
  testCaseScenarioType?: string | Computed<string>;
}

export interface ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests {
  endTime?: string | Computed<string>;
  failure?: string | Computed<string>;
  logUrl?: string | Computed<string>;
  startTime?: string | Computed<string>;
  status?: string | Computed<string>;
  testCaseDefinitionId?: string | Computed<string>;
  testCaseDefinitionName?: string | Computed<string>;
  testCaseRunId?: string | Computed<string>;
  testScenarios?: ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests_TestScenarios[] | Computed<ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests_TestScenarios[]>;
  warnings?: string | Computed<string>;
}

export interface ApiIotdeviceadvisorSuiteRun_TestResult_Groups {
  groupId?: string | Computed<string>;
  groupName?: string | Computed<string>;
  tests?: ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests[] | Computed<ApiIotdeviceadvisorSuiteRun_TestResult_Groups_Tests[]>;
}

export interface ApiIotdeviceadvisorSuiteRun_TestResult {
  /** <p>Group Result list.</p> */
  groups?: ApiIotdeviceadvisorSuiteRun_TestResult_Groups[] | Computed<ApiIotdeviceadvisorSuiteRun_TestResult_Groups[]>;
}

export interface ApiIotdeviceadvisorSuiteRunConfig {
  suiteDefinitionId: string | Computed<string>;
  suiteRunId: string | Computed<string>;
}

export interface ApiIotdeviceadvisorSuiteRunAttrs {
  endTime: string;
  errorReason: string;
  startTime: string;
  status: string;
  suiteDefinitionId: string;
  suiteDefinitionVersion: string;
  suiteRunArn: string;
  /** <p>Gets suite run configuration.</p> */
  suiteRunConfiguration: ApiIotdeviceadvisorSuiteRun_SuiteRunConfiguration;
  suiteRunId: string;
  tags: Record<string, string>;
  /** <p>Show each group result.</p> */
  testResult: ApiIotdeviceadvisorSuiteRun_TestResult;
}

export const ApiIotdeviceadvisorSuiteRun: DataSourceBinding<ApiIotdeviceadvisorSuiteRunConfig, ApiIotdeviceadvisorSuiteRunAttrs> = {
  wireType: "aws_api_iotdeviceadvisor_suite_run",
  fields: {
    suiteDefinitionId: "suite_definition_id",
    suiteRunId: "suite_run_id",
  },
};
