// Code generated by `ubx sdk gen` from aws_security_hub_delegated_admin. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type HubDelegatedAdminConfig struct {
	// The AWS-account identifier of the account to designate as the Security Hub CSPM administrator account.
	AdminAccountId any
}

type HubDelegatedAdminAttrs struct {
	// The AWS-account identifier of the account to designate as the Security Hub CSPM administrator account.
	AdminAccountId any
	DelegatedAdminIdentifier any
	Status any
}

var HubDelegatedAdmin = ubx.ResourceBinding{
	WireType: "aws_security_hub_delegated_admin",
	Fields: ubx.FieldMap{
		"AdminAccountId": ubx.FieldSpec{WireName: "admin_account_id"},
	},
}
