# Code generated by `ubx sdk gen` from aws_ssoadmin_managed_policy_attachment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagedPolicyAttachment_Timeouts:
    create: Any = None
    delete: Any = None

_ManagedPolicyAttachment_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
}

@dataclasses.dataclass
class ManagedPolicyAttachmentConfig:
    id: Any = None
    instance_arn: Any = None
    managed_policy_arn: Any = None
    permission_set_arn: Any = None
    region: Any = None
    timeouts: Any = None

ManagedPolicyAttachment = ubx.ResourceBinding(
    wire_type="aws_ssoadmin_managed_policy_attachment",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "instance_arn": ubx.FieldSpec(wire_name="instance_arn"),
        "managed_policy_arn": ubx.FieldSpec(wire_name="managed_policy_arn"),
        "permission_set_arn": ubx.FieldSpec(wire_name="permission_set_arn"),
        "region": ubx.FieldSpec(wire_name="region"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagedPolicyAttachment_TimeoutsFields,
        ),
    },
)
