// Code generated by `ubx sdk gen` from aws_route53_global_resolver_hosted_zone_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GlobalResolverHostedZoneAssociationConfig {
  hostedZoneId: string | Computed<string>;
  name: string | Computed<string>;
  resourceArn: string | Computed<string>;
}

export interface GlobalResolverHostedZoneAssociationAttrs {
  createdAt: string;
  hostedZoneAssociationId: string;
  hostedZoneId: string;
  hostedZoneName: string;
  name: string;
  resourceArn: string;
  status: string;
  updatedAt: string;
}

export const GlobalResolverHostedZoneAssociation: ResourceBinding<GlobalResolverHostedZoneAssociationConfig, GlobalResolverHostedZoneAssociationAttrs> = {
  wireType: "aws_route53_global_resolver_hosted_zone_association",
  fields: {
    hostedZoneId: "hosted_zone_id",
    name: "name",
    resourceArn: "resource_arn",
  },
};
