// Code generated by `ubx sdk gen` from aws_swf_workflow_type. DO NOT EDIT.
package swf

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type WorkflowType_Configuration_DefaultTaskList struct {
	Name any
}

type WorkflowType_Configuration struct {
	DefaultChildPolicy any
	DefaultExecutionStartToCloseTimeout any
	DefaultLambdaRole any
	// <p>Represents a task list.</p>
	DefaultTaskList any
	DefaultTaskPriority any
	DefaultTaskStartToCloseTimeout any
}

type WorkflowType_TypeInfo_WorkflowType struct {
	Name any
	Version any
}

type WorkflowType_TypeInfo struct {
	CreationDate any
	DeprecationDate any
	Description any
	Status any
	// <p>Represents a workflow type.</p>
	WorkflowType any
}

var WorkflowType_TypeInfo_WorkflowTypeFields = ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"Version": ubx.FieldSpec{WireName: "version"},
	}

type WorkflowTypeConfig struct {
	Domain any
	// <p>Represents a workflow type.</p>
	WorkflowType any
}

type WorkflowTypeAttrs struct {
	// <p>The configuration settings of a workflow type.</p>
	Configuration any
	Domain any
	// <p>Contains information about a workflow type.</p>
	TypeInfo any
	// <p>Represents a workflow type.</p>
	WorkflowType any
}

var WorkflowType = ubx.DataSourceBinding{
	WireType: "aws_swf_workflow_type",
	Fields: ubx.FieldMap{
		"Domain": ubx.FieldSpec{WireName: "domain"},
		"WorkflowType": ubx.FieldSpec{
			WireName: "workflow_type",
			Kind: "object",
			Fields: WorkflowType_TypeInfo_WorkflowTypeFields,
		},
	},
}
