# Code generated by `ubx sdk gen` from aws_lakeformation_data_lake_principal. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DataLakePrincipalConfig:
    pass

@dataclasses.dataclass
class DataLakePrincipalAttrs:
    identity: Any = None

DataLakePrincipal = ubx.DataSourceBinding(
    wire_type="aws_lakeformation_data_lake_principal",
    fields={
    },
)
