# Code generated by `ubx sdk gen` from aws_location_tracker_consumer. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TrackerConsumerConfig:
    # The Amazon Resource Name (ARN) of the consumer resource (such as an EventBridge rule) that will receive location updates from the tracker. (AI-inferred)
    consumer_arn: Any = None
    # The name of the Amazon Location Service tracker that the consumer (such as a geofence collection) is associated with, linking the consumer to receive position updates from that tracker. (AI-inferred)
    tracker_name: Any = None

@dataclasses.dataclass
class TrackerConsumerAttrs:
    # The Amazon Resource Name (ARN) of the consumer resource (such as an EventBridge rule) that will receive location updates from the tracker. (AI-inferred)
    consumer_arn: Any = None
    # The name of the Amazon Location Service tracker that the consumer (such as a geofence collection) is associated with, linking the consumer to receive position updates from that tracker. (AI-inferred)
    tracker_name: Any = None

TrackerConsumer = ubx.ResourceBinding(
    wire_type="aws_location_tracker_consumer",
    fields={
        "consumer_arn": ubx.FieldSpec(wire_name="consumer_arn"),
        "tracker_name": ubx.FieldSpec(wire_name="tracker_name"),
    },
)
