# Code generated by `ubx sdk gen` from aws_neptune_subnet_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SubnetGroupConfig:
    description: Any = None
    id: Any = None
    name: Any = None
    name_prefix: Any = None
    region: Any = None
    subnet_ids: Any = None
    tags: Any = None
    tags_all: Any = None

SubnetGroup = ubx.ResourceBinding(
    wire_type="aws_neptune_subnet_group",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "name_prefix": ubx.FieldSpec(wire_name="name_prefix"),
        "region": ubx.FieldSpec(wire_name="region"),
        "subnet_ids": ubx.FieldSpec(wire_name="subnet_ids"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
    },
)
