// Code generated by `ubx sdk gen` from aws_rds_cluster_role_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ClusterRoleAssociation_Timeouts {
  create: string;
  delete: string;
}

const ClusterRoleAssociation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface ClusterRoleAssociationConfig {
  dbClusterIdentifier: string | Computed<string>;
  featureName?: string | Computed<string>;
  id?: string | Computed<string>;
  region?: string | Computed<string>;
  roleArn: string | Computed<string>;
  timeouts?: ClusterRoleAssociation_Timeouts | Computed<ClusterRoleAssociation_Timeouts>;
}

export interface ClusterRoleAssociationAttrs {
  dbClusterIdentifier: string;
  featureName: string;
  id: string;
  region: string;
  roleArn: string;
  timeouts: ClusterRoleAssociation_Timeouts;
}

export const ClusterRoleAssociation: ResourceBinding<ClusterRoleAssociationConfig, ClusterRoleAssociationAttrs> = {
  wireType: "aws_rds_cluster_role_association",
  fields: {
    dbClusterIdentifier: "db_cluster_identifier",
    featureName: "feature_name",
    id: "id",
    region: "region",
    roleArn: "role_arn",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ClusterRoleAssociation_TimeoutsFields,
    },
  },
};
