// Code generated by `ubx sdk gen` from aws_rds_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Cluster_MasterUserSecret {
  kmsKeyId: string;
  secretArn: string;
  secretStatus: string;
}

export interface Cluster_RestoreToPointInTime {
  restoreToTime: string;
  restoreType: string;
  sourceClusterIdentifier: string;
  sourceClusterResourceId: string;
  useLatestRestorableTime: boolean;
}

export interface Cluster_S3Import {
  bucketName: string;
  bucketPrefix: string;
  ingestionRole: string;
  sourceEngine: string;
  sourceEngineVersion: string;
}

export interface Cluster_ScalingConfiguration {
  autoPause: boolean;
  maxCapacity: number;
  minCapacity: number;
  secondsBeforeTimeout: number;
  secondsUntilAutoPause: number;
  timeoutAction: string;
}

export interface Cluster_Serverlessv2ScalingConfiguration {
  maxCapacity: number;
  minCapacity: number;
  secondsUntilAutoPause: number;
}

export interface Cluster_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Cluster_RestoreToPointInTimeFields: FieldMap = {
  restoreToTime: "restore_to_time",
  restoreType: "restore_type",
  sourceClusterIdentifier: "source_cluster_identifier",
  sourceClusterResourceId: "source_cluster_resource_id",
  useLatestRestorableTime: "use_latest_restorable_time",
};

const Cluster_S3ImportFields: FieldMap = {
  bucketName: "bucket_name",
  bucketPrefix: "bucket_prefix",
  ingestionRole: "ingestion_role",
  sourceEngine: "source_engine",
  sourceEngineVersion: "source_engine_version",
};

const Cluster_ScalingConfigurationFields: FieldMap = {
  autoPause: "auto_pause",
  maxCapacity: "max_capacity",
  minCapacity: "min_capacity",
  secondsBeforeTimeout: "seconds_before_timeout",
  secondsUntilAutoPause: "seconds_until_auto_pause",
  timeoutAction: "timeout_action",
};

const Cluster_Serverlessv2ScalingConfigurationFields: FieldMap = {
  maxCapacity: "max_capacity",
  minCapacity: "min_capacity",
  secondsUntilAutoPause: "seconds_until_auto_pause",
};

const Cluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ClusterConfig {
  allocatedStorage?: number | Computed<number>;
  allowMajorVersionUpgrade?: boolean | Computed<boolean>;
  applyImmediately?: boolean | Computed<boolean>;
  autoMinorVersionUpgrade?: boolean | Computed<boolean>;
  availabilityZones?: string[] | Computed<string[]>;
  backtrackWindow?: number | Computed<number>;
  backupRetentionPeriod?: number | Computed<number>;
  caCertificateIdentifier?: string | Computed<string>;
  clusterIdentifier?: string | Computed<string>;
  clusterIdentifierPrefix?: string | Computed<string>;
  clusterMembers?: string[] | Computed<string[]>;
  clusterScalabilityType?: string | Computed<string>;
  copyTagsToSnapshot?: boolean | Computed<boolean>;
  databaseInsightsMode?: string | Computed<string>;
  databaseName?: string | Computed<string>;
  dbClusterInstanceClass?: string | Computed<string>;
  dbClusterParameterGroupName?: string | Computed<string>;
  dbInstanceParameterGroupName?: string | Computed<string>;
  dbSubnetGroupName?: string | Computed<string>;
  dbSystemId?: string | Computed<string>;
  deleteAutomatedBackups?: boolean | Computed<boolean>;
  deletionProtection?: boolean | Computed<boolean>;
  domain?: string | Computed<string>;
  domainIamRoleName?: string | Computed<string>;
  enableGlobalWriteForwarding?: boolean | Computed<boolean>;
  enableHttpEndpoint?: boolean | Computed<boolean>;
  enableLocalWriteForwarding?: boolean | Computed<boolean>;
  enabledCloudwatchLogsExports?: string[] | Computed<string[]>;
  engine: string | Computed<string>;
  engineLifecycleSupport?: string | Computed<string>;
  engineMode?: string | Computed<string>;
  engineVersion?: string | Computed<string>;
  finalSnapshotIdentifier?: string | Computed<string>;
  globalClusterIdentifier?: string | Computed<string>;
  iamDatabaseAuthenticationEnabled?: boolean | Computed<boolean>;
  iamRoles?: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  iops?: number | Computed<number>;
  kmsKeyId?: string | Computed<string>;
  manageMasterUserPassword?: boolean | Computed<boolean>;
  masterPassword?: string | Computed<string>;
  masterPasswordWo?: string | Computed<string>;
  masterPasswordWoVersion?: number | Computed<number>;
  masterUserSecretKmsKeyId?: string | Computed<string>;
  masterUsername?: string | Computed<string>;
  monitoringInterval?: number | Computed<number>;
  monitoringRoleArn?: string | Computed<string>;
  networkType?: string | Computed<string>;
  performanceInsightsEnabled?: boolean | Computed<boolean>;
  performanceInsightsKmsKeyId?: string | Computed<string>;
  performanceInsightsRetentionPeriod?: number | Computed<number>;
  port?: number | Computed<number>;
  preferredBackupWindow?: string | Computed<string>;
  preferredMaintenanceWindow?: string | Computed<string>;
  region?: string | Computed<string>;
  replicationSourceIdentifier?: string | Computed<string>;
  skipFinalSnapshot?: boolean | Computed<boolean>;
  snapshotIdentifier?: string | Computed<string>;
  sourceRegion?: string | Computed<string>;
  storageEncrypted?: boolean | Computed<boolean>;
  storageType?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tagsAll?: Record<string, string> | Computed<Record<string, string>>;
  vpcSecurityGroupIds?: string[] | Computed<string[]>;
  restoreToPointInTime?: Cluster_RestoreToPointInTime[] | Computed<Cluster_RestoreToPointInTime[]>;
  s3Import?: Cluster_S3Import[] | Computed<Cluster_S3Import[]>;
  scalingConfiguration?: Cluster_ScalingConfiguration[] | Computed<Cluster_ScalingConfiguration[]>;
  serverlessv2ScalingConfiguration?: Cluster_Serverlessv2ScalingConfiguration[] | Computed<Cluster_Serverlessv2ScalingConfiguration[]>;
  timeouts?: Cluster_Timeouts | Computed<Cluster_Timeouts>;
}

export interface ClusterAttrs {
  allocatedStorage: number;
  allowMajorVersionUpgrade: boolean;
  applyImmediately: boolean;
  arn: string;
  autoMinorVersionUpgrade: boolean;
  availabilityZones: string[];
  backtrackWindow: number;
  backupRetentionPeriod: number;
  caCertificateIdentifier: string;
  caCertificateValidTill: string;
  clusterIdentifier: string;
  clusterIdentifierPrefix: string;
  clusterMembers: string[];
  clusterResourceId: string;
  clusterScalabilityType: string;
  copyTagsToSnapshot: boolean;
  databaseInsightsMode: string;
  databaseName: string;
  dbClusterInstanceClass: string;
  dbClusterParameterGroupName: string;
  dbInstanceParameterGroupName: string;
  dbSubnetGroupName: string;
  dbSystemId: string;
  deleteAutomatedBackups: boolean;
  deletionProtection: boolean;
  domain: string;
  domainIamRoleName: string;
  enableGlobalWriteForwarding: boolean;
  enableHttpEndpoint: boolean;
  enableLocalWriteForwarding: boolean;
  enabledCloudwatchLogsExports: string[];
  endpoint: string;
  engine: string;
  engineLifecycleSupport: string;
  engineMode: string;
  engineVersion: string;
  engineVersionActual: string;
  finalSnapshotIdentifier: string;
  globalClusterIdentifier: string;
  hostedZoneId: string;
  iamDatabaseAuthenticationEnabled: boolean;
  iamRoles: string[];
  id: string;
  iops: number;
  kmsKeyId: string;
  manageMasterUserPassword: boolean;
  masterPassword: string;
  masterPasswordWo: string;
  masterPasswordWoVersion: number;
  masterUserSecret: Cluster_MasterUserSecret[];
  masterUserSecretKmsKeyId: string;
  masterUsername: string;
  monitoringInterval: number;
  monitoringRoleArn: string;
  networkType: string;
  performanceInsightsEnabled: boolean;
  performanceInsightsKmsKeyId: string;
  performanceInsightsRetentionPeriod: number;
  port: number;
  preferredBackupWindow: string;
  preferredMaintenanceWindow: string;
  readerEndpoint: string;
  region: string;
  replicationSourceIdentifier: string;
  skipFinalSnapshot: boolean;
  snapshotIdentifier: string;
  sourceRegion: string;
  storageEncrypted: boolean;
  storageType: string;
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  upgradeRolloutOrder: string;
  vpcSecurityGroupIds: string[];
  restoreToPointInTime: Cluster_RestoreToPointInTime[];
  s3Import: Cluster_S3Import[];
  scalingConfiguration: Cluster_ScalingConfiguration[];
  serverlessv2ScalingConfiguration: Cluster_Serverlessv2ScalingConfiguration[];
  timeouts: Cluster_Timeouts;
}

export const Cluster: ResourceBinding<ClusterConfig, ClusterAttrs> = {
  wireType: "aws_rds_cluster",
  fields: {
    allocatedStorage: "allocated_storage",
    allowMajorVersionUpgrade: "allow_major_version_upgrade",
    applyImmediately: "apply_immediately",
    autoMinorVersionUpgrade: "auto_minor_version_upgrade",
    availabilityZones: "availability_zones",
    backtrackWindow: "backtrack_window",
    backupRetentionPeriod: "backup_retention_period",
    caCertificateIdentifier: "ca_certificate_identifier",
    clusterIdentifier: "cluster_identifier",
    clusterIdentifierPrefix: "cluster_identifier_prefix",
    clusterMembers: "cluster_members",
    clusterScalabilityType: "cluster_scalability_type",
    copyTagsToSnapshot: "copy_tags_to_snapshot",
    databaseInsightsMode: "database_insights_mode",
    databaseName: "database_name",
    dbClusterInstanceClass: "db_cluster_instance_class",
    dbClusterParameterGroupName: "db_cluster_parameter_group_name",
    dbInstanceParameterGroupName: "db_instance_parameter_group_name",
    dbSubnetGroupName: "db_subnet_group_name",
    dbSystemId: "db_system_id",
    deleteAutomatedBackups: "delete_automated_backups",
    deletionProtection: "deletion_protection",
    domain: "domain",
    domainIamRoleName: "domain_iam_role_name",
    enableGlobalWriteForwarding: "enable_global_write_forwarding",
    enableHttpEndpoint: "enable_http_endpoint",
    enableLocalWriteForwarding: "enable_local_write_forwarding",
    enabledCloudwatchLogsExports: "enabled_cloudwatch_logs_exports",
    engine: "engine",
    engineLifecycleSupport: "engine_lifecycle_support",
    engineMode: "engine_mode",
    engineVersion: "engine_version",
    finalSnapshotIdentifier: "final_snapshot_identifier",
    globalClusterIdentifier: "global_cluster_identifier",
    iamDatabaseAuthenticationEnabled: "iam_database_authentication_enabled",
    iamRoles: "iam_roles",
    id: "id",
    iops: "iops",
    kmsKeyId: "kms_key_id",
    manageMasterUserPassword: "manage_master_user_password",
    masterPassword: "master_password",
    masterPasswordWo: "master_password_wo",
    masterPasswordWoVersion: "master_password_wo_version",
    masterUserSecretKmsKeyId: "master_user_secret_kms_key_id",
    masterUsername: "master_username",
    monitoringInterval: "monitoring_interval",
    monitoringRoleArn: "monitoring_role_arn",
    networkType: "network_type",
    performanceInsightsEnabled: "performance_insights_enabled",
    performanceInsightsKmsKeyId: "performance_insights_kms_key_id",
    performanceInsightsRetentionPeriod: "performance_insights_retention_period",
    port: "port",
    preferredBackupWindow: "preferred_backup_window",
    preferredMaintenanceWindow: "preferred_maintenance_window",
    region: "region",
    replicationSourceIdentifier: "replication_source_identifier",
    skipFinalSnapshot: "skip_final_snapshot",
    snapshotIdentifier: "snapshot_identifier",
    sourceRegion: "source_region",
    storageEncrypted: "storage_encrypted",
    storageType: "storage_type",
    tags: "tags",
    tagsAll: "tags_all",
    vpcSecurityGroupIds: "vpc_security_group_ids",
    restoreToPointInTime: {
      wireName: "restore_to_point_in_time",
      kind: "list",
      fields: Cluster_RestoreToPointInTimeFields,
    },
    s3Import: {
      wireName: "s3_import",
      kind: "list",
      fields: Cluster_S3ImportFields,
    },
    scalingConfiguration: {
      wireName: "scaling_configuration",
      kind: "list",
      fields: Cluster_ScalingConfigurationFields,
    },
    serverlessv2ScalingConfiguration: {
      wireName: "serverlessv2_scaling_configuration",
      kind: "list",
      fields: Cluster_Serverlessv2ScalingConfigurationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Cluster_TimeoutsFields,
    },
  },
};
