// Code generated by `ubx sdk gen` from aws_lightsail_auto_snapshots. DO NOT EDIT.
package lightsail

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AutoSnapshots_AutoSnapshots_FromAttachedDisks struct {
	Path any
	SizeInGb any
}

type AutoSnapshots_AutoSnapshots struct {
	CreatedAt any
	Date any
	FromAttachedDisks any
	Status any
}

type AutoSnapshotsConfig struct {
	ResourceName any
}

type AutoSnapshotsAttrs struct {
	AutoSnapshots any
	ResourceName any
	ResourceType any
}

var AutoSnapshots = ubx.DataSourceBinding{
	WireType: "aws_lightsail_auto_snapshots",
	Fields: ubx.FieldMap{
		"ResourceName": ubx.FieldSpec{WireName: "resource_name"},
	},
}
