// Code generated by `ubx sdk gen` from aws_fsx_lustre_file_system. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LustreFileSystem_DataReadCacheConfiguration {
  size: number;
  sizingMode: string;
}

export interface LustreFileSystem_LogConfiguration {
  destination: string;
  level: string;
}

export interface LustreFileSystem_MetadataConfiguration {
  iops: number;
  mode: string;
}

export interface LustreFileSystem_RootSquashConfiguration {
  noSquashNids: string[];
  rootSquash: string;
}

export interface LustreFileSystem_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const LustreFileSystem_DataReadCacheConfigurationFields: FieldMap = {
  size: "size",
  sizingMode: "sizing_mode",
};

const LustreFileSystem_LogConfigurationFields: FieldMap = {
  destination: "destination",
  level: "level",
};

const LustreFileSystem_MetadataConfigurationFields: FieldMap = {
  iops: "iops",
  mode: "mode",
};

const LustreFileSystem_RootSquashConfigurationFields: FieldMap = {
  noSquashNids: "no_squash_nids",
  rootSquash: "root_squash",
};

const LustreFileSystem_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface LustreFileSystemConfig {
  autoImportPolicy?: string | Computed<string>;
  automaticBackupRetentionDays?: number | Computed<number>;
  backupId?: string | Computed<string>;
  copyTagsToBackups?: boolean | Computed<boolean>;
  dailyAutomaticBackupStartTime?: string | Computed<string>;
  dataCompressionType?: string | Computed<string>;
  deploymentType?: string | Computed<string>;
  driveCacheType?: string | Computed<string>;
  efaEnabled?: boolean | Computed<boolean>;
  exportPath?: string | Computed<string>;
  fileSystemTypeVersion?: string | Computed<string>;
  finalBackupTags?: Record<string, string> | Computed<Record<string, string>>;
  id?: string | Computed<string>;
  importPath?: string | Computed<string>;
  importedFileChunkSize?: number | Computed<number>;
  kmsKeyId?: string | Computed<string>;
  perUnitStorageThroughput?: number | Computed<number>;
  region?: string | Computed<string>;
  securityGroupIds?: string[] | Computed<string[]>;
  skipFinalBackup?: boolean | Computed<boolean>;
  storageCapacity?: number | Computed<number>;
  storageType?: string | Computed<string>;
  subnetIds: string[] | Computed<string[]>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  tagsAll?: Record<string, string> | Computed<Record<string, string>>;
  throughputCapacity?: number | Computed<number>;
  weeklyMaintenanceStartTime?: string | Computed<string>;
  dataReadCacheConfiguration?: LustreFileSystem_DataReadCacheConfiguration[] | Computed<LustreFileSystem_DataReadCacheConfiguration[]>;
  logConfiguration?: LustreFileSystem_LogConfiguration[] | Computed<LustreFileSystem_LogConfiguration[]>;
  metadataConfiguration?: LustreFileSystem_MetadataConfiguration[] | Computed<LustreFileSystem_MetadataConfiguration[]>;
  rootSquashConfiguration?: LustreFileSystem_RootSquashConfiguration[] | Computed<LustreFileSystem_RootSquashConfiguration[]>;
  timeouts?: LustreFileSystem_Timeouts | Computed<LustreFileSystem_Timeouts>;
}

export interface LustreFileSystemAttrs {
  arn: string;
  autoImportPolicy: string;
  automaticBackupRetentionDays: number;
  backupId: string;
  copyTagsToBackups: boolean;
  dailyAutomaticBackupStartTime: string;
  dataCompressionType: string;
  deploymentType: string;
  dnsName: string;
  driveCacheType: string;
  efaEnabled: boolean;
  exportPath: string;
  fileSystemTypeVersion: string;
  finalBackupTags: Record<string, string>;
  id: string;
  importPath: string;
  importedFileChunkSize: number;
  kmsKeyId: string;
  mountName: string;
  networkInterfaceIds: string[];
  ownerId: string;
  perUnitStorageThroughput: number;
  region: string;
  securityGroupIds: string[];
  skipFinalBackup: boolean;
  storageCapacity: number;
  storageType: string;
  subnetIds: string[];
  tags: Record<string, string>;
  tagsAll: Record<string, string>;
  throughputCapacity: number;
  vpcId: string;
  weeklyMaintenanceStartTime: string;
  dataReadCacheConfiguration: LustreFileSystem_DataReadCacheConfiguration[];
  logConfiguration: LustreFileSystem_LogConfiguration[];
  metadataConfiguration: LustreFileSystem_MetadataConfiguration[];
  rootSquashConfiguration: LustreFileSystem_RootSquashConfiguration[];
  timeouts: LustreFileSystem_Timeouts;
}

export const LustreFileSystem: ResourceBinding<LustreFileSystemConfig, LustreFileSystemAttrs> = {
  wireType: "aws_fsx_lustre_file_system",
  fields: {
    autoImportPolicy: "auto_import_policy",
    automaticBackupRetentionDays: "automatic_backup_retention_days",
    backupId: "backup_id",
    copyTagsToBackups: "copy_tags_to_backups",
    dailyAutomaticBackupStartTime: "daily_automatic_backup_start_time",
    dataCompressionType: "data_compression_type",
    deploymentType: "deployment_type",
    driveCacheType: "drive_cache_type",
    efaEnabled: "efa_enabled",
    exportPath: "export_path",
    fileSystemTypeVersion: "file_system_type_version",
    finalBackupTags: "final_backup_tags",
    id: "id",
    importPath: "import_path",
    importedFileChunkSize: "imported_file_chunk_size",
    kmsKeyId: "kms_key_id",
    perUnitStorageThroughput: "per_unit_storage_throughput",
    region: "region",
    securityGroupIds: "security_group_ids",
    skipFinalBackup: "skip_final_backup",
    storageCapacity: "storage_capacity",
    storageType: "storage_type",
    subnetIds: "subnet_ids",
    tags: "tags",
    tagsAll: "tags_all",
    throughputCapacity: "throughput_capacity",
    weeklyMaintenanceStartTime: "weekly_maintenance_start_time",
    dataReadCacheConfiguration: {
      wireName: "data_read_cache_configuration",
      kind: "list",
      fields: LustreFileSystem_DataReadCacheConfigurationFields,
    },
    logConfiguration: {
      wireName: "log_configuration",
      kind: "list",
      fields: LustreFileSystem_LogConfigurationFields,
    },
    metadataConfiguration: {
      wireName: "metadata_configuration",
      kind: "list",
      fields: LustreFileSystem_MetadataConfigurationFields,
    },
    rootSquashConfiguration: {
      wireName: "root_squash_configuration",
      kind: "list",
      fields: LustreFileSystem_RootSquashConfigurationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LustreFileSystem_TimeoutsFields,
    },
  },
};
