// Code generated by `ubx sdk gen` from aws_ssm_quicksetup_configuration_managers. DO NOT EDIT.
package ssm_quicksetup

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SsmQuicksetupConfigurationManagers_ConfigurationManagersList_ConfigurationDefinitionSummaries struct {
	FirstClassParameters any
	Id any
	Type any
	TypeVersion any
}

type SsmQuicksetupConfigurationManagers_ConfigurationManagersList_StatusSummaries struct {
	LastUpdatedAt any
	Status any
	StatusDetails any
	StatusMessage any
	StatusType any
}

type SsmQuicksetupConfigurationManagers_ConfigurationManagersList struct {
	ConfigurationDefinitionSummaries any
	Description any
	ManagerArn any
	Name any
	StatusSummaries any
}

type SsmQuicksetupConfigurationManagers_Filters struct {
	Key any
	Values any
}

var SsmQuicksetupConfigurationManagers_FiltersFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Values": ubx.FieldSpec{WireName: "values"},
	}

type SsmQuicksetupConfigurationManagersConfig struct {
	Filters any
	MaxItems any
	StartingToken any
}

type SsmQuicksetupConfigurationManagersAttrs struct {
	ConfigurationManagersList any
	Filters any
	MaxItems any
	NextToken any
	StartingToken any
}

var SsmQuicksetupConfigurationManagers = ubx.DataSourceBinding{
	WireType: "aws_ssm_quicksetup_configuration_managers",
	Fields: ubx.FieldMap{
		"Filters": ubx.FieldSpec{
			WireName: "filters",
			Kind: "list",
			Fields: SsmQuicksetupConfigurationManagers_FiltersFields,
		},
		"MaxItems": ubx.FieldSpec{WireName: "max_items"},
		"StartingToken": ubx.FieldSpec{WireName: "starting_token"},
	},
}
