# Code generated by `ubx sdk gen` from aws_vpclattice_listener_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ListenerRule_Action_FixedResponse:
    status_code: Any = None

@dataclasses.dataclass
class ListenerRule_Action_Forward_TargetGroups:
    target_group_identifier: Any = None
    weight: Any = None

@dataclasses.dataclass
class ListenerRule_Action_Forward:
    target_groups: Any = None

@dataclasses.dataclass
class ListenerRule_Action:
    fixed_response: Any = None
    forward: Any = None

@dataclasses.dataclass
class ListenerRule_Match_HttpMatch_HeaderMatches_Match:
    contains: Any = None
    exact: Any = None
    prefix: Any = None

@dataclasses.dataclass
class ListenerRule_Match_HttpMatch_HeaderMatches:
    case_sensitive: Any = None
    name: Any = None
    match: Any = None

@dataclasses.dataclass
class ListenerRule_Match_HttpMatch_PathMatch_Match:
    exact: Any = None
    prefix: Any = None

@dataclasses.dataclass
class ListenerRule_Match_HttpMatch_PathMatch:
    case_sensitive: Any = None
    match: Any = None

@dataclasses.dataclass
class ListenerRule_Match_HttpMatch:
    method: Any = None
    header_matches: Any = None
    path_match: Any = None

@dataclasses.dataclass
class ListenerRule_Match:
    http_match: Any = None

@dataclasses.dataclass
class ListenerRule_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_ListenerRule_Action_FixedResponseFields = {
    "status_code": ubx.FieldSpec(wire_name="status_code"),
}

_ListenerRule_Action_Forward_TargetGroupsFields = {
    "target_group_identifier": ubx.FieldSpec(wire_name="target_group_identifier"),
    "weight": ubx.FieldSpec(wire_name="weight"),
}

_ListenerRule_Action_ForwardFields = {
    "target_groups": ubx.FieldSpec(
        wire_name="target_groups",
        kind="list",
        fields=_ListenerRule_Action_Forward_TargetGroupsFields,
    ),
}

_ListenerRule_ActionFields = {
    "fixed_response": ubx.FieldSpec(
        wire_name="fixed_response",
        kind="list",
        fields=_ListenerRule_Action_FixedResponseFields,
    ),
    "forward": ubx.FieldSpec(
        wire_name="forward",
        kind="list",
        fields=_ListenerRule_Action_ForwardFields,
    ),
}

_ListenerRule_Match_HttpMatch_HeaderMatches_MatchFields = {
    "contains": ubx.FieldSpec(wire_name="contains"),
    "exact": ubx.FieldSpec(wire_name="exact"),
    "prefix": ubx.FieldSpec(wire_name="prefix"),
}

_ListenerRule_Match_HttpMatch_HeaderMatchesFields = {
    "case_sensitive": ubx.FieldSpec(wire_name="case_sensitive"),
    "name": ubx.FieldSpec(wire_name="name"),
    "match": ubx.FieldSpec(
        wire_name="match",
        kind="list",
        fields=_ListenerRule_Match_HttpMatch_HeaderMatches_MatchFields,
    ),
}

_ListenerRule_Match_HttpMatch_PathMatch_MatchFields = {
    "exact": ubx.FieldSpec(wire_name="exact"),
    "prefix": ubx.FieldSpec(wire_name="prefix"),
}

_ListenerRule_Match_HttpMatch_PathMatchFields = {
    "case_sensitive": ubx.FieldSpec(wire_name="case_sensitive"),
    "match": ubx.FieldSpec(
        wire_name="match",
        kind="list",
        fields=_ListenerRule_Match_HttpMatch_PathMatch_MatchFields,
    ),
}

_ListenerRule_Match_HttpMatchFields = {
    "method": ubx.FieldSpec(wire_name="method"),
    "header_matches": ubx.FieldSpec(
        wire_name="header_matches",
        kind="list",
        fields=_ListenerRule_Match_HttpMatch_HeaderMatchesFields,
    ),
    "path_match": ubx.FieldSpec(
        wire_name="path_match",
        kind="list",
        fields=_ListenerRule_Match_HttpMatch_PathMatchFields,
    ),
}

_ListenerRule_MatchFields = {
    "http_match": ubx.FieldSpec(
        wire_name="http_match",
        kind="list",
        fields=_ListenerRule_Match_HttpMatchFields,
    ),
}

_ListenerRule_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ListenerRuleConfig:
    id: Any = None
    listener_identifier: Any = None
    name: Any = None
    priority: Any = None
    region: Any = None
    service_identifier: Any = None
    tags: Any = None
    tags_all: Any = None
    action: Any = None
    match: Any = None
    timeouts: Any = None

ListenerRule = ubx.ResourceBinding(
    wire_type="aws_vpclattice_listener_rule",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "listener_identifier": ubx.FieldSpec(wire_name="listener_identifier"),
        "name": ubx.FieldSpec(wire_name="name"),
        "priority": ubx.FieldSpec(wire_name="priority"),
        "region": ubx.FieldSpec(wire_name="region"),
        "service_identifier": ubx.FieldSpec(wire_name="service_identifier"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tags_all": ubx.FieldSpec(wire_name="tags_all"),
        "action": ubx.FieldSpec(
            wire_name="action",
            kind="list",
            fields=_ListenerRule_ActionFields,
        ),
        "match": ubx.FieldSpec(
            wire_name="match",
            kind="list",
            fields=_ListenerRule_MatchFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ListenerRule_TimeoutsFields,
        ),
    },
)
