# Code generated by `ubx sdk gen` from hashicorp/aws@6.58.0. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/aws", "version": "6.58.0"}

from .cache import Cache, CacheConfig
from .cached_iscsi_volume import CachedIscsiVolume, CachedIscsiVolumeConfig
from .file_system_association import FileSystemAssociation, FileSystemAssociationConfig
from .gateway import Gateway, GatewayConfig
from .nfs_file_share import NfsFileShare, NfsFileShareConfig
from .smb_file_share import SmbFileShare, SmbFileShareConfig
from .stored_iscsi_volume import StoredIscsiVolume, StoredIscsiVolumeConfig
from .tape_pool import TapePool, TapePoolConfig
from .upload_buffer import UploadBuffer, UploadBufferConfig
from .working_storage import WorkingStorage, WorkingStorageConfig
