// Code generated by `ubx sdk gen` from aws_ec2_id_format. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IdFormat_Statuses {
  deadline?: string | Computed<string>;
  resource?: string | Computed<string>;
  useLongIds?: boolean | Computed<boolean>;
}

export interface IdFormatConfig {
  resource?: string | Computed<string>;
}

export interface IdFormatAttrs {
  resource: string;
  statuses: IdFormat_Statuses[];
}

export const IdFormat: DataSourceBinding<IdFormatConfig, IdFormatAttrs> = {
  wireType: "aws_ec2_id_format",
  fields: {
    resource: "resource",
  },
};
