// Code generated by `ubx sdk gen` from aws_ec2_vpc_attribute. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface VpcAttribute_EnableDnsHostnames {
  value?: boolean | Computed<boolean>;
}

export interface VpcAttributeConfig {
  attribute: string | Computed<string>;
  dryRun?: boolean | Computed<boolean>;
  vpcId: string | Computed<string>;
}

export interface VpcAttributeAttrs {
  attribute: string;
  dryRun: boolean;
  /** <p>Describes a value for a resource attribute that is a Boolean value.</p> */
  enableDnsHostnames: VpcAttribute_EnableDnsHostnames;
  /** <p>Describes a value for a resource attribute that is a Boolean value.</p> */
  enableDnsSupport: VpcAttribute_EnableDnsHostnames;
  /** <p>Describes a value for a resource attribute that is a Boolean value.</p> */
  enableNetworkAddressUsageMetrics: VpcAttribute_EnableDnsHostnames;
  vpcId: string;
}

export const VpcAttribute: DataSourceBinding<VpcAttributeConfig, VpcAttributeAttrs> = {
  wireType: "aws_ec2_vpc_attribute",
  fields: {
    attribute: "attribute",
    dryRun: "dry_run",
    vpcId: "vpc_id",
  },
};
