// Code generated by `ubx sdk gen` from aws_resiliencehub_app_version_resource_mappings. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AppVersionResourceMappings_ResourceMappings_PhysicalResourceId {
  awsAccountId?: string | Computed<string>;
  awsRegion?: string | Computed<string>;
  identifier?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AppVersionResourceMappings_ResourceMappings {
  appRegistryAppName?: string | Computed<string>;
  eksSourceName?: string | Computed<string>;
  logicalStackName?: string | Computed<string>;
  mappingType?: string | Computed<string>;
  physicalResourceId?: AppVersionResourceMappings_ResourceMappings_PhysicalResourceId | Computed<AppVersionResourceMappings_ResourceMappings_PhysicalResourceId>;
  resourceGroupName?: string | Computed<string>;
  resourceName?: string | Computed<string>;
  terraformSourceName?: string | Computed<string>;
}

export interface AppVersionResourceMappingsConfig {
  appArn: string | Computed<string>;
  appVersion: string | Computed<string>;
  maxResults?: number | Computed<number>;
  nextToken?: string | Computed<string>;
}

export interface AppVersionResourceMappingsAttrs {
  appArn: string;
  appVersion: string;
  maxResults: number;
  nextToken: string;
  resourceMappings: AppVersionResourceMappings_ResourceMappings[];
}

export const AppVersionResourceMappings: DataSourceBinding<AppVersionResourceMappingsConfig, AppVersionResourceMappingsAttrs> = {
  wireType: "aws_resiliencehub_app_version_resource_mappings",
  fields: {
    appArn: "app_arn",
    appVersion: "app_version",
    maxResults: "max_results",
    nextToken: "next_token",
  },
};
