// Code generated by `ubx sdk gen` from aws_connect_campaigns_campaign. DO NOT EDIT.
package connectcampaigns

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Campaign_DialerConfig_AgentlessDialerConfig struct {
	// Allocates dialing capacity for this campaign between multiple active campaigns.
	DialingCapacity any
}

type Campaign_DialerConfig_PredictiveDialerConfig struct {
	// The bandwidth allocation of a queue resource.
	BandwidthAllocation any
	// Allocates dialing capacity for this campaign between multiple active campaigns.
	DialingCapacity any
}

type Campaign_DialerConfig struct {
	// Agentless Dialer config
	AgentlessDialerConfig any
	// Predictive Dialer config
	PredictiveDialerConfig any
	// Progressive Dialer config
	ProgressiveDialerConfig any
}

type Campaign_OutboundCallConfig_AnswerMachineDetectionConfig struct {
	// Enables detection of prompts (e.g., beep after after a voicemail greeting)
	AwaitAnswerMachinePrompt any
	// Flag to decided whether outbound calls should have answering machine detection enabled or not
	EnableAnswerMachineDetection any
}

type Campaign_OutboundCallConfig struct {
	// The configuration used for answering machine detection during outbound calls
	AnswerMachineDetectionConfig any
	// The identifier of the contact flow for the outbound call.
	ConnectContactFlowArn any
	// The queue for the call. If you specify a queue, the phone displayed for caller ID is the phone number specified in the queue. If you do not specify a queue, the queue defined in the contact flow is used. If you do not specify a queue, you must specify a source phone number.
	ConnectQueueArn any
	// The phone number associated with the Amazon Connect instance, in E.164 format. If you do not specify a source phone number, you must specify a queue.
	ConnectSourcePhoneNumber any
}

type Campaign_Tags struct {
	// The key of a tag attached to the Amazon Connect Campaigns campaign, used to categorize the resource for cost allocation, ownership, and access control. (AI-inferred)
	Key any
	// The string value paired with each tag key on the Amazon Connect campaigns campaign, used for identifying, organizing, and managing the resource. (AI-inferred)
	Value any
}

var Campaign_DialerConfig_AgentlessDialerConfigFields = ubx.FieldMap{
		"DialingCapacity": ubx.FieldSpec{WireName: "dialing_capacity"},
	}

var Campaign_DialerConfig_PredictiveDialerConfigFields = ubx.FieldMap{
		"BandwidthAllocation": ubx.FieldSpec{WireName: "bandwidth_allocation"},
		"DialingCapacity": ubx.FieldSpec{WireName: "dialing_capacity"},
	}

var Campaign_DialerConfigFields = ubx.FieldMap{
		"AgentlessDialerConfig": ubx.FieldSpec{
			WireName: "agentless_dialer_config",
			Kind: "object",
			Fields: Campaign_DialerConfig_AgentlessDialerConfigFields,
		},
		"PredictiveDialerConfig": ubx.FieldSpec{
			WireName: "predictive_dialer_config",
			Kind: "object",
			Fields: Campaign_DialerConfig_PredictiveDialerConfigFields,
		},
		"ProgressiveDialerConfig": ubx.FieldSpec{
			WireName: "progressive_dialer_config",
			Kind: "object",
			Fields: Campaign_DialerConfig_PredictiveDialerConfigFields,
		},
	}

var Campaign_OutboundCallConfig_AnswerMachineDetectionConfigFields = ubx.FieldMap{
		"AwaitAnswerMachinePrompt": ubx.FieldSpec{WireName: "await_answer_machine_prompt"},
		"EnableAnswerMachineDetection": ubx.FieldSpec{WireName: "enable_answer_machine_detection"},
	}

var Campaign_OutboundCallConfigFields = ubx.FieldMap{
		"AnswerMachineDetectionConfig": ubx.FieldSpec{
			WireName: "answer_machine_detection_config",
			Kind: "object",
			Fields: Campaign_OutboundCallConfig_AnswerMachineDetectionConfigFields,
		},
		"ConnectContactFlowArn": ubx.FieldSpec{WireName: "connect_contact_flow_arn"},
		"ConnectQueueArn": ubx.FieldSpec{WireName: "connect_queue_arn"},
		"ConnectSourcePhoneNumber": ubx.FieldSpec{WireName: "connect_source_phone_number"},
	}

var Campaign_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type CampaignConfig struct {
	// Amazon Connect Instance Arn
	ConnectInstanceArn any
	// The possible types of dialer config parameters
	DialerConfig any
	// Amazon Connect Campaign Name
	Name any
	// The configuration used for outbound calls.
	OutboundCallConfig any
	// One or more tags.
	Tags any
}

type CampaignAttrs struct {
	// Amazon Connect Campaign Arn
	Arn any
	// Amazon Connect Instance Arn
	ConnectInstanceArn any
	// The possible types of dialer config parameters
	DialerConfig any
	// Amazon Connect Campaign Name
	Name any
	// The configuration used for outbound calls.
	OutboundCallConfig any
	// One or more tags.
	Tags any
}

var Campaign = ubx.ResourceBinding{
	WireType: "aws_connect_campaigns_campaign",
	Fields: ubx.FieldMap{
		"ConnectInstanceArn": ubx.FieldSpec{WireName: "connect_instance_arn"},
		"DialerConfig": ubx.FieldSpec{
			WireName: "dialer_config",
			Kind: "object",
			Fields: Campaign_DialerConfigFields,
		},
		"Name": ubx.FieldSpec{WireName: "name"},
		"OutboundCallConfig": ubx.FieldSpec{
			WireName: "outbound_call_config",
			Kind: "object",
			Fields: Campaign_OutboundCallConfigFields,
		},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: Campaign_TagsFields,
		},
	},
}
