// Code generated by `ubx sdk gen` from aws_smsvoice_protect_configuration. DO NOT EDIT.
package smsvoice

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectConfiguration_CountryRuleSet_Mms struct {
	// The country code to which this MMS rule in the AWS SMS Voice protect configuration's country rule set applies, controlling MMS messaging restrictions for that country. (AI-inferred)
	CountryCode any
	// Determines whether MMS messages are allowed or blocked for the specified country rule set within the protect configuration. (AI-inferred)
	ProtectStatus any
}

type ProtectConfiguration_CountryRuleSet struct {
	// Defines a list of MMS messaging rules for a given country in the protect configuration, where each item in the list specifies an action to apply to MMS messages for that country. (AI-inferred)
	Mms any
	// The `sms` list under `country_rule_set` defines country-specific SMS protection rules for the protect configuration, allowing you to set per-country settings such as daily spend limits and opt-out behavior for SMS messages. (AI-inferred)
	Sms any
	// The voice property contains a list of voice-specific rule objects that control whether voice calls to and from the listed country are allowed or blocked in the protect configuration. (AI-inferred)
	Voice any
}

type ProtectConfiguration_Tags struct {
	Key any
	Value any
}

var ProtectConfiguration_CountryRuleSet_MmsFields = ubx.FieldMap{
		"CountryCode": ubx.FieldSpec{WireName: "country_code"},
		"ProtectStatus": ubx.FieldSpec{WireName: "protect_status"},
	}

var ProtectConfiguration_CountryRuleSetFields = ubx.FieldMap{
		"Mms": ubx.FieldSpec{
			WireName: "mms",
			Kind: "list",
			Fields: ProtectConfiguration_CountryRuleSet_MmsFields,
		},
		"Sms": ubx.FieldSpec{
			WireName: "sms",
			Kind: "list",
			Fields: ProtectConfiguration_CountryRuleSet_MmsFields,
		},
		"Voice": ubx.FieldSpec{
			WireName: "voice",
			Kind: "list",
			Fields: ProtectConfiguration_CountryRuleSet_MmsFields,
		},
	}

var ProtectConfiguration_TagsFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type ProtectConfigurationConfig struct {
	// Defines the per-country rules for the protect configuration, where each key is a two-letter country code and the value is a rule object containing Boolean flags for Sms, Voice, and Send that control whether messages can be sent to that destination. (AI-inferred)
	CountryRuleSet any
	// When set to true deletion protection is enabled and protect configuration cannot be deleted. By default this is set to false.
	DeletionProtectionEnabled any
	// An array of key-value pairs to apply to this resource.
	Tags any
}

type ProtectConfigurationAttrs struct {
	// The Amazon Resource Name (ARN) of the protect configuration.
	Arn any
	// Defines the per-country rules for the protect configuration, where each key is a two-letter country code and the value is a rule object containing Boolean flags for Sms, Voice, and Send that control whether messages can be sent to that destination. (AI-inferred)
	CountryRuleSet any
	// When set to true deletion protection is enabled and protect configuration cannot be deleted. By default this is set to false.
	DeletionProtectionEnabled any
	// The unique identifier for the protect configuration.
	ProtectConfigurationId any
	// An array of key-value pairs to apply to this resource.
	Tags any
}

var ProtectConfiguration = ubx.ResourceBinding{
	WireType: "aws_smsvoice_protect_configuration",
	Fields: ubx.FieldMap{
		"CountryRuleSet": ubx.FieldSpec{
			WireName: "country_rule_set",
			Kind: "object",
			Fields: ProtectConfiguration_CountryRuleSetFields,
		},
		"DeletionProtectionEnabled": ubx.FieldSpec{WireName: "deletion_protection_enabled"},
		"Tags": ubx.FieldSpec{
			WireName: "tags",
			Kind: "list",
			Fields: ProtectConfiguration_TagsFields,
		},
	},
}
