// Code generated by `ubx sdk gen` from aws_opensearch_dry_run_progress. DO NOT EDIT.
package opensearch

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DryRunProgress_DryRunConfig_AdvancedSecurityOptions_IamfederationOptions struct {
	Enabled any
	RolesKey any
	SubjectKey any
}

type DryRunProgress_DryRunConfig_AdvancedSecurityOptions_Jwtoptions struct {
	Enabled any
	JwksUrl any
	PublicKey any
	RolesKey any
	SubjectKey any
}

type DryRunProgress_DryRunConfig_AdvancedSecurityOptions_Samloptions_Idp struct {
	EntityId any
	MetadataContent any
}

type DryRunProgress_DryRunConfig_AdvancedSecurityOptions_Samloptions struct {
	Enabled any
	// <p>The SAML identity povider information.</p>
	Idp any
	RolesKey any
	SessionTimeoutMinutes any
	SubjectKey any
}

type DryRunProgress_DryRunConfig_AdvancedSecurityOptions struct {
	AnonymousAuthDisableDate any
	AnonymousAuthEnabled any
	Enabled any
	// <p>Output parameters showing the current IAM identity federation configuration.</p>
	IamfederationOptions any
	InternalUserDatabaseEnabled any
	// <p>Describes the JWT options configured for the domain.</p>
	Jwtoptions any
	// <p>Describes the SAML application configured for the domain.</p>
	Samloptions any
}

type DryRunProgress_DryRunConfig_Aimloptions_NaturalLanguageQueryGenerationOptions struct {
	CurrentState any
	DesiredState any
}

type DryRunProgress_DryRunConfig_Aimloptions_S3VectorsEngine struct {
	Enabled any
}

type DryRunProgress_DryRunConfig_Aimloptions struct {
	// <p>Container for parameters representing the state of the natural language query generation feature on the specified domain.</p>
	NaturalLanguageQueryGenerationOptions any
	// <p>Options for enabling S3 vectors engine features on the specified domain.</p>
	S3VectorsEngine any
	// <p>Configuration for serverless vector acceleration, which provides <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gpu-acceleration-vector-index.html">GPU-accelerated</a> vector search capabilities for improved performance on vector workloads.</p>
	ServerlessVectorAcceleration any
}

type DryRunProgress_DryRunConfig_AutoTuneOptions struct {
	ErrorMessage any
	// <p>The Auto-Tune state for the domain. For valid states see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/auto-tune.html">Auto-Tune for Amazon OpenSearch Service</a>. </p>
	State any
	UseOffPeakWindow any
}

type DryRunProgress_DryRunConfig_AutomatedSnapshotPauseOptions struct {
	Enabled any
	EndTime any
	StartTime any
	// <p>The state of the automated snapshot pause. Valid values are <code>Active</code>, <code>Completed</code>, <code>Scheduled</code>, and <code>Disabled</code>.</p>
	State any
}

type DryRunProgress_DryRunConfig_ChangeProgressDetails struct {
	ChangeId any
	ConfigChangeStatus any
	InitiatedBy any
	LastUpdatedTime any
	Message any
	StartTime any
}

type DryRunProgress_DryRunConfig_ClusterConfig_NodeOptions_NodeConfig struct {
	Count any
	Enabled any
	Type any
}

type DryRunProgress_DryRunConfig_ClusterConfig_NodeOptions struct {
	NodeConfig any
	NodeType any
}

type DryRunProgress_DryRunConfig_ClusterConfig_ZoneAwarenessConfig struct {
	AvailabilityZoneCount any
}

type DryRunProgress_DryRunConfig_ClusterConfig struct {
	// <p>Container for the parameters required to enable cold storage for an OpenSearch Service domain. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cold-storage.html">Cold storage for Amazon OpenSearch Service</a>.</p>
	ColdStorageOptions any
	DedicatedMasterCount any
	DedicatedMasterEnabled any
	DedicatedMasterType any
	InstanceCount any
	InstanceType any
	MultiAzwithStandbyEnabled any
	NodeOptions any
	WarmCount any
	WarmEnabled any
	WarmType any
	// <p>The zone awareness configuration for an Amazon OpenSearch Service domain.</p>
	ZoneAwarenessConfig any
	ZoneAwarenessEnabled any
}

type DryRunProgress_DryRunConfig_CognitoOptions struct {
	Enabled any
	IdentityPoolId any
	RoleArn any
	UserPoolId any
}

type DryRunProgress_DryRunConfig_DeploymentStrategyOptions struct {
	// <p>Specifies the deployment strategy for the domain. Valid values are <code>Default</code> and <code>CapacityOptimized</code>.</p>
	DeploymentStrategy any
}

type DryRunProgress_DryRunConfig_DomainEndpointOptions struct {
	CustomEndpoint any
	// <p>The Amazon Resource Name (ARN) of the domain. See <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/index.html">Identifiers for IAM Entities </a> in <i>Using Amazon Web Services Identity and Access Management</i> for more information. </p>
	CustomEndpointCertificateArn any
	CustomEndpointEnabled any
	EnforceHttps any
	TlssecurityPolicy any
}

type DryRunProgress_DryRunConfig_Ebsoptions struct {
	Ebsenabled any
	Iops any
	Throughput any
	VolumeSize any
	// <p>The type of EBS volume that a domain uses. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/opensearch-createupdatedomains.html#opensearch-createdomain-configure-ebs">Configuring EBS-based storage</a>.</p>
	VolumeType any
}

type DryRunProgress_DryRunConfig_EncryptionAtRestOptions struct {
	Enabled any
	KmsKeyId any
}

type DryRunProgress_DryRunConfig_IdentityCenterOptions struct {
	EnabledApiaccess any
	IdentityCenterApplicationArn any
	IdentityCenterInstanceArn any
	// <p>An Amazon Web Services Region, such as <code>us-east-1</code>.</p>
	IdentityCenterInstanceRegion any
	IdentityStoreId any
	RolesKey any
	SubjectKey any
}

type DryRunProgress_DryRunConfig_LogPublishingOptions struct {
	CloudWatchLogsLogGroupArn any
	Enabled any
}

type DryRunProgress_DryRunConfig_ModifyingProperties struct {
	ActiveValue any
	Name any
	PendingValue any
	ValueType any
}

type DryRunProgress_DryRunConfig_OffPeakWindowOptions_OffPeakWindow_WindowStartTime struct {
	Hours any
	Minutes any
}

type DryRunProgress_DryRunConfig_OffPeakWindowOptions_OffPeakWindow struct {
	// <p>The desired start time for an <a href="https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_OffPeakWindow.html">off-peak maintenance window</a>.</p>
	WindowStartTime any
}

type DryRunProgress_DryRunConfig_OffPeakWindowOptions struct {
	Enabled any
	// <p>A custom 10-hour, low-traffic window during which OpenSearch Service can perform mandatory configuration changes on the domain. These actions can include scheduled service software updates and blue/green Auto-Tune enhancements. OpenSearch Service will schedule these actions during the window that you specify.</p> <p>If you don't specify a window start time, it defaults to 10:00 P.M. local time.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/off-peak.html">Defining off-peak maintenance windows for Amazon OpenSearch Service</a>.</p>
	OffPeakWindow any
}

type DryRunProgress_DryRunConfig_ServiceSoftwareOptions struct {
	AutomatedUpdateDate any
	Cancellable any
	CurrentVersion any
	Description any
	NewVersion any
	OptionalDeployment any
	UpdateAvailable any
	UpdateStatus any
}

type DryRunProgress_DryRunConfig_SnapshotOptions struct {
	AutomatedSnapshotStartHour any
}

type DryRunProgress_DryRunConfig_SoftwareUpdateOptions struct {
	AutoSoftwareUpdateEnabled any
	UseLatestServiceSoftwareForBlueGreen any
}

type DryRunProgress_DryRunConfig_Vpcoptions struct {
	AvailabilityZones any
	EgressEnabled any
	SecurityGroupIds any
	SubnetIds any
	Vpcid any
}

type DryRunProgress_DryRunConfig struct {
	// <p>Access policy rules for an Amazon OpenSearch Service domain endpoint. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html#createdomain-configure-access-policies">Configuring access policies</a>. The maximum size of a policy document is 100 KB.</p>
	AccessPolicies any
	// <p>Exposes native OpenSearch configuration values from <code>opensearch.yml</code>. The following advanced options are available: </p> <ul> <li> <p>Allows references to indexes in an HTTP request body. Must be <code>false</code> when configuring access to individual sub-resources. Default is <code>true</code>.</p> </li> <li> <p>Specifies the percentage of heap space allocated to field data. Default is unbounded.</p> </li> </ul> <p>For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html#createdomain-configure-advanced-options">Advanced cluster parameters</a>.</p>
	AdvancedOptions any
	// <p>Container for fine-grained access control settings.</p>
	AdvancedSecurityOptions any
	// <p>Container for parameters representing the state of machine learning features on the specified domain.</p>
	Aimloptions any
	// <p>The Amazon Resource Name (ARN) of the domain. See <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/index.html">Identifiers for IAM Entities </a> in <i>Using Amazon Web Services Identity and Access Management</i> for more information. </p>
	Arn any
	// <p>The Auto-Tune settings for a domain, displayed when enabling or disabling Auto-Tune.</p>
	AutoTuneOptions any
	// <p>Specifies the automated snapshot pause options for the domain. These options allow you to temporarily pause automated snapshots for a specified time period.</p>
	AutomatedSnapshotPauseOptions any
	// <p>Container for information about a configuration change happening on a domain.</p>
	ChangeProgressDetails any
	// <p>Container for the cluster configuration of an OpenSearch Service domain. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html">Creating and managing Amazon OpenSearch Service domains</a>.</p>
	ClusterConfig any
	// <p>Container for the parameters required to enable Cognito authentication for an OpenSearch Service domain. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cognito-auth.html">Configuring Amazon Cognito authentication for OpenSearch Dashboards</a>.</p>
	CognitoOptions any
	Created any
	Deleted any
	// <p>Specifies the deployment strategy options for the domain.</p>
	DeploymentStrategyOptions any
	// <p>Options to configure a custom endpoint for an OpenSearch Service domain.</p>
	DomainEndpointOptions any
	DomainEndpointV2HostedZoneId any
	// <p>Unique identifier for an OpenSearch Service domain.</p>
	DomainId any
	// <p>The name of an OpenSearch Service domain. Domain names are unique across the domains owned by an account within an Amazon Web Services Region.</p>
	DomainName any
	DomainProcessingStatus any
	// <p>Container for the parameters required to enable EBS-based storage for an OpenSearch Service domain.</p>
	Ebsoptions any
	// <p>Specifies whether the domain should encrypt data at rest, and if so, the Key Management Service (KMS) key to use. Can only be used when creating a new domain or enabling encryption at rest for the first time on an existing domain. You can't modify this parameter after it's already been specified.</p>
	EncryptionAtRestOptions any
	// <p>The domain endpoint to which index and search requests are submitted. For example, <code>search-imdb-movies-oopcnjfn6ugo.eu-west-1.es.amazonaws.com</code> or <code>doc-imdb-movies-oopcnjfn6u.eu-west-1.es.amazonaws.com</code>.</p>
	Endpoint any
	// <p>The domain endpoint to which index and search requests are submitted. For example, <code>search-imdb-movies-oopcnjfn6ugo.eu-west-1.es.amazonaws.com</code> or <code>doc-imdb-movies-oopcnjfn6u.eu-west-1.es.amazonaws.com</code>.</p>
	EndpointV2 any
	Endpoints any
	// <p>The engine mode for the domain. Valid values are <code>GENERAL</code> (the standard OpenSearch engine) and <code>OPTIMIZED</code>. If you don't specify an engine mode, <code>GENERAL</code> is used. <code>OPTIMIZED</code> requires OpenSearch 3.5 or later, OpenSearch Optimized instance types (OR1, OR2, OM2, or OI2) for the data tier, and is available only for the <code>OBSERVABILITY</code> use cases. The engine mode can't be changed after the domain is created.</p>
	EngineMode any
	EngineVersion any
	// <p>Settings container for integrating IAM Identity Center with OpenSearch UI applications, which enables enabling secure user authentication and access control across multiple data sources. This setup supports single sign-on (SSO) through IAM Identity Center, allowing centralized user management.</p>
	IdentityCenterOptions any
	IpaddressType any
	LogPublishingOptions any
	ModifyingProperties any
	// <p>Enables or disables node-to-node encryption. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ntn.html">Node-to-node encryption for Amazon OpenSearch Service</a>.</p>
	NodeToNodeEncryptionOptions any
	// <p>Options for a domain's <a href="https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_OffPeakWindow.html">off-peak window</a>, during which OpenSearch Service can perform mandatory configuration changes on the domain.</p>
	OffPeakWindowOptions any
	Processing any
	// <p>The current status of the service software for an Amazon OpenSearch Service domain. For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/service-software.html">Service software updates in Amazon OpenSearch Service</a>.</p>
	ServiceSoftwareOptions any
	// <p>The time, in UTC format, when OpenSearch Service takes a daily automated snapshot of the specified domain. Default is <code>0</code> hours.</p>
	SnapshotOptions any
	// <p>Options for configuring service software updates for a domain.</p>
	SoftwareUpdateOptions any
	UpgradeProcessing any
	// <p>The primary use case for the domain, which determines the default configuration and the engine modes that are available. Valid values are <code>SEARCH</code> (full-text search, e-commerce, content discovery, and hybrid and semantic search), <code>VECTOR</code> (k-NN and semantic search, and retrieval-augmented generation), <code>OBSERVABILITY</code> (logs, metrics, traces, and dashboards), and <code>MIXED</code> (a combination of search and analytics). If you don't specify a use case, <code>MIXED</code> is used.</p>
	UseCase any
	// <p>Information about the subnets and security groups for an Amazon OpenSearch Service domain provisioned within a virtual private cloud (VPC). For more information, see <a href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc.html">Launching your Amazon OpenSearch Service domains using a VPC</a>. This information only exists if the domain was created with <code>VPCOptions</code>.</p>
	Vpcoptions any
}

type DryRunProgress_DryRunProgressStatus_ValidationFailures struct {
	Code any
	Message any
}

type DryRunProgress_DryRunProgressStatus struct {
	CreationDate any
	DryRunId any
	DryRunStatus any
	UpdateDate any
	ValidationFailures any
}

type DryRunProgress_DryRunResults struct {
	DeploymentType any
	Message any
}

type DryRunProgressConfig struct {
	// <p>The name of an OpenSearch Service domain. Domain names are unique across the domains owned by an account within an Amazon Web Services Region.</p>
	DomainName any
	DryRunId any
	LoadDryRunConfig any
}

type DryRunProgressAttrs struct {
	// <p>The name of an OpenSearch Service domain. Domain names are unique across the domains owned by an account within an Amazon Web Services Region.</p>
	DomainName any
	// <p>The current status of an OpenSearch Service domain.</p>
	DryRunConfig any
	DryRunId any
	// <p>Information about the progress of a pre-upgrade dry run analysis.</p>
	DryRunProgressStatus any
	// <p>Results of a dry run performed in an update domain request.</p>
	DryRunResults any
	LoadDryRunConfig any
}

var DryRunProgress = ubx.DataSourceBinding{
	WireType: "aws_opensearch_dry_run_progress",
	Fields: ubx.FieldMap{
		"DomainName": ubx.FieldSpec{WireName: "domain_name"},
		"DryRunId": ubx.FieldSpec{WireName: "dry_run_id"},
		"LoadDryRunConfig": ubx.FieldSpec{WireName: "load_dry_run_config"},
	},
}
