// Code generated by `ubx sdk gen` from aws_servicecatalog_product_view. DO NOT EDIT.
package servicecatalog

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ProductView_ProductViewSummary struct {
	Distributor any
	HasDefaultPath any
	Id any
	Name any
	Owner any
	ProductId any
	ShortDescription any
	SupportDescription any
	SupportEmail any
	SupportUrl any
	Type any
}

type ProductView_ProvisioningArtifacts struct {
	CreatedTime any
	Description any
	Guidance any
	Id any
	Name any
}

type ProductViewConfig struct {
	AcceptLanguage any
	Id any
}

type ProductViewAttrs struct {
	AcceptLanguage any
	Id any
	// <p>Summary information about a product view.</p>
	ProductViewSummary any
	ProvisioningArtifacts any
}

var ProductView = ubx.DataSourceBinding{
	WireType: "aws_servicecatalog_product_view",
	Fields: ubx.FieldMap{
		"AcceptLanguage": ubx.FieldSpec{WireName: "accept_language"},
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
