# Code generated by `ubx sdk gen` from aws_ec2_transit_gateway_route_table_propagation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TransitGatewayRouteTablePropagationConfig:
    id: Any = None
    region: Any = None
    transit_gateway_attachment_id: Any = None
    transit_gateway_route_table_id: Any = None

TransitGatewayRouteTablePropagation = ubx.ResourceBinding(
    wire_type="aws_ec2_transit_gateway_route_table_propagation",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "region": ubx.FieldSpec(wire_name="region"),
        "transit_gateway_attachment_id": ubx.FieldSpec(wire_name="transit_gateway_attachment_id"),
        "transit_gateway_route_table_id": ubx.FieldSpec(wire_name="transit_gateway_route_table_id"),
    },
)
